- hassio/__main__.py
- hassio/api/__init__.py
- hassio/api/homeassistant.py
- hassio/api/host.py
- hassio/api/supervisor.py
- hassio/api/util.py
- hassio/const.py
- setup.py
- Add ping to API
- host/info give now in every case data back
- Fix close handing in loop.
- Add api options validate
> Release 0.5

- API.md
- hassio/__main__.py
- hassio/api/__init__.py
- hassio/api/supervisor.py
- hassio/config.py
- hassio/const.py
- hassio/core.py
- hassio/dock/__init__.py
- hassio/dock/supervisor.py
- hassio/host_controll.py
- version.json
- version_beta.json
Now it need no support for supervisor update on host.
> Allow supervisor to update itself.

- API.md
- MANIFEST.in
- hassio/addons/built-in.json
- hassio/addons/data.py
- hassio/addons/validate.py
- hassio/api/addons.py
- hassio/const.py
- version.json
> Release 0.22

- API.md
- hassio/addons/__init__.py
- hassio/api/__init__.py
- hassio/api/addons.py
- hassio/api/homeassistant.py
- hassio/dock/__init__.py
- hassio/dock/supervisor.py
Add 2 new api call:
- /homeassistant/restart
- /addons/{addon}/restart
> Add restart support to homeassistant and add-ons

- API.md
- hassio/addons/__init__.py
- hassio/addons/data.py
- hassio/api/addons.py
- hassio/api/supervisor.py
- hassio/const.py
- Add `build` to addons api
- Better add-on data layer handling
- Fix wrong version in installed addons
- Fix start not running add-on after update
> Update data handling of addons

- hassio/addons/data.py
- hassio/addons/validate.py
- hassio/const.py
- hassio/dock/addon.py
Add to addon config a Attribute `devices` in form of:
`<path_on_host>:<path_in_container>:<cgroup_permissions>`
> Add device support

- hassio/addons/data.py
- hassio/addons/validate.py
- hassio/dock/addon.py
now all mappings from `map` are read only. if you Need write Access, use `map: ["config:rw"]`
> Add policy for mappings

- hassio/addons/__init__.py
- hassio/config.py
- hassio/core.py
- hassio/dock/__init__.py
- hassio/dock/addon.py
- hassio/dock/homeassistant.py
- hassio/dock/supervisor.py
- hassio/tools.py
- Cleanup code
- Make more robust
- Add a real cleanup solution for container/Images
- Remove all workarounds
> WIP: Refactory / Cleanup docker base

- hassio/addons/data.py
- hassio/addons/validate.py
Allow custom options and disable schema
> Allow custom options without validate

- hassio/const.py
- hassio/dock/util.py
- version.json
- Support new custom base image
> Release 0.42

- API.md
- hassio/addons/data.py
- hassio/api/addons.py
- hassio/api/homeassistant.py
- hassio/config.py
- hassio/const.py
- hassio/core.py
- hassio/dock/__init__.py
- hassio/dock/homeassistant.py
- hassio/homeassistant.py
- hassio/snapshots/__init__.py
- hassio/snapshots/snapshot.py
- hassio/snapshots/validate.py
- hassio/tasks.py
- hassio/tools.py
- hassio/validate.py
- add landingpage support
- cleanup handling with json file for store data
- make a own object for homeassistant + config
- allow custom homeassistant Image
Breaking Change:
- devices will reset to []
> Add landingpage / cleanup homeassistant core handling

- hassio/addons/addon.py
- setup.py
Should better scale then that what we do at the moment with options merge
> Use deepmerge for options

- hassio/dock/addon.py
https://github.com/home-assistant/hassio/issues/160
> Better cleanup for local build add-ons

- hassio/addons/__init__.py
- hassio/addons/addon.py
- hassio/bootstrap.py
- hassio/config.py
- hassio/const.py
- hassio/core.py
- hassio/dns.py
- hassio/dock/__init__.py
- hassio/dock/addon.py
- hassio/dock/homeassistant.py
- hassio/dock/interface.py
- hassio/dock/network.py
- hassio/dock/supervisor.py
- hassio/homeassistant.py
- hassio/tools.py
- hassio/validate.py
- Use fix IPs for internal network
- Link all add-ons to host network addons
- Link add-ons hostname internal
> WIP: Network docker hassio

- hassio/addons/addon.py
- hassio/addons/data.py
- hassio/addons/validate.py
- Allow to use `int(min, max)` and `float(min, max)`
- New schema type `match` to allow use regex: `match(^(?:man|woman)$)`
> More schema options

- API.md
- hassio/addons/addon.py
- hassio/addons/git.py
- hassio/addons/validate.py
- hassio/api/addons.py
- hassio/const.py
- hassio/dock/addon.py
> Add support for kernel gpio interface

- hassio/addons/validate.py
Avoid problems if options will change between updates
> Remove unknown options from input

- hassio/addons/validate.py
https://github.com/home-assistant/hassio/issues/219
> Update docker image validate

- API.md
- hassio/api/host.py
- hassio/hardware.py
> Show hardware GPIO interface

- hassio/dock/homeassistant.py
I hope this fix the ffmpeg zombie problem
> Use tini for home-assistant docker

- hassio/api/util.py
- Print a error on invalid json
> Print error on invalid json

- hassio/addons/addon.py
- hassio/addons/validate.py
- hassio/api/__init__.py
- hassio/api/addons.py
- hassio/api/homeassistant.py
- hassio/dock/addon.py
- hassio/dock/homeassistant.py
- hassio/hardware.py
- hassio/validate.py
> Allow event stream over api proxy

- API.md
- hassio/addons/addon.py
- hassio/addons/validate.py
- hassio/api/homeassistant.py
- hassio/api/snapshots.py
- hassio/docker/addon.py
- hassio/docker/homeassistant.py
- hassio/docker/interface.py
- hassio/homeassistant.py
- hassio/snapshots/snapshot.py
- hassio/snapshots/validate.py
- hassio/validate.py
We use now the same technical as on add-ons to evaluate special device mapping
> Remove home-assistant devices options

- hassio/addons/addon.py
- hassio/hardware.py
- hassio/snapshots/snapshot.py
- hassio/supervisor.py
> Div. Bugfixes for 0.79

- hassio/docker/__init__.py
- hassio/docker/network.py
It is default false, but if so we are sure for future.
> Disable ipv6 / Clear search domain names

- README.md
Fixes a couple of `markdownlint` styling issues and some minor spelling errors.
> Fixes markdownlint & spelling issue in the README file

- hassio/api/__init__.py
- hassio/api/proxy.py
Fix: https://github.com/home-assistant/hassio/issues/310
> Add GET param support

- hassio/docker/__init__.py
> Change timeout to 300

- API.md
- hassio/addons/addon.py
- hassio/api/homeassistant.py
- hassio/const.py
- hassio/core.py
- hassio/docker/addon.py
- hassio/homeassistant.py
- hassio/snapshots/__init__.py
- hassio/snapshots/snapshot.py
- hassio/snapshots/validate.py
- hassio/tasks.py
- hassio/validate.py
> Add support for home-assistant bootup

- hassio/api/homeassistant.py
- hassio/docker/__init__.py
- hassio/docker/homeassistant.py
- hassio/homeassistant.py
> Bugfix Check Config for Home-Assistant

- setup.py
> Update docker API

- hassio/addons/built-in.json
> Improve names for built-in repos

- hassio/addons/git.py
- hassio/const.py
- hassio/validate.py
Add new schema to repository URL: `http://github.com/xy/repo#my_branch`
> Allow to use branch on repositories

- hassio/utils/dt.py
> Fix URL for freegeoip

- hassio/api/__init__.py
- hassio/docker/interface.py
- hassio/homeassistant.py
- Cleanup home-assistant docker on restart to avoid problem with static files inside data layer.
> Abstract restart logic

- hassio/docker/__init__.py
> Update docker timeout to 900sec

- API.md
- hassio/addons/addon.py
- hassio/addons/validate.py
- hassio/api/addons.py
- hassio/const.py
- hassio/docker/addon.py
> Add support to map devicetree into add-on

- hassio/api/security.py
- hassio/bootstrap.py
> Use machine-id from filesystem

- hassio/addons/git.py
Implement:
Fix: #551 
Fixup:
Fix: https://github.com/home-assistant/hassio-addons/issues/303
Fix: #553
> Fix problem with Repositories

- hassio/__main__.py
- hassio/addons/addon.py
- hassio/addons/utils.py
- hassio/snapshots/validate.py
- pylintrc
- tox.ini
> Reset readonly on remove data

- hassio/core.py
- hassio/hassos.py
- hassio/supervisor.py
- hassio/updater.py
- hassio/utils/dt.py
> Fix timeout on freegeoip

- Dockerfile
Fix: https://github.com/home-assistant/hassio-build/issues/101
> Update uvloop to 0.11.0

- hassio/homeassistant.py
This bug are only available if the request have a content type
> Fix bug with proxy

- hassio/api/__init__.py
- hassio/core.py
- hassio/misc/dns.py
Workaround: https://github.com/MagicStack/uvloop/issues/180
> Timeout shutdown

- hassio/addons/validate.py
> Adapt regex validation to allow docker images from other registries

- hassio/addons/data.py
- hassio/utils/json.py
> Fix UnicodeDecodeError with read json file

- hassio/docker/addon.py
> Fix gpio mapping on amd64 systems

- requirements.txt
https://github.com/MagicStack/uvloop/releases
> Update uvloop 0.11.2

- hassio/docker/homeassistant.py
> Fix /share inside whitelist

- hassio/homeassistant.py
Handle access token expiration.
> Handle access token expiration

- hassio/docker/interface.py
> Make Label handling more robust

- hassio/docker/interface.py
> Fix not exists label bug

- API.md
- hassio/api/__init__.py
- hassio/api/security.py
- hassio/api/version.py
- hassio/const.py
> Add version endpoint

- hassio/api/proxy.py
https://developers.home-assistant.io/docs/en/auth_api.html#long-lived-access-token
> Add support for long live token

- hassio/const.py
- hassio/host/alsa.py
- hassio/misc/hardware.py
> fix: use a different convention to handle multiple devices on same card

- hassio/docker/addon.py
Solves https://github.com/home-assistant/hassio/issues/805
> Provide options for legacy add-ons

- hassio/addons/utils.py
> Bugfix stack trace on remove

- hassio/addons/data.py
> Fix wrong UTF-8 config files

- hassio/addons/addon.py
> Fix image arch version on restore/update

- hassio/misc/hardware.py
revert #944 
That will not work inside a container. Maybe if we map all rules into the container and do the same as on host, it could work.
Anyway, we move over to privileged modus for supervisor. Maybe, that fix also some issue
> Revert dev link

- API.md
- hassio/api/__init__.py
- hassio/api/homeassistant.py
- hassio/core.py
- hassio/docker/hassos_cli.py
- hassio/docker/homeassistant.py
- hassio/docker/interface.py
- hassio/homeassistant.py
- hassio/tasks.py
Add new API call: `/homeassistant/rebuild` to rebuild the container from image
> Make homeassistant container constant

- API.md
- hassio/addons/addon.py
- hassio/api/__init__.py
- hassio/api/ingress.py
- hassio/bootstrap.py
- hassio/const.py
- hassio/core.py
- hassio/coresys.py
- hassio/homeassistant.py
- hassio/ingress.py
- hassio/tasks.py
- hassio/utils/__init__.py
- hassio/utils/dt.py
- hassio/validate.py
- tests/conftest.py
- tests/test_ingress.py
Add session control to ingress for frontend
> Init ingress session boarder / lookup

- hassio/addons/addon.py
- Update config with a rebuild too
- Only allow rebuild if version don't change
> Improve add-on rebuild

- API.md
- hassio/addons/addon.py
- hassio/addons/validate.py
- hassio/api/addons.py
- hassio/api/ingress.py
- hassio/ingress.py
- hassio/validate.py
- tests/test_ingress.py
Support dynamic port handling for host add-ons with `ingress_port: 0`
> Support dynamic ingress port

- hassio/api/homeassistant.py
- hassio/homeassistant.py
> Force auto API password

- hassio/store/repository.py
Fix: #1087 #1085 https://github.com/home-assistant/home-assistant/issues/23389
> Fix error with repository without repository.json

- hassio/core.py
Print a big error message.
Fix: #1117
> Don't break on supervisor update

- hassio/api/proxy.py
- hassio/homeassistant.py
> Forward Params on API requests

- hassio/dns.py
Reverts home-assistant/hassio#1215
> Revert "Call update of resolv later"

- hassio/addons/__init__.py
> Cleanup ingress panel on add-on uninstall

- API.md
- hassio/api/dns.py
- hassio/const.py
- hassio/core.py
- hassio/dbus/__init__.py
- hassio/dbus/hostname.py
- hassio/dbus/interface.py
- hassio/dbus/nmi_dns.py
- hassio/dns.py
- hassio/host/__init__.py
- hassio/host/info.py
- hassio/host/network.py
- hassio/utils/gdbus.py
> Add support to read Host DNS

- setup.py
Fixes accidental string concatenation in classifiers list
> Fixes accidental string concatenation in classifiers list

- hassio/addons/__init__.py
- hassio/docker/__init__.py
- hassio/docker/network.py
- hassio/homeassistant.py
- https://github.com/home-assistant/hassio/issues/1309
- https://github.com/moby/moby/issues/23302
> Prune network/interface on repair

- hassio/secrets.py
Fixes #1344
Removed the use of vol at this point (since it is filtered, it became pretty useless I guess 🤷‍♂)
Removed NoneType as supported secrets value, but added in boolean types.
> Fix secrets containing unsupported types

- hassio/addons/validate.py
- hassio/api/addons.py
- hassio/api/dns.py
- hassio/api/homeassistant.py
- hassio/api/supervisor.py
- hassio/discovery/services/adguard.py
- hassio/discovery/services/almond.py
- hassio/discovery/services/deconz.py
- hassio/discovery/services/home_panel.py
- hassio/discovery/services/mqtt.py
- hassio/discovery/validate.py
- hassio/dns.py
- hassio/docker/dns.py
- hassio/services/modules/mqtt.py
- hassio/snapshots/validate.py
- hassio/validate.py
- tests/test_validate.py
> Dns update

- API.md
- hassio/api/hassos.py
- hassio/core.py
- hassio/dbus/rauc.py
- hassio/docker/interface.py
- hassio/hassos.py
- hassio/utils/tar.py
As next step, we remove partition handling from HassOS
> Offload rauc logic with partition handling

- hassio/api/__init__.py
- hassio/api/ingress.py
Fix: #1420 
Need same code on HA
> Allow big files on Ingress

- requirements.txt
Reverts home-assistant/hassio-supervisor#1427
> Revert "Update aiohttp to version 3.6.2 again"

- hassio/addons/validate.py
- hassio/services/__init__.py
- hassio/services/const.py
- hassio/services/data.py
- hassio/services/modules/mysql.py
- hassio/services/validate.py
Adds support for MySQL as an add-on service, allowing add-ons to find and use it.
> Add MySQL service support

- hassio/discovery/services/unifi.py
Adds the UniFi discovery service.
> Add UniFi discovery service

- hassio/addons/utils.py
If an add-on is protected by Home Assistant / let spend +1
> Change rating for ingress add-on

- hassio/bootstrap.py
> Change log level INFO to use black text color

- hassio/bootstrap.py
Reverts home-assistant/supervisor#1459
> Revert "Change log level INFO to use black text color"

- hassio/api/utils.py
Fix: https://github.com/home-assistant/hassio-addons/issues/1049
> Fix overwrite authorization / ingress

- hassio/hassos.py
> Set timeout of 10min for download OTA

- hassio/misc/hardware.py
- tests/misc/test_hardware.py
Fix: #1516
was merged wrong into master and add more tests
> Extend video & add tests

- hassio/addons/addon.py
> Fix webui option

- supervisor/host/apparmor.py
- supervisor/supervisor.py
> Fix supervisor update flow with apparmor

- supervisor/docker/audio.py
> Check if SND is loaded

- supervisor/__main__.py
- supervisor/bootstrap.py
- supervisor/const.py
We finish now the migration to `/run` instead old `/var/run`. Look some linux system have issue with it. This should help with #1563
> Enforce env check

- supervisor/addons/addon.py
- supervisor/docker/homeassistant.py
- supervisor/homeassistant.py
> Fix Issue with pulse folder

- supervisor/snapshots/__init__.py
This will restore repositories for a partial snapshot if at least 1 addon is selected.
Fixes #1526
> Restore repositories with partial snapshot

- API.md
Typos, style, periods and wording.
> Minor re-work

- supervisor/addons/__init__.py
- supervisor/ingress.py
Adds a small loop to keep generating random Ingress ports until a unique one is found.
Fixes #1680
> Fix possible Ingress port collisions

- tests/conftest.py
- tests/test_arch.py
- tests/utils/test_tarfile.py
- Address the flake8 and pylint lint warnings in the tests.
> Delint tests

- supervisor/config.py
This is a small fix for obvious mistake
> Fix config version setter

- .gitignore
I'm running MyPy in my environment, which currently triggers vscode's git extension with thousands of changes :(
> Add mypy cache files to .gitignore

- setup.cfg
- supervisor/addons/build.py
- supervisor/addons/validate.py
- supervisor/bootstrap.py
- supervisor/core.py
- supervisor/coresys.py
- supervisor/dbus/utils.py
- supervisor/docker/__init__.py
- supervisor/docker/addon.py
- supervisor/docker/interface.py
- supervisor/homeassistant.py
- supervisor/host/services.py
- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
- supervisor/snapshots/__init__.py
- supervisor/snapshots/snapshot.py
- supervisor/store/__init__.py
- supervisor/utils/__init__.py
- supervisor/utils/gdbus.py
- supervisor/utils/tar.py
- supervisor/utils/validate.py
- supervisor/validate.py
- tests/addons/test_config.py
- tests/test_validate.py
Configures flake8 similar to our core repository, enabling doctests.
Corrected all warnings as a result of that.
> Improve flake8 configuration and pydocstyle fixes

- pylintrc
- supervisor/addons/addon.py
- supervisor/addons/model.py
- supervisor/coresys.py
- supervisor/store/addon.py
Completes the type hinting in CoreSys.
Added a None check to all getters to ensure the returned type is correct. While it adds a bit of code, it prevents NoneType checking in the rest of the codebase.
This file now passes MyPy without anything disabled.
> Complete typehinting in CoreSys

- supervisor/discovery/__init__.py
fixed typo in discovery/__init__.py
> Fix typo in discovery log message

- supervisor/api/addons.py
Fixes a review comment by @MartinHjelmare 
<https://github.com/home-assistant/supervisor/pull/1767#pullrequestreview-422583385>
> Fix additional parameter on exception

- supervisor/config.py
- supervisor/core.py
- supervisor/validate.py
Additional for https://github.com/home-assistant/operating-system/pull/741
> Add the current supervisor version as default

- supervisor/addons/addon.py
- supervisor/addons/model.py
- supervisor/api/addons.py
- supervisor/api/discovery.py
- supervisor/api/hardware.py
- supervisor/api/homeassistant.py
- supervisor/bootstrap.py
- supervisor/dbus/interface.py
- supervisor/docker/__init__.py
- supervisor/docker/addon.py
- supervisor/docker/interface.py
- supervisor/homeassistant.py
- supervisor/plugins/__init__.py
- supervisor/services/__init__.py
- supervisor/utils/tar.py
- supervisor/validate.py
This PR is a collection of minor changes to the codebase.
- Type hinting
- Pythonic changes
- isort
- `DBusInterface` is now abstract
98 MyPy issues left 😉
> Collection of minor changes

- .devcontainer/devcontainer.json
- .github/workflows/ci.yaml
- .github/workflows/matchers/check-executables-have-shebangs.json
- .github/workflows/matchers/check-json.json
- .github/workflows/matchers/flake8.json
- .github/workflows/matchers/hadolint.json
- .github/workflows/matchers/pylint.json
- .github/workflows/matchers/python.json
- .pre-commit-config.yaml
- codecov.yaml
- requirements_tests.txt
- supervisor/addons/addon.py
- tests/utils/test_tarfile.py
Adds GitHub Actions and pre-commit for the Supervisor, including some additions:
- JQ has been replaced by pre-commit, including problem matcher
- Added isort
- Added pyupgrade to prevent old patterns (I've removed all of its warnings in previous PRs)
- Check for files with executable permissions that should not have them
- Add testing for both Python 3.7 & 3.8
- Add coverage handling & codecov.io reporting (comments by codecov disabled after merge to dev)
> Add QA/CI to Supervisor

- .github/workflows/ci.yaml
> Drop last references 3.7

- supervisor/homeassistant.py
> Fix rollback timeout on new versions with early stage UI

- supervisor/docker/interface.py
- supervisor/host/info.py
- supervisor/misc/hardware.py
- tests/host/test_info.py
- tests/misc/test_hardware.py
- Add free disk space info method.
- Add info log about available space on docker image install error.
> Add free disk space log on docker install error

- API.md
- requirements.txt
- supervisor/api/supervisor.py
- supervisor/bootstrap.py
- supervisor/config.py
- supervisor/const.py
- supervisor/core.py
- supervisor/validate.py
- tests/conftest.py
If diagnostic is None, user have not take a choise and it's disabled. Otherwise it's False/True.
> Add diagnostics support

- supervisor/bootstrap.py
- supervisor/const.py
- supervisor/docker/audio.py
- supervisor/docker/homeassistant.py
> Allow Core access to dbus for bluetooth

- supervisor/core.py
Sentry: 31d26ac278e845239843a4b8d2642627
Sentry:  f8d8a41cb6834654bb94279d38054bf5
I think they run watchtower or somethings similarly
> Fix dev outside stable channel

- supervisor/core.py
- supervisor/docker/__init__.py
- supervisor/misc/hwmon.py
Set not supported if:
- Wrong docker logger
- Wrong storage for docker
- No access to udev monitor
> Set not supported with wrong docker configuration

- supervisor/ingress.py
- I saw this error from Sentry.
> Fix ingress unbound local errors

- supervisor/misc/filter.py
- tests/misc/test_filter_data.py
Change coresys.supported -> coresys.core.supported
> Fix attribute in sentry data_filter

- supervisor/api/info.py
- supervisor/api/security.py
- supervisor/coresys.py
- supervisor/docker/addon.py
- supervisor/docker/audio.py
- supervisor/docker/cli.py
- supervisor/docker/dns.py
- supervisor/docker/homeassistant.py
- supervisor/docker/multicast.py
- supervisor/misc/filter.py
- tests/conftest.py
- tests/misc/test_filter_data.py
> Machine ID for user/sentry & cleanups

- supervisor/core.py
- supervisor/docker/__init__.py
> Don't break startup with corrupt docker filesystem

- supervisor/core.py
This check is not realy needed, was a bit oversize from me...
> Simplify OS check

- supervisor/addons/addon.py
- supervisor/api/addons.py
- supervisor/api/homeassistant.py
- supervisor/api/proxy.py
- supervisor/api/supervisor.py
- supervisor/auth.py
- supervisor/bootstrap.py
- supervisor/core.py
- supervisor/coresys.py
- supervisor/discovery/__init__.py
- supervisor/homeassistant/__init__.py
- supervisor/homeassistant/api.py
- supervisor/homeassistant/core.py
- supervisor/homeassistant/secrets.py
- supervisor/ingress.py
- supervisor/misc/tasks.py
- supervisor/snapshots/__init__.py
Make the code a bit cleaner and help to understand the code
> Group all homeassistant/core into a module

- API.md
- supervisor/addons/__init__.py
- supervisor/addons/addon.py
- supervisor/addons/model.py
- supervisor/addons/validate.py
- supervisor/api/addons.py
- supervisor/api/supervisor.py
- supervisor/bootstrap.py
- supervisor/const.py
- supervisor/core.py
- supervisor/docker/interface.py
- supervisor/exceptions.py
- supervisor/hassos.py
- supervisor/homeassistant/core.py
- supervisor/host/__init__.py
- supervisor/misc/hardware.py
- supervisor/misc/scheduler.py
- supervisor/misc/tasks.py
- supervisor/plugins/audio.py
- supervisor/plugins/cli.py
- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
- supervisor/supervisor.py
- supervisor/validate.py
- tests/addons/test_config.py
- tests/misc/test_scheduler.py
- tests/test_validate.py
Monitor container + allow to monitor an application with port / http requests
> Watchdog for Add-ons

- API.md
- supervisor/api/__init__.py
- supervisor/api/addons.py
Add an API endpoint to addons to validate the current options
> Adds options_validate API

- supervisor/exceptions.py
- supervisor/utils/log_format.py
- tests/utils/test_log_format.py
Fixes https://github.com/home-assistant/supervisor/issues/2051
> Capture typeerror exception

- API.md
- Fix grammar.
- Indent text and code per bullet to easier see what bullet is targeted.
> Clean api doc

- supervisor/api/supervisor.py
- supervisor/store/__init__.py
- supervisor/store/git.py
- supervisor/store/repository.py
- tests/conftest.py
- tests/store/test_custom_repository.py
Ensure that we only handle valid add-on repositories.
> Addon repositories

- supervisor/utils/json.py
- tests/test_core_state.py
- tests/utils/test_json.py
- tests/utils/test_tarfile.py
Set permissions for saved JSON files to 600.
> Set permissions on JSON files

- supervisor/api/__init__.py
> Make docker API more Consistency to exists

- requirements.txt
> Pin yarl to 1.5.1

- requirements.txt
- supervisor/const.py
> Cherry-pick commits for 247

- requirements.txt
Add brotlipy for ingress. We have it also on core docker image
> Add brotlipy for ingress / like core

- supervisor/api/__init__.py
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/676
> Rename snapshot remove like other API calls

- supervisor/core.py
> Mark system without using NetworkManager as unsupported

- supervisor/api/network.py
- tests/api/test_network.py
> Return default network connection

- supervisor/api/snapshots.py
Adds content-disposition header for snapshot downloads to signal to the client what the name should be.
> Add content-disposition header to snapshot download

- supervisor/api/__init__.py
- supervisor/api/security.py
- supervisor/api/utils.py
- supervisor/core.py
- tests/api/test_security.py
- tests/conftest.py
- tests/test_core_state.py
Make API soon available and show error on cli/api that the system is on startup
> Make api soon available

- supervisor/plugins/cli.py
This was only needed for old OS which we not support anymore. However, they can update to new OS.
> CLI: remote latest tag, not needed anymore

- supervisor/core.py
- supervisor/exceptions.py
- supervisor/homeassistant/core.py
Help to get HA back running after a reboot or poweroff with corrupt core container.
> Fix corrupt container on startup

- supervisor/docker/observer.py
- supervisor/misc/tasks.py
- supervisor/plugins/__init__.py
- supervisor/plugins/observer.py
> Observer: rebuild container if the application don't response

- supervisor/api/security.py
> Add api access for resolution call

- supervisor/api/__init__.py
- supervisor/api/resolution.py
- supervisor/api/security.py
- tests/api/test_resolution.py
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/687
> Use /info for resolution API

- supervisor/plugins/__init__.py
> Bump cli min version to 2020.10.0

- supervisor/snapshots/__init__.py
If a snapshot slug already exists, overwrite it.
- This PR fixes or closes issue: fixes #2145
> Overwrite snapshot if slug already exist

- supervisor/misc/tasks.py
> Fix old issues attach to Issues list

- supervisor/api/__init__.py
- supervisor/api/auth.py
- supervisor/api/security.py
- supervisor/auth.py
- tests/conftest.py
- tests/test_auth.py
The change is less as maybe it can look at first view. It's like the speed dial for wifi. Timing attacks with that are only possible if you know the password and it returns anyway True. The old password maybe still working sometimes but we speak about add-ons and the new password work all time.
- This PR fixes or closes issue: fixes: https://github.com/home-assistant/hassio-addons/issues/1630
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/688
> Speedup HA core auth

- supervisor/homeassistant/core.py
Make sure, preinstalled landing page get started soon as possible
> Support preinstalled landingpage

- tests/api/test_network.py
> Add test for network docker

- supervisor/docker/interface.py
- supervisor/plugins/dns.py
- supervisor/store/git.py
> Correct typo in log message

- supervisor/docker/stats.py
- tests/docker/test_stats.py
- tests/fixtures/container_stats.json
Normalize docker CPU stats
- This PR fixes or closes issue: fixes #2131
> Normalize CPU stats

- supervisor/plugins/__init__.py
- supervisor/plugins/audio.py
- supervisor/plugins/cli.py
- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
- supervisor/plugins/observer.py
- supervisor/resolution/const.py
- tests/resolution/test_resolution_manager.py
> Fix new version handling with Plugins

- .github/workflows/ci.yaml
> Add build check to CI

- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
There is no reason to restart this each supervisor restart
> Fix plugin restart

- supervisor/api/__init__.py
- supervisor/core.py
- tests/conftest.py
Make startup more robust for unknown issues. Since we don't know what can be happening, we need first see on sentry before we can create issues/suggestions.
> Make startup more stable

- supervisor/plugins/dns.py
> Revert dns restart logic

- .github/workflows/builder.yml
> Use matrix builds

- supervisor/store/git.py
Fixes <https://discordapp.com/channels/330944238910963714/330944238910963714/770361818848690196>
> Fix missing await

- .github/workflows/builder.yml
Needs: <https://github.com/home-assistant/actions/pull/17>
More info: <docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch>
> Add workflow_dispatch for manual action run

- supervisor/addons/__init__.py
- supervisor/docker/__init__.py
- supervisor/docker/interface.py
- supervisor/docker/network.py
- supervisor/homeassistant/core.py
- supervisor/misc/tasks.py
A new way to handle the issue https://github.com/moby/moby/issues/23302. It allows recovering from that issue on the host and hassio network before the issue faces the user. After more than 4 years, the bug is now a feature of docker which needs to be addressed in a better way as we did before. I solve today the only issue (based on sentry) which can completely destroy the core container after an update/restart. We have 30k issue (mostly from the watchdog, and faced around 110 active user installation). …
> New fix for stale container on network

- supervisor/plugins/audio.py
- supervisor/plugins/dns.py
> Init template sooner

- supervisor/docker/homeassistant.py
Look like there is a container that can not be started, should be not marked as initialized.
Status can be: created, restarting, running, removing, paused, exited, or dead
> Fix initialized state on dead/removing/pause containers

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
> Fix missing metadata in the issue template

- rootfs/etc/pulse/client.conf
> Fix pulse cookie error

- supervisor/ingress.py
Adds more logs to session validation, so we can know what caused it to invalidate it.
> Adds more logs to session validation

- supervisor/api/__init__.py
- supervisor/api/ingress.py
- tests/api/test_ingress.py
- tests/api/test_network.py
Add a new API endpoint `POST /api/ingress/validate_session` that will extend the validation of the current session and returns a 401 if it is no longer valid.
I couldn't get auth working in the API test, so decided to stub it out. Not sure how the other API tests do it. Still verify that we call the check auth function.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/714
> Add validate session API

- supervisor/dbus/network/interface.py
- tests/api/test_network.py
> Fix all interface are primary

- supervisor/auth.py
- supervisor/bootstrap.py
- supervisor/core.py
- supervisor/docker/interface.py
- supervisor/homeassistant/secrets.py
- supervisor/plugins/dns.py
Some of the loggers are changed to debug, but they are very usefully for bug hunting.
> Cleanup some logger

- supervisor/api/network.py
- tests/api/test_network.py
> Fix gateway None on API

- supervisor/dbus/payloads/interface_update.tmpl
- supervisor/host/const.py
- supervisor/host/network.py
- tests/dbus/payloads/test_interface_update_payload.py
> Fix auth mode WEP

- supervisor/dbus/network/accesspoint.py
- supervisor/host/network.py
- supervisor/utils/gdbus.py
- tests/fixtures/org_freedesktop_NetworkManager_AccessPoint_43099.json
- tests/fixtures/org_freedesktop_NetworkManager_AccessPoint_43100.json
- tests/utils/test_gvariant_parser.py
> Handle dbus single byte

- supervisor/exceptions.py
- supervisor/host/network.py
- supervisor/utils/gdbus.py
> Fix error if a wlan scan is allready running

- supervisor/dbus/payloads/interface_update.tmpl
- supervisor/host/network.py
- tests/dbus/payloads/test_interface_update_payload.py
> Fix handling with open or wpa-psk

- supervisor/dbus/payloads/generate.py
- supervisor/host/network.py
> Fix wifi conversation

- supervisor/dbus/payloads/interface_update.tmpl
> Revert: psk is not readable and only exists on initial

- supervisor/host/network.py
> Improve the error logging with new DBusProgramError

- supervisor/hassos.py
- supervisor/homeassistant/__init__.py
- supervisor/plugins/audio.py
- supervisor/plugins/cli.py
- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
- supervisor/plugins/observer.py
- supervisor/supervisor.py
> Fix show update if version is None

- supervisor/misc/filter.py
- tests/misc/test_filter_data.py
> Send issues with sentry report

- supervisor/core.py
- supervisor/host/network.py
- supervisor/job/decorator.py
This split out the check so you see in the logs if it is the supervisor or the host internet that failed
> Split check for internet connection to help troubleshooting

- supervisor/dbus/payloads/interface_update.tmpl
- tests/dbus/payloads/test_interface_update_payload.py
Needed for: https://github.com/home-assistant/operating-system/pull/986
> Enable support for mdns & llmnr for host

- supervisor/dbus/payloads/interface_update.tmpl
- tests/dbus/payloads/test_interface_update_payload.py
> Fix auto interface method

- supervisor/addons/__init__.py
- supervisor/api/resolution.py
- supervisor/const.py
- supervisor/core.py
- supervisor/misc/filter.py
- supervisor/misc/hwmon.py
- supervisor/resolution/__init__.py
- supervisor/resolution/const.py
- supervisor/resolution/evaluate.py
- supervisor/store/data.py
- tests/api/test_resolution.py
- tests/job/test_job_decorator.py
- tests/misc/test_filter_data.py
- tests/resolution/test_resolution_manager.py
The healthy have the same issue as unsupported had. It's hard to find out later why somethings are marked as unhealthy. Now we can better follow what was happening to disable auto features.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/724
> Handle Unhealthy like Unsupported

- supervisor/jobs/__init__.py
- supervisor/store/__init__.py
- tests/jobs/test_job_manager.py
Job updates can not be a coroutine. It's too expensive of calling and switching the context each update. We need to decouple that and also later add a sync version for docker operations. We can use the call_soon to ping the jobmanager to send it to HA event bus.
> Remove coroutine from job update

- supervisor/jobs/decorator.py
- supervisor/misc/tasks.py
- supervisor/store/__init__.py
- supervisor/updater.py
- tests/jobs/test_job_decorator.py
Split host/system internet. Some jobs need only a working supervisor internet, other relays on Host internet because of Docker.
> Enforce internet host/system

- supervisor/dbus/const.py
- supervisor/dbus/network/__init__.py
- supervisor/host/network.py
> Check if connectivity check if available on host

- supervisor/api/host.py
- supervisor/api/info.py
- supervisor/dbus/__init__.py
- supervisor/hassos.py
- supervisor/host/__init__.py
- supervisor/misc/tasks.py
- supervisor/resolution/evaluations/network_manager.py
- supervisor/resolution/evaluations/systemd.py
- tests/host/test_supported_features.py
- tests/resolution/evaluation/test_evaluate_network_manager.py
- tests/resolution/evaluation/test_evaluate_systemd.py
> Make host feature cheaper to call and relay on it

- supervisor/core.py
On slow system it's missing what is going on. It can take a while until the container gets started, so it looks at it is freezen.
> Missing log what going on

- requirements.txt
- supervisor/utils/json.py
> Use atomic writes to make it more stable again full disk

- requirements.txt
> Use Brotli instead of brotlipy

- supervisor/const.py
- supervisor/store/__init__.py
> Rename add-ons repository

- supervisor/docker/interface.py
- supervisor/resolution/const.py
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/15687
> Add log about ratelimit

- supervisor/dbus/const.py
- supervisor/host/network.py
- supervisor/utils/gdbus.py
- tests/conftest.py
Wait for `org.freedesktop.NetworkManager.Connection.Active.PropertiesChanged` signal before refreshing interface information
> Fix missing primary interface after change

- supervisor/store/__init__.py
Removes HEALTHY condition from update_repositories, we don't need it there and it stops the store from loading.
> Remove HEALTHY from update_repositories

- supervisor/addons/__init__.py
- supervisor/docker/interface.py
- supervisor/homeassistant/core.py
- supervisor/snapshots/__init__.py
> Add jobs decorator to add-ons/snapshot/core and remove 404 hack

- rootfs/etc/services.d/supervisor/finish
- supervisor/__main__.py
- supervisor/api/__init__.py
- supervisor/api/supervisor.py
- supervisor/core.py
- supervisor/jobs/decorator.py
- supervisor/misc/tasks.py
- supervisor/supervisor.py
- tests/jobs/test_job_decorator.py
Restart is needed to get the supervisor healthy again after the issue was fixed by the sysadmin. Since part of the system can break which makes that the supervisor is not 100% started, only a full restart is essential to make sure all is fully working again. I call that "soft" because we only restart it inside container with s6-overlay
> Soft restart supervisor

- supervisor/snapshots/__init__.py
Currently, the healthty condition is not needed to create a snapshot, let's remove that until we need it.
> Change snapshot create conditions

- supervisor/api/__init__.py
- supervisor/api/jobs.py
- supervisor/api/security.py
- supervisor/jobs/__init__.py
- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- supervisor/jobs/validate.py
- supervisor/resolution/const.py
- supervisor/resolution/evaluate.py
- supervisor/resolution/evaluations/job_conditions.py
- tests/api/test_jobs.py
- tests/conftest.py
- tests/jobs/test_job_decorator.py
- tests/resolution/evaluation/test_evaluate_job_conditions.py
Allow for development to disable job conditions. This breaks for sure workflows and leads on the issue, but for development machines, it doesn't matter. I would suggest not use this feature on a production instance.
- This PR fixes or closes issue: fixes #2288
> Add JobManager API ignore

- supervisor/misc/filter.py
- tests/misc/test_filter_data.py
> Fix sentry resoluton messages

- supervisor/dbus/network/__init__.py
> Don't send DBusProgramError to sentry

- supervisor/resolution/checks/base.py
- supervisor/resolution/checks/free_space.py
- tests/resolution/check/test_check.py
- tests/resolution/check/test_check_free_space.py
Until now, only a fixup can clean an issue. Checks only check and create issues but can't dismiss an issue if they do not exist anymore. Now it can.
- This PR fixes or closes issue: fixes #2299
> Allow check to cleanup issues

- supervisor/misc/hardware.py
> Strip device names

- scripts/test_env.sh
- supervisor/api/supervisor.py
- supervisor/exceptions.py
- supervisor/resolution/const.py
- supervisor/resolution/fixup.py
- supervisor/resolution/fixups/base.py
- supervisor/resolution/fixups/clear_full_snapshot.py
- supervisor/resolution/fixups/store_execute_reload.py
- supervisor/resolution/fixups/store_execute_remove.py
- supervisor/resolution/fixups/store_execute_reset.py
- supervisor/store/__init__.py
- supervisor/store/const.py
- supervisor/store/git.py
- supervisor/store/repository.py
- supervisor/utils/__init__.py
- tests/conftest.py
- tests/resolution/fixup/test_store_execute_reload.py
- tests/resolution/fixup/test_store_execute_remove.py
- tests/resolution/fixup/test_store_execute_reset.py
- tests/store/test_custom_repository.py
I ported the remove function from factory reset PR.
> Handle Store suggestion

- supervisor/store/data.py
> Reset on invalid filesystem

- supervisor/store/data.py
Now we can handle it on the device and don't need more info on sentry for this
> Remove corrupt FS on store sentry report

- tests/utils/test_remove_folder.py
> Add tests for remove function

- supervisor/resolution/fixups/store_execute_remove.py
- supervisor/store/repository.py
- tests/resolution/fixup/test_store_execute_remove.py
- tests/store/test_custom_repository.py
> Fix: cleanup repository from list

- supervisor/dbus/payloads/generate.py
- supervisor/dbus/payloads/interface_update.tmpl
- tests/dbus/payloads/test_interface_update_payload.py
> Fix byte order for network DNS settings

- supervisor/dbus/network/configuration.py
- supervisor/dbus/network/setting.py
- supervisor/dbus/payloads/interface_update.tmpl
- supervisor/host/network.py
- tests/api/test_network.py
- tests/dbus/payloads/test_interface_update_payload.py
> Use persistent MAC address instead clone / don't touch default

- supervisor/dbus/payloads/generate.py
- tests/dbus/payloads/test_interface_update_payload.py
> Fix NM naming schema

- supervisor/api/__init__.py
- supervisor/api/network.py
- tests/api/test_network.py
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/742
> Add network reload to api

- supervisor/misc/filter.py
- supervisor/resolution/evaluate.py
- supervisor/resolution/evaluations/container.py
- tests/misc/test_filter_data.py
- tests/resolution/evaluation/test_evaluate_container.py
We have still unsupported installation which spams our sentry because of watchtower like containers. Let get a list to exclude such installation from sentry/supported.
> Send list of images to sentry

- supervisor/misc/filter.py
- tests/misc/test_filter_data.py
> Fix sentry with sets

- supervisor/const.py
- supervisor/hassos.py
- supervisor/updater.py
- supervisor/validate.py
> Support OTA url over version files

- supervisor/dbus/__init__.py
- supervisor/dbus/hostname.py
- supervisor/dbus/interface.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/rauc.py
- supervisor/dbus/systemd.py
> Make dbus connection more robust

- supervisor/bootstrap.py
Sentry STDLIB default module spamming so much, that we lose information to finding a solution or bug. This tries to make the data useful again.
> Fix sentry stdlib spam

- supervisor/addons/__init__.py
- supervisor/exceptions.py
- supervisor/homeassistant/core.py
- supervisor/jobs/decorator.py
- supervisor/snapshots/__init__.py
- supervisor/supervisor.py
- supervisor/updater.py
- tests/jobs/test_job_decorator.py
Return False is not useful because most parts of the system use the new error handling over exception. Now we raise on an error while the condition fails to trigger the code which normally will be executed if somethings are not executed. But it's also possible to just return which is also needed like on internal jobs.
> Improve error handling with job condition

- supervisor/dbus/network/__init__.py
- This PR fixes or closes issue: fixes #2330
> Fix KeyError in connectivity_enabled

- supervisor/dbus/payloads/generate.py
- tests/dbus/payloads/test_interface_update_payload.py
> Fix NM byte switch for ipv6 nameserver

- supervisor/utils/json.py
Allow to see issue with validation on Sentry
> Upgrade json config handler logging to critical

- supervisor/core.py
> Fix issue with mark system wrong as rollback

- supervisor/api/network.py
> Actually use the vlan_struct

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> Add changes to release drafter

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
> Add note for unsupported system

- .github/ISSUE_TEMPLATE/config.yml
> Show link for help user with unsupported systems

- supervisor/snapshots/__init__.py
> Fix typo in log message when completing snapshot

- requirements.txt
Pin `docker-py` to this commit which fixes the filtering after Docker 20.10
https://github.com/docker/docker-py/commit/1757c974fa3a05b0e9b783af85242b18df09d05d
- This PR fixes or closes issue: fixes #2359
> Fix filtering with docker 20.10.x

- requirements.txt
https://github.com/docker/docker-py/compare/4.4.0...4.4.1
This includes the commit we had pinned with `git+git://github.com/docker/docker-py@1757c974fa3a05b0e9b783af85242b18df09d05d#docker=4.4.1dev0`
> Bump docker to 4.4.1

- requirements.txt
- supervisor/utils/json.py
> Bump awesomeversion from 20.12.4 to 20.12.5

- supervisor/store/__init__.py
Changes `refrence` to `reference`
> Fix typo in reference

- supervisor/store/git.py
Happening because of: https://github.com/home-assistant/supervisor/pull/2409
> Fix missing repository

- supervisor/store/git.py
Adds support for submodule updates in the add-on store.
> Update git to support updates of submodules

- supervisor/store/git.py
> Fix submodules - check if it is needed or not

- supervisor/api/auth.py
Make `AUTHORIZATION` more spec compliance
- This PR fixes or closes issue: fixes #2423
> Auth: Improve authorisation

- .github/workflows/builder.yml
Fixes https://github.com/home-assistant/supervisor/runs/1688628593?check_suite_focus=true
> Ignore wheels on release

- supervisor/store/git.py
> Fix submodule update

- supervisor/resolution/notify.py
> Update wording in notification

- supervisor/store/git.py
Make submodule update more robust with corrupt git/submodules. This code work now an all repository they reported issue in the last couple of weeks.
> Fix: stable issue with corrupt git repository / submodule

- supervisor/discovery/services/ozw.py
- supervisor/discovery/services/zwave_js.py
- tests/discovery/test_ozw.py
- tests/discovery/test_zwave_js.py
> Add discovery support for zwave_js

- supervisor/resolution/fixup.py
- supervisor/resolution/fixups/store_execute_reload.py
- supervisor/resolution/fixups/store_execute_reset.py
> Improve fixups with Job condition checks

- supervisor/resolution/checks/core_security.py
- supervisor/resolution/notify.py
- tests/resolution/check/test_check_core_security.py
> Update alert notification

- supervisor/resolution/checks/core_security.py
> Fix OSError with custom component check

- supervisor/api/security.py
Not all info commands are anymore on the second path of the URL.
> Fix API info calls access

- requirements.txt
- supervisor/dbus/network/__init__.py
> New version logic NM

- .github/workflows/check_pr_labels.yml
> Add action to check PR labels

- requirements.txt
[Release notes](https://github.com/ludeeus/awesomeversion/releases/tag/21.1.4)
[Diff](https://github.com/ludeeus/awesomeversion/compare/21.1.3...21.1.4)
> Bump awesomeversion from 21.1.3 to 21.1.4

- supervisor/docker/stats.py
Suppress TypeError in `_calc_block_io`
> Add TypeError guard for docker stats

- .github/workflows/check_pr_labels.yml
Limit label check to label events
> Limit label check

- supervisor/addons/options.py
- tests/addons/test_options.py
> Improve device selection and show device by id if available

- supervisor/docker/addon.py
> Fix mknod creating of the device on runtime time

- scripts/run-supervisor.sh
- supervisor/docker/addon.py
- supervisor/hardware/const.py
- supervisor/hardware/policy.py
- tests/hardware/test_policy.py
> Handle GPIO / VIDEO map with subystem

- requirements.txt
https://github.com/ludeeus/awesomeversion/releases/tag/21.1.5
https://github.com/ludeeus/awesomeversion/compare/21.1.4...21.1.5
> Bump awesomeversion from 21.1.4 to 21.1.5

- supervisor/hardware/const.py
- supervisor/hardware/monitor.py
Address @ludeeus comments about bad named udev/supervisor device actions.
> Cleanup supervisor/udev device action / add GPIO

- supervisor/hardware/helper.py
- tests/hardware/test_helper.py
Filter out vcs devices as we anyway filter the virtual tty devices. No one care about that things.
> Filter out virtual vcs devices

- supervisor/store/data.py
- supervisor/store/git.py
> Handle corrupt store branch / ignore local reset on corruption

- supervisor/api/network.py
- supervisor/homeassistant/core.py
- supervisor/jobs/__init__.py
- tests/api/test_network.py
> Typofix exsist -> exist

- supervisor/addons/build.py
- supervisor/docker/addon.py
Don't report issues to sentry for a user which experiment with something new.
> Validate build env before using it

- supervisor/addons/build.py
Fixes:
```
21-02-01 10:16:24 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/local_ssh
21-02-01 10:16:24 ERROR (MainThread) [supervisor.jobs] Unhandled exception: all() takes exactly one argument (2 given)
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 61, in wrapper
return await self._method(*args, **kwargs)
File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
await addon.instance.install(store.version, store.image)
File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
return await method(api, *args, **kwargs)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File …
```
> Fix add-on is_valid check

- .github/workflows/check_pr_labels.yml
Rerun the PR label check on `pull_request.synchronize` events (new push to branch)
> Rerun label check on synchronize

- supervisor/addons/model.py
- supervisor/addons/validate.py
- supervisor/docker/addon.py
- supervisor/docker/homeassistant.py
- tests/addons/test_config.py
Docker shares the shared memory (shm) with the host if we map `/dev` into containers. Changing IPC settings have no effect, but we can mask shm with a tmpfs (which is it anyway).
There is a small "view" bug, it shows 2 mounts for shm, but it's only one mount. The bug is also known in Kubernetes or other container orchestrators: ie. https://success.mirantis.com/article/more-than-one-dev-shm-mount-in-the-host-namespace (just we have no issue with that) - However, mask mounts is a common way for handling that and also docker using the same. This view bug can be fixed with a later docker update or so.
I clean up an not really used add-on feature, which we merged in the early days, and did id complete wrong 🤦 
- Link to …
> Fix handling with shm and shared /dev

- requirements.txt
https://github.com/ludeeus/awesomeversion/releases/tag/21.2.0
> Bump awesomeversion from 21.1.8 to 21.2.0

- supervisor/hardware/monitor.py
Process devices again in the udev monitor loop. Otherwise, it's too fast to get all details on the device.
> Lookup udev device in monitor thread

- supervisor/hardware/monitor.py
> Make sure device is ready initialize on udev

- supervisor/addons/validate.py
Small typo I noticed when someone posted a copy&paste of an error message in the Discord #beta channel.
> Typo: depircated -> deprecated

- supervisor/api/hardware.py
> Change verbosity for hardware.trigger API

- supervisor/addons/addon.py
- supervisor/snapshots/validate.py
> Fix add-on state was not fast reflected

- supervisor/addons/validate.py
> Make add-on file schema more future approved

- rootfs/etc/cont-init.d/udev.sh
We can be faced with the same issue as we had on beta with Core Container. Apply the same handling.
> Apply old udev handling like core container

- supervisor/jobs/decorator.py
> Show the current core state on message

- supervisor/docker/stats.py
https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats
> Fix memory stats calc

- supervisor/addons/__init__.py
> Fix cleanup with changed image

- supervisor/supervisor.py
> Change Supervisor update flow with AppArmor

- supervisor/addons/options.py
- tests/addons/test_options.py
> Fix UI options without filter

- .github/workflows/builder.yml
- build.json
> Use Alpine 3.13

- .github/ISSUE_TEMPLATE/bug_report.yml
Small tweaks to the issue form:
- Add some sections
- Re-ordering
- Fixes a broken link in the introduction text
> Small tweaks to issue form

- supervisor/hardware/policy.py
> Add support for hiddev on USB

- supervisor/hardware/policy.py
> Add hidraw to USB

- supervisor/docker/addon.py
> Mask folder /dev/bus/usb RW

- supervisor/docker/addon.py
Reverts home-assistant/supervisor#2555
> Revert "Mask folder /dev/bus/usb RW"

- supervisor/core.py
A few simple grammar and typo corrections, 
> Fix Typos in LOGGER

- supervisor/core.py
- supervisor/docker/addon.py
Before we make an auto action, I will log this kind of data for the sentry to make the best decision.
> Add some issues and suggestion

- supervisor/docker/addon.py
- This PR fixes or closes issue: fixes #2544 
> Fix path for tmpfs

- supervisor/docker/audio.py
- supervisor/hardware/const.py
- supervisor/hardware/policy.py
> Drop full privileged from audio plugin

- supervisor/discovery/services/vlc_telnet.py
- tests/discovery/test_vlc_telnet.py
> Discovery for vlc telnet

- supervisor/docker/audio.py
- supervisor/hardware/policy.py
> Fix audio cgroup issue

- supervisor/docker/addon.py
> Fix typo in suggestion

- supervisor/addons/utils.py
- supervisor/addons/validate.py
- supervisor/docker/addon.py
- supervisor/hardware/disk.py
- supervisor/hardware/helper.py
- supervisor/hardware/module.py
- supervisor/hardware/policy.py
- supervisor/host/info.py
- tests/hardware/test_disk.py
- tests/hardware/test_helper.py
- tests/hardware/test_policy.py
- This PR fixes or closes issue: fixes #2562
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/812
> Fix handling with full access / blocked devices

- supervisor/docker/audio.py
> Add capabilities for puleaudio

- supervisor/docker/addon.py
> Fix device check if not exists

- .github/ISSUE_TEMPLATE/bug_report.yml
Updates the GitHub Issue form to the new format.
> Update GitHub Issue Form template

- .github/ISSUE_TEMPLATE/bug_report.yml
There were a few changes needed left from #2591 
> Fix some issues with the issue template

- supervisor/docker/__init__.py
- supervisor/resolution/evaluations/lxc.py
- tests/resolution/evaluation/test_evaluate_lxc.py
> Imrove the LXC detection

- supervisor/addons/addon.py
- supervisor/addons/model.py
- supervisor/addons/options.py
- tests/addons/test_options.py
- This PR fixes or closes issue: closes #2600
> Show add-on with bad config in log

- supervisor/docker/addon.py
> Fix small typo in log message

- supervisor/docker/addon.py
- supervisor/docker/audio.py
> Use the cpu_rt support check also for rtprio

- supervisor/homeassistant/websocket.py
> Remove not needed call_soon

- supervisor/hardware/policy.py
> Add kernel docs about the device classes

- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- tests/jobs/test_job_decorator.py
> Add execution limit for jobs

- supervisor/addons/addon.py
- supervisor/homeassistant/websocket.py
> Fix issue with concurrent reads

- supervisor/addons/addon.py
- supervisor/addons/options.py
- supervisor/core.py
- supervisor/exceptions.py
- supervisor/resolution/check.py
- supervisor/resolution/checks/addon_pwned.py
- supervisor/resolution/checks/base.py
- supervisor/resolution/checks/core_security.py
- supervisor/resolution/checks/free_space.py
- supervisor/resolution/const.py
- supervisor/resolution/notify.py
- supervisor/utils/dt.py
- supervisor/utils/pwned.py
- tests/addons/test_options.py
- tests/resolution/check/test_check_addon_pwned.py
> Add check for pwned secrets to resolution center

- supervisor/api/addons.py
Add ATTR_HOMEASSISTANT to the /addons/info API response so it can be used in the frontend.
- This PR is related to issue: home-assistant/addons#1880
> Add home-assistant version to API response

- supervisor/api/__init__.py
- supervisor/api/resolution.py
- supervisor/core.py
- supervisor/resolution/module.py
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/820
> Optimize resolution checks / add endpoint to trigger it manual

- supervisor/addons/options.py
- supervisor/utils/pwned.py
- tests/addons/test_options.py
> Small cleanups with pwned handling

- supervisor/api/__init__.py
- supervisor/api/store.py
- supervisor/api/utils.py
- supervisor/coresys.py
- tests/api/test_store.py
- tests/conftest.py
- tests/fixtures/add-on.json
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/821
> Add /store API

- supervisor/utils/pwned.py
> Fix k-anonymity handling

- supervisor/resolution/module.py
> Log issues/suggestion with info

- supervisor/homeassistant/secrets.py
- supervisor/host/sound.py
- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- supervisor/resolution/checks/addon_pwned.py
- supervisor/updater.py
- supervisor/utils/__init__.py
- tests/jobs/test_job_decorator.py
- tests/resolution/check/test_check_addon_pwned.py
> Add throttle to job execution

- supervisor/api/addons.py
- supervisor/api/security.py
- supervisor/api/store.py
Fixes a bug when updating add-ons.
> Fix add-on updates

- supervisor/api/snapshots.py
- supervisor/snapshots/__init__.py
> Make homeassistant optional in partial snapshot

- supervisor/snapshots/__init__.py
> Allways store docker and repository config

- supervisor/const.py
- supervisor/exceptions.py
- supervisor/homeassistant/secrets.py
- supervisor/store/data.py
- supervisor/store/repository.py
- supervisor/utils/__init__.py
- supervisor/utils/yaml.py
- tests/utils/test_yaml.py
Add support for loading add-on and repository files from YAML in addition to JSON.
> Allow use YAML for addon and repository config

- supervisor/resolution/notify.py
> Fixed typos in resolution notify

- supervisor/addons/addon.py
- supervisor/addons/build.py
- supervisor/addons/data.py
- supervisor/arch.py
- supervisor/auth.py
- supervisor/config.py
- supervisor/discovery/__init__.py
- supervisor/docker/__init__.py
- supervisor/exceptions.py
- supervisor/homeassistant/__init__.py
- supervisor/ingress.py
- supervisor/jobs/__init__.py
- supervisor/plugins/base.py
- supervisor/plugins/dns.py
- supervisor/services/data.py
- supervisor/store/data.py
- supervisor/store/repository.py
- supervisor/updater.py
- supervisor/utils/__init__.py
- supervisor/utils/common.py
- supervisor/utils/json.py
- supervisor/utils/yaml.py
- tests/utils/test_yaml.py
Rename the `JsonConfig` baseclass to `FileConfiguration`, and move common (YAML and JSON utils) to `utils.common`
This allows for _all_ configuration files to be `.yaml` / `.yml` in addition to the exsiting `.json`
> Create FileConfiguration baseclass

- supervisor/hardware/const.py
- supervisor/hardware/policy.py
- tests/hardware/test_policy.py
- This PR fixes or closes issue: fixes #2613  fixes #2574
> Allow dynamic lookup cgroup rules based on Host udev

- supervisor/resolution/checks/addon_pwned.py
- tests/resolution/check/test_check_addon_pwned.py
> Fix add-on is not installed anymore

- supervisor/addons/validate.py
- tests/store/test_translation_load.py
Allow network descriptions in the translation files.
```yaml
network:
80/tcp: Webserver port
```
> Add network description to translation files

- supervisor/store/data.py
- This PR fixes or closes issue: fixes Sentry#2247680912
> Guard for missing repository file

- supervisor/exceptions.py
- supervisor/utils/common.py
> Fix error handling with new config handling

- supervisor/addons/build.py
- supervisor/store/data.py
- supervisor/utils/common.py
- tests/utils/test_common.py
- tests/utils/test_yaml.py
- This PR fixes or closes issue: fixes #2669 
> Fix defaults for builds

- supervisor/exceptions.py
- supervisor/hassos.py
- supervisor/host/network.py
- supervisor/resolution/checks/addon_pwned.py
- supervisor/supervisor.py
- supervisor/updater.py
- supervisor/utils/pwned.py
We have several tasks that use network, we should use the result of those tasks to set the connectivity state.
Changed both connectivity attributes to be setters so we can update the frontend with this information if anything changes.
> Set connectivity state on network tasks

- supervisor/resolution/checks/addon_pwned.py
> Abort on Connection Error

- supervisor/docker/addon.py
- supervisor/docker/audio.py
- supervisor/docker/cli.py
- supervisor/docker/dns.py
- supervisor/docker/homeassistant.py
- supervisor/docker/interface.py
- supervisor/docker/multicast.py
- supervisor/docker/observer.py
We Disabled secomp on Supervisor and add-ons. But it going forgotten to do the same later on plugins.
- This PR fixes or closes issue: fixes #2688
> Disable secomp global

- supervisor/utils/pwned.py
Once it is True, it will be never unpwned, so we can cache this hits. False do not means that they is false on next check.
> Cache hits on pwned

- supervisor/homeassistant/__init__.py
- supervisor/homeassistant/api.py
- supervisor/homeassistant/const.py
- supervisor/homeassistant/core.py
- supervisor/homeassistant/validate.py
- supervisor/validate.py
- This PR fixes or closes issue: fixes #2678
> Fix landingpage on first boot

- supervisor/api/__init__.py
- tests/api/test_resolution.py
> Tweak check API path

- supervisor/resolution/check.py
- supervisor/resolution/checks/addon_pwned.py
- supervisor/resolution/checks/base.py
- supervisor/resolution/checks/core_security.py
- supervisor/resolution/checks/free_space.py
- supervisor/resolution/validate.py
- tests/resolution/check/test_check.py
> Dynamically load resolution checks

- supervisor/api/__init__.py
- supervisor/api/resolution.py
- tests/api/test_resolution.py
> Resolution: API call for run check manual

- .github/workflows/builder.yml
> CoreNotary Image singing

- supervisor/addons/__init__.py
- supervisor/exceptions.py
- supervisor/hassos.py
- supervisor/homeassistant/core.py
- supervisor/snapshots/__init__.py
> New error handling

- .github/workflows/builder.yml
> Use github context object for workspace

- .github/workflows/builder.yml
- Dockerfile
> Fix access to needs.init.outputs.publish

- supervisor/hassos.py
- This PR is related to issue: https://github.com/home-assistant/operating-system/pull/1213
> Detect haos as well

- supervisor/coresys.py
- supervisor/exceptions.py
- supervisor/updater.py
- supervisor/utils/codenotary.py
- supervisor/utils/pwned.py
- tests/utils/test_codenotary.py
Currently, we only warn the user. It's like a test before we roll it out.
> Add CodeNotary / for version file

- supervisor/exceptions.py
> Fix sentry logs with None

- Dockerfile
> remove git from build-dependencies

- supervisor/utils/codenotary.py
> fix signerID command

- .github/PULL_REQUEST_TEMPLATE.md
> Add link to cli on pull request template

- .github/workflows/builder.yml
- build.json
- supervisor/api/addons.py
- supervisor/api/supervisor.py
- supervisor/config.py
- supervisor/const.py
- supervisor/coresys.py
- supervisor/exceptions.py
- supervisor/resolution/checks/addon_pwned.py
- supervisor/utils/codenotary.py
- supervisor/utils/pwned.py
- supervisor/validate.py
- tests/api/test_supervisor.py
- tests/resolution/check/test_check_addon_pwned.py
- tests/test_updater.py
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/860
- Link to cli pull request: https://github.com/home-assistant/cli/pull/285
> Force / Enforce security if service is not available

- supervisor/const.py
- tests/docker/test_addon.py
I feel incredibly dumb right now. I had a typo in the submission for [PR 2722](https://github.com/home-assistant/supervisor/pull/2722). I put `/var/logs/journal` as the folder for the journal when it should've been `/var/log/journal`. I realized immediately when I tried the beta just now 🤦
> Fix typo in journald location

- supervisor/api/os.py
- supervisor/core.py
- supervisor/exceptions.py
- supervisor/hassos.py
- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- tests/jobs/test_job_decorator.py
> Fix HAOS sync output

- supervisor/config.py
- supervisor/docker/interface.py
- supervisor/docker/supervisor.py
- supervisor/supervisor.py
- supervisor/validate.py
> Supervisor image handler

- supervisor/homeassistant/secrets.py
- supervisor/utils/json.py
- supervisor/utils/yaml.py
> Make secrets more robust again

- supervisor/updater.py
> Updater check response code

- supervisor/exceptions.py
- supervisor/supervisor.py
- supervisor/updater.py
> Fix request status check on AppArmor profile fetch

- supervisor/docker/cli.py
> Enable content-trust on CLI docker

- supervisor/docker/audio.py
- supervisor/docker/multicast.py
> Add NET_ADMIN to multicast for pimd

- supervisor/docker/audio.py
- supervisor/docker/dns.py
- supervisor/docker/multicast.py
- supervisor/docker/observer.py
> Enable content-trust for all plugins

- supervisor/docker/__init__.py
> Fix issues with special compiled binary with own version schema

- supervisor/resolution/const.py
- supervisor/resolution/evaluations/apparmor.py
- tests/resolution/evaluation/test_evaluate_apparmor.py
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/17303
> Evaluate AppArmor support

- supervisor/exceptions.py
- supervisor/jobs/decorator.py
> Improve message handling of job condition

- supervisor/store/repository.py
- tests/store/test_custom_repository.py
- This PR fixes or closes issue: fixes home-assistant/developers.home-assistant#878
> Break loop when we have the correct file

- supervisor/homeassistant/__init__.py
- supervisor/updater.py
Change `need_update` for core to use `<` instead of  `!=`when comparing.
Signal frontend to update supervisor, core, and os after updater has run 
> Signal frontend when updater runs

- supervisor/jobs/decorator.py
> Remove not needed warning before raise on JobDecorator

- build.json
> Add image source to build.json

- supervisor/bootstrap.py
- supervisor/resolution/const.py
- supervisor/resolution/evaluations/source_mods.py
- supervisor/resolution/fixup.py
- supervisor/resolution/module.py
- supervisor/utils/codenotary.py
- tests/resolution/evaluation/test_evaluate_source_mods.py
This is not to provent code modification, it's just to show that it lost the supported state and people are on his own if they run into issue which not should be sended to sentry. This just prevent reports from modified installation.
People can run what ever they want, it should just not show as supported.
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/17312
> System unsupported source modification

- supervisor/coresys.py
This will be also sent with the critical message later. Just this error has not so much content as the later message, so let's ditch it.
> Remove double sentry event for untrusted

- supervisor/homeassistant/websocket.py
> Guard against multiple client creations

- .github/workflows/builder.yml
> Extend supervisor CI checks

- rootfs/etc/services.d/supervisor/run
Replace jemalloc with mimalloc
> Using mimalloc

- .github/workflows/builder.yml
> Using exists container on publish

- build.json
https://github.com/opencontainers/image-spec/blob/master/annotations.md
> Add more image-spec annotations

- supervisor/utils/__init__.py
- supervisor/utils/codenotary.py
- supervisor/utils/gdbus.py
> Clean env on subprocess

- .github/ISSUE_TEMPLATE/bug_report.yml
Fix/Workaround for an issue with the GitHub issue forms, where the title is not seen as a string.
Additionally, it incorporates breaking changes that are being deployed by GitHub today.
> Update GitHub issue form

- supervisor/utils/__init__.py
> Clean env on remove-folder

- supervisor/api/supervisor.py
This option is useless outside of dev and just breaks the installation. This option never did what people mean for what it was.
Now the option only works for development.
> Ignore version on supervisor update

- .github/ISSUE_TEMPLATE/bug_report.yml
Small tweak to the issue form, that now supports a renderer (and adjusts the input box for it).
> Update GitHub issue form with render field

- .pre-commit-config.yaml
> Update black 21.4b1 on pre-commit

- rootfs/etc/services.d/supervisor/run
Need: https://github.com/home-assistant/docker-base/actions/runs/792468660
> Switch back to jemalloc

- .devcontainer/Dockerfile
- scripts/common.sh
> Handle iptables better WSL2

- requirements.txt
https://github.com/ludeeus/awesomeversion/releases/tag/21.5.0
> Bump awesomeversion to 21.5.0

- supervisor/addons/addon.py
- supervisor/addons/model.py
- supervisor/addons/options.py
- supervisor/api/__init__.py
- supervisor/api/addons.py
- supervisor/api/middleware_security.py
- supervisor/api/security.py
- supervisor/api/supervisor.py
- supervisor/bootstrap.py
- supervisor/config.py
- supervisor/const.py
- supervisor/coresys.py
- supervisor/docker/interface.py
- supervisor/resolution/checks/addon_pwned.py
- supervisor/resolution/evaluations/content_trust.py
- supervisor/resolution/evaluations/source_mods.py
- supervisor/security.py
- supervisor/supervisor.py
- supervisor/updater.py
- supervisor/utils/pwned.py
- supervisor/validate.py
- tests/api/test_middleware_security.py
- tests/api/test_security.py
- tests/api/test_supervisor.py
- tests/resolution/check/test_check_addon_pwned.py
- tests/resolution/evaluation/test_evaluate_content_trust.py
- tests/resolution/evaluation/test_evaluate_source_mods.py
- tests/test_updater.py
Validate secrets on the option validate UI API call and add a flag `pwned` to the return. Can be used to show a warning on UI that some of the secrets are not secure.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/917
> Validate secrets on options/validate UI check

- supervisor/core.py
- supervisor/jobs/decorator.py
- supervisor/plugins/__init__.py
- supervisor/plugins/dns.py
- supervisor/supervisor.py
Enable connectivity check on startup. We decided to not release the job manager to begin with this for getting more test data.
> Enable connectivity on startup

- supervisor/addons/addon.py
- supervisor/api/proxy.py
- supervisor/core.py
- supervisor/coresys.py
- supervisor/homeassistant/api.py
- supervisor/homeassistant/websocket.py
- tests/conftest.py
> Cleanup websession with new aiohttp ssl

- .github/workflows/builder.yml
> Fix wheels host

- .devcontainer/Dockerfile
- .github/workflows/builder.yml
- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- build.json
- pylintrc
- requirements_tests.txt
- supervisor/bootstrap.py
> Python 3.9

- .github/workflows/builder.yml
> Update builder builder-2021.05.0

- supervisor/addons/addon.py
When using a Watchdog URI formatted as `tcp://`, the port is a string, which:
```py
result = sock.connect_ex((str(address), port))
```
Doesn't like. This PR ensures the regex port match result is cast to an integer.
- This PR fixes or closes issue: fixes #2902
> Fix Watchdog port being used as string

- supervisor/addons/validate.py
- supervisor/data/arch.json
- supervisor/hassos.py
- tests/conftest.py
- tests/test_hassos.py
Since OS renamed from intel-nuc to generic-x86-64, the new image must be fetched by the supervisor. This change makes sure that when updating on a board named `intel-nuc` to OS releases with major version 6 or higher, the board name `generic-x86-64` is used instead.
- This PR is related to issue: https://github.com/home-assistant/operating-system/issues/1048
> Update OS on intel-nuc to generic-x86-64 image

- supervisor/docker/homeassistant.py
I mixup my work for container installation with the images for the supervisor. This is the correct version that sign all supervisor core images. For container installation, we backdate that a bit more.
> Adjust content-trust core version

- supervisor/hassos.py
Minor spelling fixes to log messages
> Minor spelling fixes

- supervisor/homeassistant/api.py
> Lmit ensure_access_token

- supervisor/host/sound.py
- This PR fixes or closes issue: fixes #2859
> Fix setting audio profile

- requirements.txt
> Bump awesomeversion to 21.6.0

- supervisor/api/store.py
> Add-on: Block update itself

- supervisor/resolution/checks/addon_pwned.py
- tests/resolution/check/test_check_addon_pwned.py
- This PR fixes or closes issue: fixes #2951
> Fix addon_pwned enabled setter

- supervisor/misc/tasks.py
Fix API watchdog was not triggered because the container was running. A copy past issue from the container watchdog code
> Fix API watchdog never trigger

- supervisor/addons/build.py
- supervisor/homeassistant/module.py
- supervisor/plugins/base.py
- tests/addons/test_config.py
- tests/conftest.py
- tests/fixtures/basic-build-config.json
> Using ghcr.io/home-assistant + fallback

- supervisor/store/__init__.py
Fixes `[supervisor.store] https://github.com/home-assistant/addons is not a valid add-on repository`.
With this fixed, the user can now also add back `https://github.com/home-assistant/addons` as a valid repository in the supervisor UI / CLI
> When validating add-ons transform core-addons url

- supervisor/misc/tasks.py
Fix: https://sentry.io/organizations/home-assistant-io/issues/2457789112/events/0130534841a146a59987ff5f49afca7e
> Run API watchdog only if core is running

- supervisor/updater.py
- tests/test_updater.py
Need: https://github.com/home-assistant/version/pull/154
> Using images data from version file

- supervisor/hassos.py
- tests/test_hassos.py
Allow to customize URL depending on OS name. This allows to generate the correct URL to downgrade to Operating System versions before 6.
This is an alternative to https://github.com/home-assistant/supervisor/pull/2964
Note: This requires the URL in version json's to be extended with `{os_name}`. Supervisor updates need to be sufficient deployed before this step can occur.
- This PR fixes or closes issue: issue mentioned in https://github.com/home-assistant/operating-system/issues/1336#issuecomment-864088541 …
> Allow downgrade to "hassos" from "haos"

- supervisor/addons/addon.py
- supervisor/addons/const.py
- supervisor/addons/model.py
- supervisor/addons/validate.py
Followup of the #2941 - Fix also issue if the container is not running.
- This PR fixes or closes issue: fixes #2968
> Support HOT/COLD snapshots for Add-ons

- supervisor/bootstrap.py
- supervisor/coresys.py
- tests/conftest.py
- tests/test_coresys.py
> Logging in local timezone

- supervisor/hassos.py
Once {os_name} is part of the update URL we also need to set the OS name
explicitly for upgrades: A user might use a new Supervisor version on a
OS release 5 device. The device will still use "hassos" as OS name.
Before introducing {os_name}, the new OS name was part of the URL. Now
when {os_name} is used, we need to adjust the name for upgrade as well.
- This PR is related to issue: https://github.com/home-assistant/supervisor/pull/2970
> Allow upgrade when using {os_name} in URL

- supervisor/hassos.py
> Add running job condition to OS update

- requirements.txt
`Brotli` is not used by `aiohttp` until 3.8.x or 4.0
This PR adds back `brotlipy` instead of `Brotli`.
- This PR fixes or closes issue: fixes #2918
> Use brotlipy instead of Brotli

- supervisor/api/ingress.py
Stream requests to add-ons behind ingress.
Related core PR https://github.com/home-assistant/core/pull/52184
- This PR fixes or closes issue: closes #2950
> Stream requests to ingress

- tests/test_hassos.py
> Fix failing test

- supervisor/api/ingress.py
Only use `.content` for POST request, for all others, use `.read()` as before.
- This PR fixes or closes issue: fixes home-assistant/addons#2095
> Only use .content for POST

- .github/workflows/builder.yml
- build.json
> Alpine 3.14

- supervisor/plugins/base.py
- supervisor/resolution/checks/base.py
- supervisor/resolution/evaluations/base.py
- supervisor/resolution/fixups/base.py
`abstractproperty` was deprecated in Python 3.3
https://docs.python.org/3/library/abc.html#abc.abstractproperty
> Replace abstractproperty with abstractmethod

- tests/conftest.py
Example:
https://github.com/home-assistant/supervisor/runs/3281785138#step:10:83
> Fix flaky tests when CI did not have access to /run/supervisor

- .github/workflows/ci.yaml
We migrated our org to use the github but this one was not on my radar
> Fix vcn install on CI

- supervisor/docker/audio.py
Helps: https://github.com/home-assistant/plugin-audio/pull/84
> Give audio plugin machine data for mixer evaluation

- supervisor/resolution/evaluations/operating_system.py
Adds `Debian GNU/Linux 11 (bullseye)` to the list of supported operating systems.
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/19031
- Other: https://github.com/home-assistant/supervisor/pull/3066
> Add Debian 11: Bulleyes to support systems check

- supervisor/store/data.py
- tests/store/test_reading_addons.py
> Ignore all files and directories that starts with .

- supervisor/store/data.py
- tests/store/test_reading_addons.py
Followup to <https://github.com/home-assistant/supervisor/pull/3094#issuecomment-910165194>
> Ignore rootfs

- supervisor/homeassistant/module.py
> Support USB discovery

- .github/workflows/builder.yml
Currently the container logs are hidden on cancel/failure.
This adds a conditional step to always get supervisor logs if this job fails or is canceled.
It also changes the timeout from 360 (default) to 60 minutes
> Print supervisor container logs on failure

- supervisor/homeassistant/api.py
- supervisor/homeassistant/core.py
> Detect if frontend is not loaded

- .github/workflows/builder.yml
> Using git token + pull image from ghcr.io for tests

- supervisor/host/const.py
- supervisor/host/manager.py
- supervisor/jobs/decorator.py
- supervisor/resolution/const.py
- supervisor/resolution/evaluations/os_agent.py
- tests/resolution/evaluation/test_evaluate_os_agent.py
> Add os-agent to evaluations for supported systems

- requirements.txt
Reverts home-assistant/supervisor#3141
> Revert "Bump voluptuous from 0.12.1 to 0.12.2"

- .github/workflows/builder.yml
- requirements.txt
- supervisor/addons/validate.py
- supervisor/api/addons.py
- supervisor/api/audio.py
- supervisor/api/auth.py
- supervisor/api/backups.py
- supervisor/api/docker.py
- supervisor/api/homeassistant.py
- supervisor/api/host.py
- supervisor/backups/validate.py
- supervisor/discovery/services/adguard.py
- supervisor/discovery/services/almond.py
- supervisor/discovery/services/deconz.py
- supervisor/discovery/services/homematic.py
- supervisor/discovery/services/motioneye.py
- supervisor/discovery/services/mqtt.py
- supervisor/discovery/services/unifi.py
- supervisor/discovery/validate.py
- supervisor/homeassistant/validate.py
- supervisor/services/modules/mqtt.py
- supervisor/services/modules/mysql.py
- supervisor/store/validate.py
- supervisor/validate.py
> Bump voluptuous from 0.12.1 to 0.12.2

- supervisor/homeassistant/core.py
https://sentry.io/organizations/home-assistant-io/issues/2669352857/?project=5370612&query=is%3Aunresolved+release%3A2021.09.3&statsPeriod=14d
> Fix UnboundLocalError

- .github/workflows/ci.yaml
> Fix typo in vcn_version

- .pre-commit-config.yaml
- supervisor/utils/json.py
> Fix pyupgrade precommit

- supervisor/misc/filter.py
- supervisor/plugins/manager.py
- supervisor/resolution/checks/plugin_trust.py
> Add all_plugins to cleanup code

- supervisor/utils/codenotary.py
> Return early in validate

- supervisor/api/middleware/security.py
> Fix observer security filter

- supervisor/auth.py
I replaced the exact construct mentioned in the issue.
In this file however, there are some similar constructs (see line 133 onwards or the method from line 91 onwards). Those are more complex, how should they be treated?
- This PR fixes or closes issue: -
> Use new format for logging exceptions - auth.py

- supervisor/addons/addon.py
Implemented changes requested in #3156 
- This PR fixes or closes issue: -
- This PR is related to issue: #3156
> Use new format for logging exceptions - addons/addon.py

- supervisor/addons/__init__.py
Implemented changes requested in #3156
- This PR fixes or closes issue: -
> Use new format for logging exceptions - addons/init.py

- supervisor/host/sound.py
change exception logging to the new format in host/sound.py
> Use new format for logging exceptions - host/sound.py

- supervisor/services/modules/mysql.py
- This PR fixes or closes issue: 
- This PR is related to issue: #3156
> Use new format for logging exceptions - services/modules/mysql.py

- supervisor/homeassistant/api.py
Implemented changes requested in #3156
- This PR fixes or closes issue: -
> Use new format for logging exception - homeassistent/api.py

- supervisor/services/modules/mqtt.py
> Use new format for logging exceptions - services/modules/mqtt.py

- supervisor/api/proxy.py
- This PR fixes or closes issue:
> Use new format for logging exceptions - api/proxy.py

- supervisor/plugins/cli.py
- This PR is related to issue:#3156
> Use new format for logging exceptions - plugins/cli.py

- supervisor/utils/apparmor.py
> Use new format for logging exceptions - utils/apparmor.py

- supervisor/docker/__init__.py
> Use new format for logging exceptions - docker/init.py

- supervisor/plugins/dns.py
- This PR is related to issue:#3156
> Use new format for logging exceptions - plugins/dns.py

- supervisor/dbus/network/__init__.py
> Use new format for logging exceptions - dbus/network/__init__.py

- supervisor/host/network.py
> Use new format for logging exceptions - host/network.py

- supervisor/host/apparmor.py
> Use new format for logging exceptions - host/apparmor.py

- supervisor/api/const.py
- supervisor/api/os.py
- tests/api/test_os.py
This is what's used in the [docs](https://developers.home-assistant.io/docs/api/supervisor/endpoints/#os) and the [frontend](https://github.com/home-assistant/frontend/blob/dev/src/data/hassio/host.ts#L28)
> Rename disk_data to data_disk

- supervisor/docker/interface.py
New format for logging exceptions in "docker/interface.py"
Please add hacktoberfest-accepted label to this PR to count towards hacktoberfest contribution.
- This PR is related to issue: [Use new format for logging exceptions #3156](https://github.com/home-assistant/supervisor/issues/3156)
> Use new format for logging exceptions - docker/interface.py

- supervisor/host/info.py
> Use new format for logging exceptions - host/info.py

- supervisor/resolution/module.py
> Use new format for logging exceptions - resolution/module.py

- supervisor/homeassistant/core.py
> Fix typo in HA startup message

- supervisor/plugins/observer.py
> Using rolling token on observer

- supervisor/utils/whoami.py
- This PR fixes or closes issue: fixes #3289 
> Handle whoami SSL error less strict

- supervisor/addons/addon.py
Using the new style as we use also after the update. That code was stale after the last update on that mechanic.
> Fix: using deep merge for test update schema

- supervisor/api/addons.py
Make sure, secrets are almost up to date like we do on generating the options.json and work well until today.
> Reload secrets on options config

- requirements.txt
Replaces #3303
Replaces #3298
Reverts #2977
> Bump aiohttp and friends

- requirements_tests.txt
- tests/addons/test_options.py
> Bump pylint from 2.11.1 to 2.12.1

- .github/workflows/builder.yml
> Fix path name for build file

- requirements.txt
- supervisor/utils/yaml.py
Upgrades ruamel.yaml 0.17.17
Changelog: <https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/CHANGES>
Added load type to `safe`, as we don't use the default `rt` functionality.
This PR prevents issues reported like #3362 that merely trigger on an outdated version, even though we are not affected by this.
- This PR fixes or closes issue: closes #3362
> Update ruamel.yaml to 0.17.17

- supervisor/store/__init__.py
- tests/fixtures/add-on.json
- tests/store/test_custom_repository.py
A follow-up to this will be to disable the UI buttons, but by doing it here as well we effectively stop them from being removed from CLI/UI and other tasks
> Don't remove add-on repos if add-on is installed

- supervisor/updater.py
Explicitly check if the board reported by HAOS is in the version file.
Also make sure that we still set the download URL so it will still be
possible to update to old versions in case needed.
Noted here: https://github.com/home-assistant/version/pull/190#pullrequestreview-831964935
> Log if board reported by HAOS isn't in version file

- supervisor/__main__.py
- supervisor/store/__init__.py
- supervisor/store/data.py
Enable asyncio debug in developer mode.
One issue which showed up with developer mode was supervisor.store.data.StoreData update. Move it into an executor to avoid long running IO in async mode.
> Enable asyncio debug in developer mode

- .github/workflows/ci.yaml
Fix/Change cache restore policy on the CI, rebuilding the venv fully when a dependency changes.
> Change CI cache restore policy

- supervisor/backups/backup.py
Currently log files are excluded from the backup. Core uses a time or
startup based log rotation mechanism, both append a dot and an
additional; string (`.1`, `.{timestamp}`). There is also a fault
mechanism which creates a log file with the ending `.log.fault`. Exclude
all cases from the backup.
> Exclude old log files from backup

- tests/discovery/test_almond.py
Fix copy-paste error in pydoc for test_almond.py
> Fix copy-paste error in pydoc for test_almond.py

- tests/discovery/test_adguard.py
- tests/discovery/test_almond.py
- tests/discovery/test_deconz.py
- tests/discovery/test_homematic.py
- tests/discovery/test_motioneye.py
- tests/discovery/test_mqtt.py
- tests/discovery/test_ozw.py
- tests/discovery/test_unifi.py
- tests/discovery/test_zwave_js.py
Fix additional copy/paste errors found in tests.
> Fix copy/paste issues in tests

- supervisor/discovery/services/rtsp_to_webrtc.py
- tests/discovery/test_rtsp_to_webrtc.py
Add Add-on discovery schema for RTSPtoWebRTC, a complement to config flow discovery support added in https://github.com/home-assistant/core/pull/63211
This has not been end-to-end tested yet.
> Add Add-on discovery schema for RTSPtoWebRTC

- .devcontainer/devcontainer.json
- supervisor/homeassistant/websocket.py
When the connection closes (e.g. due to Core restart), there might still
be WebSocket calls pending (waiting for a result). Currently, those
calls hang forever waiting for a result. Make sure those futures throw
an exception so the caller knows that the call actually failed.
> Release all pending WebSocket calls on connection close

- supervisor/docker/addon.py
Make sure to not reference version attribute from the DockerAddon
instance since it is not yet populated in case this instance hadn't
installed that Add-on previously.
Use the higher level Images.load() API which returns a list of images
instead of loading with the lower level API and then search for the
image we just imported.
- This PR fixes or closes issue: fixes #3402
> Fix local Add-on restore on blank instance

- supervisor/api/backups.py
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/1187
> Add backup size to list API

- supervisor/docker/addon.py
> Fixing IO on the loop with docker HW events

- supervisor/validate.py
Add ESPHome to the default repositories
> ESPHome default repo for new installations

- rootfs/etc/services.d/watchdog/run
I was looking through the supervisor repo to find more info on the `/run/supervisor` file and found what looks like a typo at the end of the watchdog run script
> Fix bashio-typo in watchdog service

- .github/workflows/builder.yml
Fix CI with adding hash://....
> Add suffix hash on CAS CI

- .github/workflows/builder.yml
> Fix source-mod detection calculation

- tests/resolution/evaluation/test_evaluate_source_mods.py
Source mods test was corrected to start from `supervisor` folder within repo and not include tests. The patch here was still starting from the workspace directory since that's what it used to do
> Hash correct folder in source_mods tests

- supervisor/homeassistant/module.py
Ignore databases which the recorder deemed corrupt and moved away
from backup (see homeassistant/components/recorder/util.py function
move_away_broken_database()).
> Ignore corrupted databases in backup

- supervisor/docker/addon.py
- supervisor/docker/const.py
- supervisor/docker/dns.py
Add dbus support to `plugin-dns` to support of https://github.com/home-assistant/plugin-dns/pull/73
> Add dbus support to plugin-dns

- rootfs/root/.cas/config.json
Merged after: https://github.com/home-assistant/version/pull/207/files
> Add CAS configs to image

- supervisor/misc/tasks.py
> Create a backup on add-on auto update

- supervisor/backups/backup.py
- supervisor/backups/manager.py
- supervisor/backups/validate.py
- tests/backups/test_validate.py
> Partial backup v1 bugfix

- supervisor/core.py
> Disable diagnostic on dev/unsupported

- supervisor/utils/codenotary.py
> Test CI codenotary timeout of 15sec for DNS plugin issues

- .github/workflows/builder.yml
> Fix CI warning "[: =~: binary operator expected"

- supervisor/addons/__init__.py
- supervisor/addons/model.py
- supervisor/const.py
- supervisor/core.py
- supervisor/docker/addon.py
- supervisor/docker/interface.py
- tests/docker/test_interface.py
Populating platform arg when doing an image pull by mapping from the determined cpu architecture.
> Passing platform arg on image pull

- supervisor/docker/interface.py
Arch to plaform map should use the new enum
> Use enum in arch to platform map

- supervisor/utils/codenotary.py
- tests/utils/test_codenotary.py
Fix for error handling issue with cas identified by sentry and tests around error behavior.
> Error response handling & tests

- supervisor/api/backups.py
- supervisor/backups/manager.py
- supervisor/backups/validate.py
- This PR fixes or closes issue: fixes #3477
> Fix partial backup with Core

- supervisor/utils/whoami.py
https://github.com/home-assistant/services.home-assistant.io/releases/tag/2.0.0
> Update whoami URL

- .github/workflows/builder.yml
- .github/workflows/ci.yaml
- .github/workflows/lock.yml
- .github/workflows/release-drafter.yml
- .github/workflows/stale.yml
Dependabot set a lot of our actions to auto-update within the latest major version. I looked up the latest version of each action we use and set the version to the full semantic version to prevent unexpected CI issues.
> Use full version in actions to prevent auto-updates

- .github/release-drafter.yml
This was added in release-drafter 5.19.0, if there are more than 3 dependencies it will now use the summary tag to collapse them
https://github.com/release-drafter/release-drafter#categorize-pull-requests
> Add collapse-after for dependencies

- supervisor/resolution/checks/core_trust.py
- supervisor/resolution/checks/plugin_trust.py
- supervisor/utils/codenotary.py
- Revert timeout for keep things fast as before with old backend
- Disable plugin check and core check on startup and keep it after the system is running
- Abort trust check if a backend error is happening
> Reduce floot on startup

- .github/workflows/builder.yml
- supervisor/utils/codenotary.py
- tests/test_security.py
- tests/utils/test_codenotary.py
Take down the load from the nodes to rebuild the index
> Disable CAS until it work

- supervisor/addons/model.py
Partial revert of <https://github.com/home-assistant/supervisor/pull/3465/files>
Fixes #3497
> Get arch from config and not data when generating image

- supervisor/backups/backup.py
> Remove name argument to _restore

- .github/workflows/builder.yml
> Add backup and restore to CI

- supervisor/backups/validate.py
- tests/backups/test_validate.py
- This PR fixes or closes issue: fixes #3514
> Fix issues with old protection flag

- .github/workflows/builder.yml
- supervisor/resolution/checks/core_trust.py
- supervisor/resolution/checks/plugin_trust.py
- supervisor/security.py
- supervisor/utils/codenotary.py
- tests/test_security.py
- tests/utils/test_codenotary.py
This partial reverts commit 435241bccf3f3c678161b50cfefd4b036f1daba9.
Using CAS for add-ons first
> Enable CAS for Add-ons

- supervisor/host/info.py
- tests/conftest.py
- tests/host/test_manager.py
Update systemd-resolved information with other host info.
> Update resolved information with host info

- supervisor/dbus/network/setting/__init__.py
- supervisor/utils/dbus.py
- tests/conftest.py
- tests/dbus/network/setting/test_init.py
- tests/fixtures/org_freedesktop_NetworkManager_Settings_1-GetSettings.json
Fixes #3566 by merging values for supported settings supervisor understands with unsupported ones that supervisor does not in order to preserve advanced customization by users. 
As discussed in the meeting this doesn't currently add an unsupported message for unrecognized options because there is [simply too many of them](https://developer-old.gnome.org/NetworkManager/stable/ch01.html). And a number have default values that are good we just don't understand it because we don't support changing it to anything else.
I'm open to suggestions on this front if there are any ideas. Or we just update the documentation to make it very clear that the only supported use case for updating network settings outside of the Supervisor API is to set up wifi on a wifi-only device (ex. pi zero w 2).
- This …
> Merge updates with existing network settings

- supervisor/resolution/checks/core_trust.py
- supervisor/resolution/checks/plugin_trust.py
- supervisor/security.py
- tests/test_security.py
Full enable the CAS service also for our internal services. As we fixed the timeout issue, it will not break the startup or updates if the service fails.
> Enable CAS

- rootfs/etc/services.d/supervisor/run
Optimize jemalloc but unlike core, we keep the memory page faster cleanup as we do not have such state machine as core has.
> Tuning Jemalloc

- supervisor/security/module.py
ONCE is fine, we cache anyway also in all other modules, so the call is not that expensive to throttle it for manual usage
> Using job limit ONCE for integrity

- supervisor/updater.py
- tests/test_updater.py
Revert https://github.com/home-assistant/supervisor/commit/0548afdb61219efad651e88d93b4a9790eac2a79. Was a mistake but to be honest did not expect it would let me do that.
> Revert "OS latest version set from upgrade path"

- requirements.txt
https://github.com/ludeeus/awesomeversion/releases/tag/22.5.1
> Bump awesomeversion to 22.5.1

- requirements.txt
> Fix update issues

- .devcontainer/devcontainer.json
Use volume as Docker storage location. This allows to use `overlay2` as file system driver and improves performance significantly.
> Use volume as Docker storage location

- supervisor/updater.py
- tests/test_updater.py
Set latest version of OS according to the update path for current major version if one is provided in the version info. Note that this PR requires https://github.com/home-assistant/version/pull/227 first.
- This PR fixes or closes issue: fixes #3629
> OS latest version set from upgrade path

- supervisor/store/git.py
When doing a git pull on addon store if origin refspec has gone missing the library raises `AssertionError` which we're currently not catching (see [here](https://github.com/gitpython-developers/GitPython/blob/3.1.27/git/remote.py#L835)). Catch so we suggest reset.
- This PR fixes or closes issue: fixes #3648
> Catch assertion error on git pull

- supervisor/api/store.py
- supervisor/api/supervisor.py
- supervisor/backups/backup.py
- supervisor/backups/validate.py
- supervisor/config.py
- supervisor/misc/filter.py
- supervisor/resolution/fixups/store_execute_remove.py
- supervisor/store/__init__.py
- supervisor/store/const.py
- supervisor/store/git.py
- supervisor/store/repository.py
- supervisor/store/validate.py
- supervisor/validate.py
- tests/api/test_store.py
- tests/api/test_supervisor.py
- tests/conftest.py
- tests/fixtures/addons/git/5c53de3b/repository.yaml
- tests/fixtures/addons/git/a0d7b954/repository.yaml
- tests/resolution/fixup/test_store_execute_remove.py
- tests/store/test_custom_repository.py
- tests/store/test_store_manager.py
- tests/store/test_validate.py
Move repository URLs out of settings file for core config and to settings file for store. Will do a one-time migration to move the URLs from supervisor to store config for existing users to handle backwards compatibility. APIs unchanged for now although `repositories` in `supervisor/options` should be deprecated in the near future in favor of `POST store/repositories` and `DELETE store/repositories/{slug}`.
Additionally I made the community and esphome addon repositories true built-in repositories. Supervisor ensures they are always there and cannot be removed. There's a lot of issues about these being removed because users assume they are built-in, seems wise to make it official. …
> Move repository urls to store settings file

- supervisor/store/__init__.py
- tests/api/test_store.py
- tests/api/test_supervisor.py
- tests/store/test_custom_repository.py
Use `repository.source` not `repository.url` in code. In real repos `repository.url` is the documentation URL.
> Use source instead of URL for repos

- supervisor/store/__init__.py
On startup we runt through `add_repository` logic for all saved repos to force them to load. But we don't want to re-add those to the data as that breaks.
> Don't add dupe repos to data on startup

- supervisor/bootstrap.py
- supervisor/config.py
- supervisor/store/__init__.py
- tests/conftest.py
- tests/store/test_store_manager.py
Move migration of addon repos from core to store config from `StoreManager.load` to `bootstrap.migrate_system_env`
> Move addon repo migration to bootstrap

- supervisor/docker/__init__.py
- supervisor/resolution/evaluations/docker_configuration.py
- tests/resolution/evaluation/test_evaluate_docker_configuration.py
Following the ADR, make sure it's on the correct group to reduce creating issues with the hardware layer.
https://github.com/home-assistant/home-assistant.io/pull/23170
> Verify the cgroup supported level

- supervisor/api/addons.py
- This PR fixes or closes issue: fixes home-assistant/frontend#12993
> Add back missing state to addons list API

- supervisor/supervisor.py
> Use checkonline instead of version for online check

- supervisor/store/addon.py
> AddonStore is_installed needs to check installed

- .github/workflows/builder.yml
This unblocks the CI by setting a pin on the wheels action (currently all CI builds fail)
Once the current beta is shipped to stable, we can look into upgrading to the latest base image (Python 3.10) and upgrading to the latest wheels builder at that point.
For now, this unblocks CI.
> Fix wheels build by pinning wheels action

- .pre-commit-config.yaml
The requirements_test.txt and pre-commit configuration file are out of sync.
This updates the pre-commit to the latest version that matches the requirements_test.txt files.
> Bump black in pre-commit

- supervisor/validate.py
> Branch names can contain periods

- supervisor/addons/addon.py
> Output backup log on error

- requirements.txt
See https://github.com/home-assistant/core/pull/74758 . Moving to our fork as well since the current dependency no longer exists.
> Bump atomicwrites

- supervisor/docker/stats.py
Docker versions newer than 19.03 calculate memory usage sligthly
different compared to previous versions. It seems the field
"total_inactive_file" was not available in 19.03, so it can be used
as indicator.
See: https://docs.docker.com/engine/reference/commandline/stats/#description
Essentially, this includes also tmpfs usage in memory usage. Some
more detailed discussions can be found here:
https://github.com/moby/moby/issues/40727 …
> Fix add-on memory calculation

- supervisor/api/__init__.py
Some ingress addons require very long URLs. Since all access to ingress addons goes through supervisor's API they are subject to whatever we set as for `max_line_size` and `max_field_size` in [aiohttp](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/http_parser.py#L127-L128). This can create issues like #3737 . Increasing it should support more addons.
- This PR fixes or closes issue: fixes #3737 
> Increase max line size for ingress addons

- supervisor/plugins/audio.py
- tests/plugins/test_audio.py
Let audio know if supervisor debug logging is on so it can set log level accordingly.
- This PR is related to issue: https://github.com/home-assistant/plugin-audio/issues/57 , https://github.com/home-assistant/plugin-audio/issues/56
> Pass supervisor debug value to audio

- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- supervisor/misc/tasks.py
- tests/jobs/test_job_decorator.py
We should always update supervisor before auto-updating anything else. This prevents issues where something banking on a new feature of supervisor is accidently updated first. 
> Update supervisor before auto-updating others

- supervisor/docker/monitor.py
Not all containers have names, particular build layers. Need to protect against that.
> Fix keyerror on unnamed containers

- supervisor/addons/addon.py
- tests/addons/test_addon.py
Addon rebuild tries to rebuild the image. Very different from core and plugin rebuild which rebuilds the container from the image. Watchdog should only be restarting and rebuilding containers, not images.
> Watchdog shouldn't rebuild addons

- supervisor/docker/interface.py
Docker attach runs in the executor, can't call `fire_event` directly as it uses `create_task`. Use `call_soon_threadsafe`.
- This PR fixes or closes issue: fixes #3761 
> Attach is in executor, use `call_soon_threadsafe`

- supervisor/resolution/const.py
- supervisor/resolution/evaluations/cgroup.py
- supervisor/resolution/evaluations/docker_configuration.py
- tests/resolution/evaluation/test_evaluate_cgroup.py
- tests/resolution/evaluation/test_evaluate_docker_configuration.py
> Mark CGroup V2 supported on Home Assistant OS

- supervisor/addons/addon.py
- supervisor/addons/const.py
- supervisor/exceptions.py
- supervisor/homeassistant/const.py
- supervisor/homeassistant/core.py
- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- supervisor/plugins/audio.py
- supervisor/plugins/base.py
- supervisor/plugins/cli.py
- supervisor/plugins/const.py
- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
- supervisor/plugins/observer.py
- tests/jobs/test_job_decorator.py
Set limits on how often watchdog will retry when it finds an error. Limits are as follows:
1. If reanimation fails 5 times in the 10 second retry loop then stop trying
2. If we receive 10 failed/unhealthy events in a half hour period then ignore them
This should prevent issues like what was in sentry where an addon with an problematic config is continuously restarted with no hope of succeeding.
> Set limits on watchdog retries

- supervisor/core.py
The issue is, that the certificate can be valid because the drift is not that big, but if other certificates are closer on their end, it will be invalid. Only using the certification of our service as grant that the time is okay, don't work anymore at the time where all using acme and short period validated certificates
- This PR fixes or closes issue: fixes #3764 
> Handle timedrift better if not synchronized

- supervisor/jobs/decorator.py
- tests/addons/test_addon.py
- tests/homeassistant/test_core.py
- tests/jobs/test_job_decorator.py
Instead of failing the `PLUGINS_UPDATED` job condition when one or more plugins are not up to date, first try to update them. Only fail the condition if they could not be updated.
> Attempt plugin update before failing job condition

- supervisor/docker/stats.py
- tests/docker/test_stats.py
- tests/fixtures/container_stats.json
- tests/fixtures/container_stats_cgroupv1.json
- tests/fixtures/container_stats_cgroupv2.json
Memory calculation changed on cgroupv2 according to logic [here](https://github.com/docker/cli/blob/9400e3dbe8ebd0bede3ab7023f744a8d7f4397d2/cli/command/container/stats_helpers.go#L227-L249). Adjust to account for that.
> Fix memory calculation for cgroupv2

- supervisor/__main__.py
Creating the asyncio loop explicitly. This fixes the following
deprecation warning on Python 3.10:
```
/usr/src/supervisor/supervisor/__main__.py:31: DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()
```
> Create asyncio loop explicitly

- supervisor/resolution/checks/dns_server.py
- supervisor/resolution/checks/dns_server_ipv6.py
- tests/resolution/check/test_check.py
- tests/resolution/check/test_check_dns_server_failure.py
- tests/resolution/check/test_check_dns_server_ipv6_error.py
Very minor name change. Checks check something and create an issue with the type of error its looking for. Checks don't check for a type of error. Was bugging me 😄 
> Rename dns checks to fit pattern

- supervisor/docker/addon.py
- supervisor/docker/dns.py
- supervisor/docker/homeassistant.py
- supervisor/docker/observer.py
Adjust OOM killer score to prevent crucial services from getting
selected.
> Improve system behavior on low memory situation

- supervisor/addons/addon.py
I think the current `or` is wrong because it checks event name only with watchdog but the manual stopped is tested without looking also again into event name
> Simplify watchdog container rules

- tests/api/test_resolution.py
> Fix suggestion test to be order agnostic

- requirements.txt
> Bump ruamel.yaml to 0.17.21

- tests/api/test_resolution.py
Follow-up from review on #3822
> No bool conversion in resolution test

- supervisor/dbus/const.py
- supervisor/dbus/network/setting/generate.py
- supervisor/host/network.py
- tests/dbus/network/setting/test_init.py
> Use link-local instead disabled for ipv6

- supervisor/resolution/checks/backups.py
> Add missing await in backup check

- tests/conftest.py
- tests/resolution/check/test_check_backups.py
Add tests for backup check added in #3814 
> Add tests for backups check

- tests/conftest.py
This addresses a deprecation warning when calling tests with Python 3.10:
```
../python3.10/site-packages/pytest_aiohttp/plugin.py:33: DeprecationWarning: 'loop' fixture is deprecated and scheduled for removal, please use 'event_loop' instead
```
> Replace loop test fixture with event_loop

- supervisor/docker/manager.py
Bump min docker version to 20.10.0 - The ADR want 20.10.17 soon but let's start with 20.10.17 because of the OS-8
> Bump supported docker version

- .github/workflows/ci.yaml
- Removes matrix from CI (we were not using it anyway)
- Reuse the same python version for all steps
> Use the same python version for all steps

- supervisor/resolution/evaluations/apparmor.py
- supervisor/resolution/evaluations/cgroup.py
- supervisor/resolution/evaluations/container.py
- supervisor/resolution/evaluations/content_trust.py
- supervisor/resolution/evaluations/dbus.py
- supervisor/resolution/evaluations/dns_server.py
- supervisor/resolution/evaluations/docker_configuration.py
- supervisor/resolution/evaluations/docker_version.py
- supervisor/resolution/evaluations/job_conditions.py
- supervisor/resolution/evaluations/lxc.py
- supervisor/resolution/evaluations/network_manager.py
- supervisor/resolution/evaluations/operating_system.py
- supervisor/resolution/evaluations/os_agent.py
- supervisor/resolution/evaluations/privileged.py
- supervisor/resolution/evaluations/resolved.py
- supervisor/resolution/evaluations/source_mods.py
- supervisor/resolution/evaluations/systemd.py
- tests/resolution/evaluation/test_evaluate_cgroup.py
- Changes docstrings to be correct
- Prevents cgroup evaluation to print double warnings (we already print when the evaluation fails)
> Cleanup evaluations

- supervisor/api/network.py
- supervisor/host/network.py
- tests/api/test_network.py
Fixes #3863
- This PR fixes or closes issue: fixes #3863
> Fix network vlan api

- supervisor/docker/addon.py
With Cgroup2, we should properly only update a device per time
> Only update HW condition at once

- supervisor/dbus/network/ip_configuration.py
- tests/dbus/network/test_ip_configuration.py
> Empty string in gateway returns none

- requirements.txt
- supervisor/dbus/agent/__init__.py
- supervisor/dbus/hostname.py
- supervisor/dbus/interface.py
- supervisor/dbus/logind.py
- supervisor/dbus/manager.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/network/dns.py
- supervisor/dbus/network/interface.py
- supervisor/dbus/network/setting/__init__.py
- supervisor/dbus/network/setting/generate.py
- supervisor/dbus/network/settings.py
- supervisor/dbus/rauc.py
- supervisor/dbus/resolved.py
- supervisor/dbus/systemd.py
- supervisor/dbus/timedate.py
- supervisor/utils/dbus.py
- tests/common.py
- tests/conftest.py
- tests/dbus/network/setting/test_init.py
- tests/dbus/network/test_accesspoint.py
- tests/dbus/test_interface.py
- tests/host/test_network.py
- tests/utils/test_dbus.py
Switch from [dbus-next](https://pypi.org/project/dbus-next/) to our fork ([dbus-fast](https://pypi.org/project/dbus-fast/)) to take advantage of the performance enhancements and other changes being made.
> Switch from dbus-next to dbus-fast

- requirements.txt
- supervisor/dbus/agent/__init__.py
- supervisor/dbus/hostname.py
- supervisor/dbus/interface.py
- supervisor/dbus/logind.py
- supervisor/dbus/manager.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/network/dns.py
- supervisor/dbus/network/interface.py
- supervisor/dbus/network/setting/__init__.py
- supervisor/dbus/network/setting/generate.py
- supervisor/dbus/network/settings.py
- supervisor/dbus/rauc.py
- supervisor/dbus/resolved.py
- supervisor/dbus/systemd.py
- supervisor/dbus/timedate.py
- supervisor/utils/dbus.py
- tests/common.py
- tests/conftest.py
- tests/dbus/network/setting/test_init.py
- tests/dbus/network/test_accesspoint.py
- tests/dbus/test_interface.py
- tests/host/test_network.py
- tests/utils/test_dbus.py
Reverts home-assistant/supervisor#3877
> Revert "Switch from dbus-next to dbus-fast"

- tests/resolution/check/test_check.py
Not having a full backup makes an issue so test should check that the issue its looking for is in the list, not necessarily at the end of the list. Can also mock the backup but may break again if issues added in the future.
> Check if issue in list, not end of list in test

- supervisor/resolution/evaluations/container.py
Extend the list of software that should not run on the host.
> Add portainer as container orchestra

- requirements.txt
Bump dbus-fast from [1.14.0 to 1.15.1](https://github.com/Bluetooth-Devices/dbus-fast/compare/v1.14.0...v1.15.1)
> Bump dbus-fast from 1.14.0 to 1.15.1

- supervisor/docker/homeassistant.py
> Bump HA timeout to match S6_SERVICES_GRACETIME

- supervisor/utils/dbus.py
- tests/api/test_supervisor.py
There's no unpack variants kwarg when setting dbus properties since there's never a response. Ensure we don't pass it in those cases.
- This PR fixes or closes issue: fixes #3910
> No unpack variants for property sets

- .github/workflows/stale.yml
> Adjust stale bot

- supervisor/utils/dbus.py
```
22-10-04 18:22:44 DEBUG (MainThread) [supervisor.utils.dbus] Property change for org.freedesktop.NetworkManager-/org/freedesktop/NetworkManager/ActiveConnection/10: dict_keys(['StateFlags']) changed & [] invalidated
```
Remove the `dict_keys`
> Fix property change debug log

- .github/ISSUE_TEMPLATE/bug_report.yml
Need to collect system information in bug reports as it prevents a lot of routine back and forth in issues. Also fixing instructions to places that don't exist in the UI anymore and adding my links.
> Ask for system information in bug reports

- tests/host/test_manager.py
Test for host reload does not work in isolation. It only works if the host load test has run first because then the dbus interfaces were mock loaded. Fixing to eliminate this dependency.
> Fix host reload test

- supervisor/jobs/decorator.py
- tests/jobs/test_job_decorator.py
Adds the reasons to the returned message.
> Add unhealthy reasons to block message

- supervisor/host/network.py
- tests/jobs/test_job_decorator.py
The `conditions` argument of the `Job` decorator takes a list, there was 1 case in the code and a few cases in test that did not set this properly.
> Job conditions take a list

- supervisor/homeassistant/const.py
- supervisor/resolution/data.py
- supervisor/resolution/module.py
- tests/host/test_network.py
- tests/resolution/test_resolution_manager.py
Dispatch messages to HA when unsupported/unhealthy state changes so HA can tell the user.
> Events when unhealthy/unsupported changes

- supervisor/resolution/const.py
- supervisor/resolution/evaluations/systemd_journal.py
- tests/resolution/evaluation/test_evaluate_systemd_journal.py
Mark systems unsupported if systemd journal is not accessible via gatewayd.
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/24548
> Unsupported check for journal gateway

- .github/workflows/builder.yml
- .github/workflows/ci.yaml
- Cancel un-needed runs
- Fixes situations like this:
> Add action concurrency

- .pre-commit-config.yaml
`https://gitlab.com/pycqa/flake8` is gone, need to use `https://github.com/PyCQA/flake8` now. Also thought I would update all the versions of the things we use to the latest while there since it looks like dependabot doesn't do that.
> Fix & update pre-commit

- supervisor/utils/dbus.py
- tests/conftest.py
- tests/utils/test_dbus.py
> Make dbus-fast calls more robust

- supervisor/utils/common.py
- tests/api/test_jobs.py
Jobs reset doesn't save data after. So if used to unignore ignored job conditions they re-appear next time supervisor restarts. This fixes that.
- This PR fixes or closes issue: fixes #3988
> Jobs reset saves data

- supervisor/addons/build.py
- tests/addons/test_build.py
Also, make arch handling for the build more consistent. Currently they can mixup different arch because it use for each arch-specific things an different evaluations
> Support arch specific dockerfiles

- supervisor/dbus/network/__init__.py
Make sure to set non-primary interfaces to false (required in a changing network environment).
> Prevent multiple primary interfaces

- supervisor/discovery/services/esphome.py
- tests/discovery/test_esphome.py
Adds support for ESPHome dashboard discovery.
This allows the ESPHome add-on to announce itself to Home Assistant.
It will allow Home Assistant to connect to the API exposed by the Dashboard API to
handle device additions and other things (like handling update for devices).
> Add support for ESPHome dashboard discovery

- supervisor/addons/addon.py
`sys_capture_exception` should be `capture_exception` now since sentry may or may not be loaded.
> sys_capture_exception to capture_exception

- supervisor/jobs/decorator.py
- tests/jobs/test_job_decorator.py
Some job conditions were checking against `self.condition` instead of `used_conditions` making them unignorable. Fixes that and ensures that is tested.
Also there were a couple near duplicate test cases in this large file so merged them.
> Allow all job conditions to be ignored

- supervisor/utils/apparmor.py
- tests/common.py
- tests/fixtures/apparmor_multiple_profiles.txt
- tests/fixtures/apparmor_no_profile.txt
- tests/fixtures/apparmor_valid.txt
- tests/fixtures/apparmor_valid_mediate.txt
- tests/utils/test_apparmor.py
Follow up to #4078 , add tests around apparmor profile processing.
Also fix an unlikely edge case where the chosen profile name happens to also occur later in the line as a flag (like if you choose `mediate` and had the `mediate_deleted` flag).
> AppArmor tests and fix profile name in flag

- supervisor/addons/model.py
- tests/api/test_store.py
#4098 caused any check of addon availability to log an error if the addon is unavailable. It should only log an error when specifically asked to validate availability (in the case of install or update), not just when obtaining availability status.
> Don't log error for addon unavailable

- supervisor/dbus/udisks2/const.py
Needs to be a variant, not just a boolean.
> Fix udisks2 standard options constant

- .github/workflows/builder.yml
- supervisor/const.py
- tests/api/test_root.py
- tests/backups/conftest.py
- tests/test_coresys.py
> Fix CI Supervisor version for tests

- requirements_tests.txt
- supervisor/api/__init__.py
- supervisor/api/middleware/security.py
- tests/api/middleware/test_security.py
Allign handling of aiohttp with core to avoid confusion of URL handling.
> Backport core api filter

- tests/addons/test_manager.py
- tests/conftest.py
When working on the issue emontnemery mentioned about addon discovery I made a unit test confirming that supervisor does attempt to delete the discovery message on addon uninstall. Adding it to supervisor.
> Test discovery message deleted on uninstall

- supervisor/addons/validate.py
- supervisor/data/arch.json
- tests/test_arch.py
Add Hardkernel ODROID-M1 to architecture list.
> Add ODROID-M1

- tests/dbus/agent/boards/test_board.py
- tests/dbus/agent/boards/test_yellow.py
- tests/dbus/agent/conftest.py
- tests/dbus/agent/test_agent.py
- tests/dbus/agent/test_apparmor.py
- tests/dbus/agent/test_cgroup.py
- tests/dbus/agent/test_datadisk.py
- tests/dbus/agent/test_system.py
- tests/dbus_service_mocks/apparmor.py
- tests/dbus_service_mocks/boards.py
- tests/dbus_service_mocks/boards_supervised.py
- tests/dbus_service_mocks/boards_yellow.py
- tests/dbus_service_mocks/cgroup.py
- tests/dbus_service_mocks/datadisk.py
- tests/dbus_service_mocks/os_agent.py
- tests/dbus_service_mocks/system.py
Continuation of #4160 - Use mocked services on session dbus for os agent tests instead of fixtures.
> Use session dbus for os agent tests

- tests/common.py
- tests/conftest.py
- tests/dbus/network/setting/test_init.py
- tests/dbus/network/test_connection.py
- tests/dbus/network/test_interface.py
- tests/dbus/network/test_network_manager.py
- tests/dbus/network/test_wireless.py
- tests/dbus/udisks2/test_block.py
- tests/dbus/udisks2/test_drive.py
- tests/dbus/udisks2/test_filesystem.py
- tests/dbus/udisks2/test_manager.py
- tests/dbus/udisks2/test_partition_table.py
- tests/dbus_service_mocks/udisks2_block.py
- tests/dbus_service_mocks/udisks2_drive.py
- tests/dbus_service_mocks/udisks2_filesystem.py
- tests/dbus_service_mocks/udisks2_loop.py
- tests/dbus_service_mocks/udisks2_manager.py
- tests/dbus_service_mocks/udisks2_partition.py
- tests/dbus_service_mocks/udisks2_partition_table.py
Continuation of #4160, #4180 and #4191 - Use mocked services on session dbus for udisks2 tests instead of fixtures
> Use session dbus for udisks2 tests

- supervisor/utils/codenotary.py
- tests/utils/test_codenotary.py
> Disable codenotary until rework of cosign

- supervisor/api/os.py
- supervisor/os/data_disk.py
Don't  if data disk cannot be detected.
Fixes: #4216
> Don't fail if data disk can't be detected

- supervisor/resolution/module.py
- tests/resolution/test_resolution_manager.py
When supervisor tells core that an issue was created or modified, it should include the list of suggestions. Otherwise core just has to immediately ask supervisor for this information in order to make the repair. Faster and simpler to just include it in the message to begin with.
> Issue changed messages include suggestions

- .devcontainer/devcontainer.json
VSCode by default bind mounts the project dir into /workspace. Our scripts assume the Supervisor repository at /workspace/supervisor, but there is no guarnatee for that with VSCode default behavior. Explicitly mount it to /workspace/supervisor so we can safely make that assumption in our devcontainer scripts.
> Support checkout directory which are not named supervisor

- requirements_tests.txt
Seems the package has been deprecated and removed and we use the github action anyway.
> Remove codecov package

- supervisor/dbus/const.py
- supervisor/dbus/systemd.py
- supervisor/host/services.py
- tests/dbus/test_systemd.py
- tests/dbus_service_mocks/systemd.py
Add start transient unit dbus method to systemd proxy interface.
> Add start transient unit dbus method

- .devcontainer/devcontainer.json
This reverts https://github.com/home-assistant/supervisor/pull/4223 as that used the wrong name. It binds the workspace to `/workspace/supervisor` but all our scripts expect the workspace folder to be at `/workspaces/supervisor` as that was the default (ex. https://github.com/home-assistant/devcontainer/blob/7bc7e77e3101dd6317309fa02f175dcf81b99233/supervisor/rootfs/usr/bin/supervisor_run#LL41C24-L41C24 )
Instead what this will do is stash the workspace folder VSCode has picked into an env. And then I will modify the scripts in [devcontainer](https://github.com/home-assistant/devcontainer) to use this env instead of hard-coding the workspace folder. Borrowed this from [frontend](https://github.com/home-assistant/frontend/blob/5bea929c1e766521a8520c264d644ff8e1d8d0bd/.devcontainer/devcontai …
> Fix devcontainer workspace and use env

- .github/workflows/builder.yml
- .github/workflows/ci.yaml
- build.yaml
- requirements.txt
- supervisor/addons/__init__.py
- supervisor/api/ingress.py
- supervisor/backups/manager.py
- supervisor/core.py
- supervisor/homeassistant/module.py
- supervisor/mounts/manager.py
- supervisor/plugins/manager.py
- supervisor/store/__init__.py
- supervisor/updater.py
- supervisor/utils/codenotary.py
- tests/addons/test_manager.py
- tests/homeassistant/test_module.py
- tests/plugins/test_plugin_manager.py
- tests/store/test_store_manager.py
Update supervisor to python 3.11. Will try and bump the version of alpine in a separate PR.
All tests are passing after fixing places we were calling `asyncio.wait` with coroutines. This definitely could use some testing on a live system though. Will do it on mine, would appreciate anyone else trying that wants to.
> Update to python 3.11

- supervisor/mounts/validate.py
Fix problem with saving the new default backup location.
> Add missing default_backup_mount to mount config

- supervisor/mounts/const.py
- supervisor/mounts/manager.py
- tests/backups/test_manager.py
- tests/conftest.py
- tests/mounts/test_manager.py
Add support for mounts in `/share`
> Support share mounts

- supervisor/api/middleware/security.py
With <https://github.com/home-assistant/frontend/pull/16665> and #4320 we now fetch the font files from the frontend bundled with the supervisor instead of relying on core (which can change).
This PR adjusts the regex to allow serving `woff2` files as well.
> Adjust regex to allow woff2 files to be served

- supervisor/docker/addon.py
- supervisor/docker/homeassistant.py
- supervisor/resolution/checks/docker_config.py
- tests/docker/test_addon.py
- tests/fixtures/basic-addon-config.json
- tests/resolution/check/test_check_docker_config.py
Set mount propagation on share mount and check share mount in the docker config issue.
> Add share to docker config issue

- supervisor/docker/interface.py
Need  null check for `_meta` in the new `meta_mounts` property.
> Null check for meta in meta_mounts

- supervisor/api/supervisor.py
- tests/api/test_supervisor.py
- tests/homeassistant/test_module.py
Missed an `asyncio.wait` call in supervisor reload API, needs to be tasks now for python 3.11
- This PR fixes or closes issue: fixes #4331
> Fix asyncio.wait in supervisor.reload

- supervisor/mounts/manager.py
Exit reload immediately if there are no mounts to reload
- This PR fixes or closes issue: fixes #4337 
> Exit reload early if no mounts

- supervisor/resolution/evaluations/operating_system.py
Add support for Debian Bookworm while maintaining the 4 months of support for Bullseye as stated by the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md)
I also removed Debian Buster from the list as it was deprecated as per the ADR... a while ago 
- This PR fixes or closes issue: fixes: https://github.com/home-assistant/supervised-installer/issues/296
- This PR is related to issue: 
- Link to supervised installer pull request: https://github.com/home-assistant/supervised-installer/pull/297 …
> Support Debian Bookworm

- supervisor/bootstrap.py
- supervisor/config.py
- supervisor/mounts/mount.py
- supervisor/mounts/validate.py
- tests/conftest.py
- tests/mounts/test_mount.py
Using a credentials file instead of passing username/password in `options` allows us to remove the character restrictions for username and password in CIFS mounts.
- This PR fixes or closes issue: fixes #4373 , fixes #4352 , fixes #4348
> Allow all characters in mount credentials

- supervisor/const.py
- supervisor/supervisor.py
- tests/test_supervisor.py
Add support for apparmor channels created in https://github.com/home-assistant/version/pull/305
> Add support for apparmor channels

- supervisor/homeassistant/websocket.py
Avoid check_api_state in websocket `_can_send` if we are already connected
> Avoid check_api_state in websocket _can_send if we are already connected

- supervisor/api/discovery.py
- tests/api/test_discovery.py
- tests/fixtures/discovery.json
When listing discovery messages, only ones for running and healthy services should be listed. Otherwise Home Assistant tries to do discovery and gets errors. It's also unnecessary to list these as those services will fire a discovery message when they do successfully startup.
> List discovery only includes healthy addons

- requirements.txt
This reverts commit b8178414a47066b8fa139c713b5669f9c8a991bf.
3.8.5 seems to have created a backwards compatibility issue, this update is the root cause of #4454 . Reverting until I can track down why.
- This PR fixes or closes issue: fixes #4454
> Revert "Bump aiohttp from 3.8.4 to 3.8.5 (#4448)"

- supervisor/dbus/network/setting/generate.py
- tests/dbus/network/setting/test_generate.py
After #4476 we tie settings to interfaces primarily by udev path. However it appears there are some cases where that property is missing according to events in sentry. This adds a fallback to use interface name in those cases. 
> Fallback on interface name if path is missing

- supervisor/addons/validate.py
- supervisor/data/arch.json
- tests/test_arch.py
Add Home Assistant Green support.
> Add Home Assistant Green

- supervisor/store/data.py
> Missing an await in addon data

- supervisor/api/audio.py
Switched from `attr` to `dataclass` so can't use `attr.asdict` anymore, have to use `dataclasses.asdict`
- This PR fixes or closes issue: fixes #4497
> Use dataclasses asdict for dataclasses

- supervisor/misc/tasks.py
This is not longer needed as we update add-on state based on docker events and not anymore over poll.
> Remove old add-on state refresh

- supervisor/store/data.py
Currently we are clearing all data from the store at the start of a data update and then recreating it repository by repository. Since each repository is processed as a separate asyncio task this is not an asyncio safe approach as it allows other tasks expecting to read store data to be interleaved with our data update ones and create errors like this:
```
23-08-29 08:14:39 ERROR (MainThread) [aiohttp.server] Error handling request                                                                                                                                                                                                                                                   …
```
> Update store data in one task to prevent races

- supervisor/docker/homeassistant.py
- tests/docker/test_homeassistant.py
Landingpage doesn't need the same level of access as homeassistant as it does very little. Also when it is started sometimes trying to give it this level of access can cause issues since things aren't necessarily ready yet:
```
23-08-31 15:11:48 INFO (MainThread) [supervisor.homeassistant.core] Using preinstalled landingpage
23-08-31 15:11:48 INFO (MainThread) [supervisor.homeassistant.core] Starting HomeAssistant landingpage
23-08-31 15:11:48 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
23-08-31 15:11:48 ERROR (SyncWorker_0) [supervisor.docker.manager] Can't create container from homeassistant: 400 Client Error for http+docker://localhost/v1.42/containers/create?name=homeassistant: Bad Request ("invalid mount config for …
```
> Skip unnecessary mounts and privileges for landingpage

- supervisor/docker/interface.py
- supervisor/docker/supervisor.py
Add more jobs to docker tasks in supervisor. Also switch a couple docker methods which are not called or scheduled tasks and are safe to repeat from `GROUP_ONCE` to `GROUP_WAIT`. Particularly `attach` as we really don't want to miss that.
> Add jobs to docker supervisor and use group wait

- supervisor/mounts/validate.py
- tests/api/test_mounts.py
It appears `\w` in python includes more options then I realized and allowed through characters that can't be used in filenames. Changing to strictly validating for alphanumeric and underscore characters only in mount names.
- This PR fixes or closes issue: fixes #4483
> Mount names cannot include non-alphanumerics

- supervisor/api/ingress.py
- supervisor/const.py
- supervisor/homeassistant/module.py
#4152 assumed that if we have a user ID on the request then we also have a user's name. This isn't true. Some auth providers like [command line auth](https://www.home-assistant.io/docs/authentication/providers/#command-line) only provide us with a user ID. We cannot assume we have all 3 pieces of info (id, username and display name) and should just pass on what we do have only.
- This PR fixes or closes issue: fixes #4547
- This PR is related to issue: https://github.com/home-assistant/core/issues/99811 …
> Ingress does not break when username missing

- supervisor/backups/backup.py
- tests/backups/test_manager.py
Restore wipes folders before restoring them. But folders now include network mounts so this will not work. Unmount all bind mounts for network mounts before doing a restore into a folder and then remount them afterwards.
> Unmount mounts before backup restore

- .github/workflows/builder.yml
- Dockerfile
- requirements.txt
- supervisor/utils/yaml.py
ruamel.yaml seems to be the source of a lot of yaml parse errors that really don't make any sense since the YAML appears fine. Core has been using pyyaml for a while with a lot less of these issues. The only benefit ruamel.yaml gives us is YAML 1.2 support. Since this isn't something we need or want since its inconsistent with YAML in core (which uses pyyaml and therefore YAML 1.1). And YAML 1.1 is less restrictive then 1.2 so we don't expect this swap to create issues.
Therefore we try swapping it to see if we can reduce the amount of log noise and be consistent with core in YAML handling. …
> Switch from ruamel.yaml to pyyaml

- supervisor/backups/manager.py
- supervisor/jobs/decorator.py
- tests/backups/test_manager.py
When making a backup to a network mount we should not care how much free space is left on the local hard disk. We don't need a free space check at all because it doesn't matter if free space on the network mount is approaching zero, its not our responsibility to keep that machine from filling up all available space. Most likely even if that mount is completely full the system still has some free space its not sharing anyway.
> Network backups skip free space check

- supervisor/homeassistant/api.py
- supervisor/misc/tasks.py
Landingpage does not implement the API we use to check if core is running anymore. ~~The attempt to skip the check was incorrect, by returning false Supervisor always assumed landingpage was down. Needs to always return true to skip this test for landingpage~~
EDIT: We cannot return true in from `check_api_state`. That method is used in other places and makes supervisor think the API is available for landingpage when its not. Disabled the task for landingpage instead. …
> Skip watchdog API test on landingpage

- supervisor/resolution/fixups/mount_execute_remove.py
- tests/resolution/fixup/test_mount_execute_remove.py
After removing a mount need to save data to persist that change over a restart.
- This PR fixes or closes issue: fixes #4617
> Call save data after removing mount in fixup

- supervisor/addons/addon.py
- supervisor/core.py
- supervisor/jobs/decorator.py
Fixed a couple typos, where warnings were containing "more then" to make a comparison. This should be "more than". And "skiping" to "skipping".
Minor, whereas it only contains nitpicking on typos. :)
> Fixing multiple typos

- supervisor/homeassistant/module.py
- tests/homeassistant/test_module.py
Fixes #4624 . Appears the get users API can return `None`
- This PR fixes or closes issue: fixes #4624
> Handle get users API returning None

- supervisor/dbus/network/setting/generate.py
- supervisor/host/network.py
- tests/api/test_network.py
- tests/dbus/network/setting/test_generate.py
- tests/dbus/network/setting/test_init.py
Vlans need to set their parent interface by UUID as it is stable. They currently use interface name which is not necessarily stable and was changed in OS 11.0
> Use UUID for setting parent interface in vlans

- supervisor/jobs/__init__.py
- tests/jobs/test_job_manager.py
Unstarted jobs should not warn when removed like this:
```
23-10-17 08:05:08 WARNING (MainThread) [supervisor.jobs] Removing incomplete job supervisor_check_connectivity from job manager
23-10-17 08:05:08 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/rhasspy/hassio-addons repository
23-10-17 08:05:08 WARNING (MainThread) [supervisor.jobs] Removing incomplete job supervisor_check_connectivity from job manager
23-10-17 08:05:08 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
``` …
> Don't warn for removing unstarted jobs

- supervisor/host/manager.py
- supervisor/host/sound.py
In the past the audio plug-in restarted Pulseaudio on hardware change. This broke with the s6 updates. However, it also turns out that this is quite racy: The Supervisor reloads audio data much too quickly, when Supervisor isn't restarted yet.
Instead, let's reload the relevant modules from Supervisor itself.
This works well with a USB microphone on Home Assistant Green.
Related change: https://github.com/home-assistant/plugin-audio/pull/153 …
> Reload Pulseaudio modules on hardware change

- supervisor/utils/yaml.py
Yaml loader did not catch unicode decode errors as json loader did.
- This PR fixes or closes issue: fixes 
- This PR is related to issue: https://github.com/home-assistant/core/issues/102818
> Catch unicode decode errors

- Dockerfile
- supervisor/utils/__init__.py
Fixes #4652 as supervisor will be blocked from removing anything from a mount during a restore if a mount somehow got left in one of the folders its trying to restore.
- This PR fixes or closes issue: fixes #4652 
> Remove folder only deletes from current filesystem

- supervisor/homeassistant/module.py
Don't remove Home Assistant folder itself on a restore, only its contents. Otherwise we reset the inode and all addons mapping `config` will need a restart to see HA config again.
> Don't remove folder itself on restore

- supervisor/addons/__init__.py
- supervisor/addons/addon.py
- supervisor/addons/model.py
- supervisor/api/addons.py
- supervisor/api/store.py
- supervisor/backups/backup.py
- supervisor/backups/manager.py
- supervisor/misc/tasks.py
- tests/addons/test_addon.py
- tests/addons/test_manager.py
All methods in addon which interface with docker now employ job group locking. This prevents things like an unexpected and poorly timed call to `restart` from messing up an `update` or `restore` due to race conditions with the tasks.
> Addon methods interfacing with docker are job groups

- supervisor/homeassistant/api.py
- tests/conftest.py
> Fix Home Assistant Core API check

- .devcontainer/devcontainer.json
Use the new structure used by VSCode. Also drop deprecated configurations. The tools inside the devcontainer seem to get picked up by Visual Studio Code automatically, without the need of customizing paths.
> Update devcontainer.json to use the new format

- supervisor/addons/model.py
- supervisor/api/middleware/security.py
- supervisor/api/utils.py
- supervisor/homeassistant/api.py
- supervisor/utils/__init__.py
We check core version quite frequently in the code, and its a bit expensive to do all the comparsions everywhere. Since its mostly the same check happening over and over we can cache it
We can effectively get rid of the highlighted flames
> Cache common version checks

- supervisor/utils/sentry.py
This gives better insight for certain issues as more log entries are available in the breadcrumbs of captured Sentry issues.
> Add log entries of level INFO to Sentry breadcrumbs

- supervisor/api/ingress.py
This is a port of https://github.com/home-assistant/core/pull/103477 from core
> Use content-type fast path for common case

- pytest.ini
- tests/api/middleware/test_security.py
- tests/api/test_addons.py
- tests/api/test_audio.py
- tests/api/test_dns.py
- tests/api/test_homeassistant.py
- tests/api/test_multicast.py
- tests/api/test_supervisor.py
- tests/dbus/test_interface.py
- tests/jobs/test_job_decorator.py
- tests/utils/test_dbus.py
Address pytest warnings and turn them into errors by default. There is one warning caused by an external package, add this to the ignore list.
> Address pytest warnings

- requirements.txt
- supervisor/api/__init__.py
changelog: https://github.com/aio-libs/aiohttp/compare/v3.8.6...v3.9.0
> Bump aiohttp to 3.9.0

- requirements.txt
- supervisor/api/__init__.py
Bump aiohttp to 3.9.1
changelog: https://github.com/aio-libs/aiohttp/compare/v3.8.6...v3.9.1
The issues that caused us to revert 3.9.0 have been fixed
> Bump aiohttp to 3.9.1

- Dockerfile
- supervisor/utils/__init__.py
Instead of using rm -rf use find to delete files recursively. This has the added benefit that we do not need to rely on shell expansion.
In particular, shell expansion caused the --one-file-system flag to not work as intended: The idea was that the content of a (left-over) bind mounted directory would not get deleted. However, since shell expansion passed the directory to rm, rm happily deleted also files in that bind mounted directory.
Fixes: #4652, #4711, #4726 
Relates-to: #4653 …
> Use find to delete files recursively

- supervisor/docker/homeassistant.py
- tests/homeassistant/test_core.py
Bump core shutdown timeout for new pre-stopping core state which adds up to 20s for automations to run
Core PR: https://github.com/home-assistant/core/pull/91165
> Bump core shutdown timeout for new pre-stopping core state

- .github/workflows/builder.yml
- .github/workflows/release-drafter.yml
> Address GitHub action deprecation warnings

- supervisor/addons/validate.py
- supervisor/data/arch.json
- tests/addons/test_config.py
- tests/test_arch.py
> Add Raspberry Pi 5

- .devcontainer/devcontainer.json
- .github/workflows/builder.yml
- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- build.yaml
- pyproject.toml
- requirements_tests.txt
- supervisor/addons/addon.py
- supervisor/backups/backup.py
- supervisor/config.py
- supervisor/hardware/helper.py
- supervisor/homeassistant/module.py
- supervisor/utils/dt.py
- tests/api/middleware/test_security.py
- tests/conftest.py
- tests/jobs/test_job_decorator.py
- tox.ini
Update Supervisor from python 3.11 to [python 3.12](https://docs.python.org/3/whatsnew/3.12.html)
Corresponding update to devcontainer to merge after: https://github.com/home-assistant/devcontainer/pull/59
Note - this also contains major updates to versions of dependencies in pre-commit config as those were woefully out of date and didn't know about python 3.12. I guess we should look into an automated means of keeping that file up to date. …
> Update python to 3.12

- .github/workflows/builder.yml
- requirements.txt
`dirhash` needs `pkg_resources` which is provided by `setuptools` https://github.com/andhus/dirhash-python/pull/11
Its been failing since upgrading to python 3.12
https://github.com/home-assistant/supervisor/actions/runs/7513346221/job/20454994962
> Fix dirhash failing to import pkg_resources

- supervisor/bootstrap.py
Fixes #4829 
- This PR fixes or closes issue: fixes #4829
> Fix bootstrap log typo

- supervisor/homeassistant/api.py
Currently a timeout leads to a log entry which simply states: "Error on call http://172.30.32.1:8123/api/core/state: ". From this, it is not immeaditly clear what the problem is. This commit adds a log entry which explicitly states that the request timed out.
> Explicitly log when API requests timeout

- requirements.txt
changelog: https://github.com/pvizeli/securetar/compare/2023.12.0...2024.2.0
> Bump securetar to 2024.2.0

- requirements.txt
- supervisor/backups/backup.py
- tests/backups/test_backup.py
~~needs https://github.com/pvizeli/securetar/pull/33~~
~~needs https://github.com/home-assistant/supervisor/pull/4888~~
core version https://github.com/home-assistant/core/pull/110267
This is a followup to #4843 where I noticed a large chunk of the time on I/O bound systems is copying the data into the tarfile and than making another tarfile of the original tarfiles. This will allow us to effectively cut the disk writes in half when creating backups and increase storage media longevity.  Additionally this means the user no longer needs twice as much disk space as the backup size since there is only one copy of the backup being written to disk now.
To avoid the double copy, we now write each tarfile into the fileobj of the outer tar file.
This reduced my backup time on my fast system from …
> Create backups files without having to copy inner tarballs

- supervisor/mounts/mount.py
It seems that #4882 and the bump to ruff 0.2.1 with #4877 got merged with different bases. So this introduced a new ruff issue into the main codebase. Address the issue.
> Fix new complaint by ruff 0.2.1

- supervisor/addons/addon.py
- supervisor/addons/model.py
Make sure both timestamps are UTC, otherwise Python complains with:
```
TypeError: can't compare offset-naive and offset-aware datetimes
```
Related-to: https://github.com/home-assistant/supervisor/pull/4838
- This PR fixes or closes issue: fixes #4896
> Fix autoupdate time compare

- requirements.txt
Bump securetar to 2024.2.1 fixing #4924
- This PR fixes or closes issue: fixes #4924
> Bump securetar to 2024.2.1

- supervisor/api/__init__.py
- supervisor/api/middleware/security.py
- supervisor/api/os.py
- supervisor/dbus/agent/system.py
- supervisor/os/data_disk.py
- tests/api/middleware/test_security.py
- tests/api/test_os.py
- tests/dbus/agent/test_system.py
- tests/dbus_service_mocks/agent_system.py
- tests/dbus_service_mocks/logind.py
- tests/os/test_data_disk.py
Home Assistant should have a factory reset option: https://community.home-assistant.io/t/wth-where-is-factory-reset-option/468659
This isn't exactly a factory reset since we can't really do that. We don't maintain a copy of the state of the device when first turned on and we sit too far above the hardware anyway. But a complete wipe of the datadisk is close enough to serve our purposes here. It provides an easy way to not only wipe all Home Assistant and Add-on config but also settings of docker and downloaded images and reset the user to a nearly clean slate.
~~It notably will miss some user-configurable things such as network settings. Which would definitely confuse people if advertised as a factory reset, should try to clarify the difference in documentation.~~ Actually it will clear …
> Add an admin only device wipe API

- supervisor/misc/tasks.py
Check used for auto-update was wrong. This fixes #4914
- This PR fixes or closes issue: fixes #4914
> Fix check used for addon auto update

- supervisor/api/proxy.py
We can "proxy" WebSocket close messages just as well as any other WebSocket message. This avoids an error print in the Supervisor logs whenever any one side of the connection closes.
- This PR fixes or closes issue: fixes #4870
> Proxy WebSocket close messages as well

- supervisor/api/__init__.py
- supervisor/api/const.py
- supervisor/api/os.py
- supervisor/dbus/rauc.py
- supervisor/exceptions.py
- supervisor/host/manager.py
- supervisor/os/manager.py
- tests/api/test_os.py
- tests/dbus/test_rauc.py
- tests/dbus_service_mocks/rauc.py
- tests/host/test_manager.py
Every time OS is updated we keep the old version in a separate boot slot. We use this for automatic rollbacks in case of catastrophic failure but there's no reason users couldn't use this to do fast and easy manual rollbacks in cases of smaller errors they noticed which aren't catastrophic. This new API allows users to change the active boot slot between A and B
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/2107
- Link to cli pull request: https://github.com/home-assistant/cli/pull/469 …
> Allow client to change boot slot via API

- supervisor/addons/addon.py
- supervisor/addons/manager.py
- supervisor/addons/model.py
- supervisor/resolution/fixups/store_execute_reload.py
- supervisor/store/__init__.py
- supervisor/store/git.py
- supervisor/store/repository.py
- tests/addons/test_addon.py
- tests/addons/test_manager.py
- tests/store/test_store_manager.py
Reduce stat calls by caching the existence of various addon paths. We clear the cache when we see there has been a change in the repository.
As an added performance bonus, we now only do a git reset if we see there has been a new commit in the fetch. If the commit we see matches what was returned for a fetch on the branch we leave it as is.
For the local repository we clear the cache every 3 hours when a store reload is called or when the user clicks rebuild since we can't ask git if there's been a new commit. Not ideal but the local repo is intended for dev and testing anyway and not a place to put addons long term so it seems like an acceptable trade off.
Supercedes #4675
- Link …
> Cache existence of addon paths

- supervisor/misc/tasks.py
Commit 140b769a42156b476b92edc5eb8cbff3455c6bd0 separated the `continue` from its block, so this puts it back, as I believe it was intended to be.
I do not intend to set up a local development environment just for this drive-by fix, but I hope that you will still be able to accept this simple fix - if it is indeed a bug.
> Restore lost continue statement

- .github/workflows/builder.yml
- .github/workflows/ci.yaml
- build.yaml
The external service cosign relies on updated with a breaking change. Therefore we need to bump both of these to latest to keep CI working.
- Cosign: [v2.0.2...v2.2.3](https://github.com/sigstore/cosign/compare/v2.0.2...v2.2.3)
- Builder: [2024.01.0...2024.03.5](https://github.com/home-assistant/builder/compare/2024.01.0...2024.03.5)
> Bump cosign to `v2.2.3` and builder to `2024.03.5`

- supervisor/utils/systemd_journal.py
Sometimes an empty line is returned from readuntil when EOF is reached, which seems to be caused by a race of the EOF check in the loop and later check in readuntil. With this fix, I am not able to reproduce the issue anymore.
> Fix IncompleteReadError happening sometimes when reading Systemd logs

- build.yaml
> Update base images to 3.12-alpine3.19

- supervisor/os/const.py
- supervisor/resolution/checks/disabled_data_disk.py
- supervisor/resolution/const.py
- supervisor/resolution/fixups/system_adopt_data_disk.py
- supervisor/resolution/fixups/system_rename_data_disk.py
- tests/dbus/udisks2/test_filesystem.py
- tests/dbus_service_mocks/base.py
- tests/dbus_service_mocks/udisks2_filesystem.py
- tests/dbus_service_mocks/udisks2_manager.py
- tests/resolution/check/test_check_disabled_data_disk.py
- tests/resolution/fixup/test_system_adopt_data_disk.py
- tests/resolution/fixup/test_system_rename_data_disk.py
Allow adopting a data disk that was disabled at first boot of HAOS. Also prompt users to rename it to `hassos-data-old` if they don't want to adopt it so we know that and the repair won't come back.
> Adopt a disabled data disk

- supervisor/api/__init__.py
- supervisor/api/host.py
- tests/api/test_supervisor.py
Supervisor logs fallback in get_supervisor_logs didn't work properly because the exception was caught in api_process_raw instead. This was not discovered in tests because the side effect raised OSError, which isn't handled there.
To address that, I split the advanced_logs to two functions, one being a wrapped API handler, one being plain function returning response without any additional error handling. The tests now check for both cases of errors (HassioError and random generic Python error).
- This PR fixes or closes issue:
- This PR is related to issue: #5021 …
> Fix Supervisor logs fallback

- supervisor/resolution/fixups/system_create_full_backup.py
The Create Full Backup fixup was missing the issues property linking it to the No Current Backup issue. This meant the issue and suggestion were considered separate and not shown together or dismissed together.
> Add issues field to create full backup suggestion

- requirements.txt
https://github.com/ijl/orjson/issues/479
> Revert orjson to 3.9.15 due to segmentation faults

- requirements_tests.txt
Bump pytest asyncio to `0.23.6` ([`v0.23.5...v0.23.6`](https://github.com/pytest-dev/pytest-asyncio/compare/v0.23.5...v0.23.6)
> Bump pytest-asyncio to 0.23.6

- supervisor/dbus/udisks2/__init__.py
If we fail to connect to UDisks at load, don't try to set up the signal listeners.
> Skip udisks listener on failure to connect

- requirements.txt
This reverts commit 71e91328f1c225d774ba9492e133147470427744.
It is not proven that the segfaults seen in Core are resolved (see https://github.com/ijl/orjson/issues/479). Since we are shipping a bugfix release, conservatively revert back to 3.9.15.
> Revert "Bump orjson from 3.9.15 to 3.10.3 (#5057)"

- requirements.txt
Make sure Python requests package is pinned to a known version. This is required by docker-py for instance. This fixes current CI builds.
> Pin Python requets package

- supervisor/resolution/fixups/addon_execute_repair.py
- tests/resolution/fixup/test_addon_execute_repair.py
If the addon image repair fixup fails 5 times then it stops being auto-applied. At this point we assume this cannot be fixed automatically and requires manual intervention so we stop using resources pulling/building the image and failing.
> Max retries for auto applying addon image fixup

- supervisor/resolution/checks/multiple_data_disks.py
- tests/resolution/check/test_check_multiple_data_disks.py
Supervised installations do not have a specific data disk, so only check for duplicate data disks on Home Assistant OS.
[client-library-repository]: https://github.com/home-assistant-libs/python-supervisor-client/
> Check for duplicate data disks only when the OS is available

- supervisor/dbus/udisks2/data.py
- supervisor/resolution/checks/duplicate_os_installation.py
- supervisor/resolution/const.py
- tests/resolution/check/test_check_duplicate_os_installation.py
The HAOS update system relies on partition label and partition UUIDs to find the correct partition to update. If for some reason the user has multiple HAOS installations on a system, we might update the "wrong" partition.
This adds a check for dupplicate parittions, and  marks the system as unhealthy in case multiple partitions with the same partition label or UUID is found.
Implements: #6021
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/40022 …
> Mark system as unhealthy if multiple OS installations are found

- build.yaml
Update the Supervisor base image to Alpine 3.22 for all architectures.
[client-library-repository]: https://github.com/home-assistant-libs/python-supervisor-client/
> Update to Alpine 3.22

- supervisor/hardware/disk.py
- tests/hardware/test_disk.py
This avoids that we display a 10% life time use for a brand new eMMC storage. The values are estimates anyways, and there is a separate value which represents life time completely used (100%).
For a detailed description of the eMMC life time used meaning see https://github.com/home-assistant/supervisor/pull/2413#issuecomment-769889885.
Related to https://github.com/home-assistant/frontend/pull/26379. …
> Return optimistic life time estimate for eMMC storage

- .github/workflows/ci.yaml
Use name and path parameters to explicitly download the coverage report artifact. This fixes a behavioral change introduced with v5.0.0 ofactions/download-artifact.
The build matrix has been removed already a while ago in #3864. Remove the remaining traces.
[client-library-repository]: …
> Use path for actions/download-artifact to fix coverage report

- supervisor/addons/manager.py
The JobGroup concurrency decorator of the Addon class does not prevent concurrent installation since the AddonManager creates a separate object for each installation. Make sure only one add-on installation is running at a time by using the JobGroup decorator on the AddonManager install method instead.
[client-library-repository]: …
> Avoid race condition on add-on installation

- supervisor/addons/model.py
Add-on documentation might not have valid UTF-8 encoding. Since this is user provided content, we should not fail if it contains invalid UTF-8 characters. Instead, we can replace them with a placeholder.
[client-library-repository]: https://github.com/home-assistant-libs/python-supervisor-client/
> Ignore UTF-8 errors in addon docs

- supervisor/const.py
- supervisor/docker/interface.py
- supervisor/docker/manager.py
- supervisor/exceptions.py
- tests/addons/test_addon.py
- tests/addons/test_manager.py
- tests/conftest.py
- tests/docker/test_interface.py
- tests/homeassistant/test_core.py
- tests/plugins/test_plugin_base.py
The high-level docker client in the library we use handles errors during image pulls very poorly. It suppresses the entire log during the actual pull (including any errors) and just assumes it went successfully. If something did go wrong then what actually happens is the call to get the image fails (because it was never pulled). This leads to very confusing error messages like in #5938 that don't describe what is actually wrong in any way.
This fixes that by using the low-level client instead. It basically mimics the behavior of the high level client except now we actually read the pull log. And if there's an error, we raise an exception with those details.
Additionally I set it up to fire all the non-error messages on the bus. This PR doesn't make use of that yet but this log includes a …
> Improved error handling for docker image pulls

- supervisor/jobs/__init__.py
- tests/docker/test_interface.py
There are many sentry issues of pull progress log entries being skipped because of rounding errors. If two updates are so close together that they round up to the same thing at one decimal place then the entry is incorrectly skipped. Fix by making progress in jobs not rounded and only rounded when the value is output to the API. …
> Do not skip messages in pull progress log due to rounding

- tests/jobs/test_job_decorator.py
Running tests in UTC+2 timezone makes some of the tests fail because the mocked time in the future is actually in the past, as UTC is used as the new reference point. Adjust the tests to mock also the time when the first execution of function happens.
Instances where the second execution happened "immediately" were mocked to happen 1ms later. The 1ms delta is also needed to be added when mocking time 1h in the future, otherwise it will be throttled too. …
> Make test_job_decorator tests timezone agnostic
