- hassio/const.py
- hassio/dock/__init__.py
- hassio/dock/addon.py
- hassio/dock/homeassistant.py
- hassio/dock/util.py
- This code allow user to use every dockerfile without change for hass.io
- Cleanup wired version tracking code
- Make build system more robust
> Use label instead env, cleanup build

- hassio/addons/validate.py
- hassio/const.py
- hassio/core.py
- version.json
- Add support for nested dicts in addons options. Example:
```
"group": {
"element1": "bla"
}
```
- Use new startup layout for addons. Please change it on our addons. We have now: `initialize`, `system`, `services`, `application`. To migrate use for `before` -> `services` and `after` -> `application`
> Release 0.44

- hassio/addons/validate.py
In order to allow writes to /dev/mem, which is needed e.g. to use the
GPIO ports on Raspberry Pi, the SYS_RAWIO capability needs to be
granted.
Fixes #134.
**NOTE:** I haven't been able to test this, so please verify it as you please before merging :)
> Allow privileged capability SYS_RAWIO

- hassio/addons/git.py
Cloning GIT repositories, containing hass.io add-ons, recursively, allowing the use of GIT submodules in those add-on repositories.
Imagine maintaining a large add-on repository, with all kinds of plugins. The issue tracker of this repository would possibly contain all kinds of stuff, a big mix of issues for all those different add-ons.
Using submodules an add-ons repository maintainer could separate the actual add-on from the repository. This would potentially help with issue tracking separation, but also with things like testing.
> Recursively git clone addon repositories, allowing submodules

- hassio/addons/validate.py
We can not care about custom modify config.json and they can make trouble in future changes. This prevent us also to install a addon they config is not supported with the current running hass.io version
> Remove support for custom configs / configs for other hass.io versions

- hassio/addons/addon.py
- hassio/addons/validate.py
- support now dynamic lookup for proto: `[PROTO:ssl]://[HOST]:[PORT:80]/login`. This try to lookup `ssl` in options and set `https` if they will be true or `http`
> Allow dynamic handling of proto part

- API.md
- hassio/addons/addon.py
- hassio/api/addons.py
For tests I had add function to set the version on installation. That was never the idea on the productive system. I forgot to remove this old code.
> Remove dedicated API calls

- hassio/addons/addon.py
- hassio/addons/validate.py
- setup.py
- Allow to set option as optional inside schema with a `?` on the end of type: `str?`
- Remove `deepmerge` and use python3.6 merge to protect merge into wrong storage
- Allow simple lists inside dicts:
```json
{
"step1": {
"step_list": ["str"]
},
"step_deep": [
{
"step_deep_list": ["str"]
}
]
}
```
> Allow to set a option als optional

- hassio/addons/addon.py
- hassio/addons/validate.py
- hassio/const.py
- hassio/dock/addon.py
- Add new add-on config options `legacy`. This allow to use docker image without hass.io labels and give full support
> Add support for legacy mode

- hassio/addons/built-in.json
Changes it to "you", this improves the display of the maintainer for local add-ons.
Fixes #243
> Re-labeling of "By our self"

- hassio/addons/validate.py
I'm developing an addon that uses a DVB card. In order to use this card the capabilities SYS_TIME and SYS_NICE need to be granted.
> Allow additional docker privileges

- hassio/api/addons.py
> Small typo in error msg

- .github/move.yml
With [ProBot Move Issues](https://probot.github.io/apps/move/) we are able to move an issue around.
Command Syntax:
```text
/move [to ][<owner>/]<repo>
```
This feature is already activate for the main repo, the docs and the Polymer repo.
> Enable probot move

- hassio/addons/validate.py
Currerntly it's not possible to create an addon for pigpiod (the pigpio daemon) because it uses mmap and required the IPC_LOCK capability when running the addon Docker image.
This PR adds support to home-assistant for this.
> Allow addons that require IPC_LOCK capability

- hassio/host/asound.tmpl
hw identifiers should not have {} around them.
Verified fix with snips addon.
> Fix for asound.tmpl

- hassio/misc/hardware.py
Improves the handling of the search for available audio devices.
On systems without audio devices (and therefore no `asound` installed) the following error is now thrown in the logs:
```
18-05-07 17:14:50 ERROR (MainThread) [hassio.misc.hardware] Can't read asound data: [Errno 2] No such file or directory: '/proc/asound/cards'
```
This PR improves this a little, adding an additional check with a proper matching info log.
**Note**: This change has been dry-coded. I currently do not have a test machine available, nevertheless, the change is trival imho.
> Improves audio devices handling

- hassio/addons/data.py
This code is not needed anymore. It is also a security problem because add-on author can change the config after the user has installed it.
> Remove update config with allready installed one

- .travis.yml
- hassio/api/homeassistant.py
- hassio/api/proxy.py
- hassio/const.py
- hassio/exceptions.py
- hassio/homeassistant.py
- hassio/tasks.py
- hassio/validate.py
- pylintrc
- setup.py
Authenticate with Home Assistant using access tokens.
**Not tested yet. Assumes Python 3.7.**
> Leverage access and refresh tokens if available

- hassio/addons/validate.py
I'm trying to create a PulseAudio addon. In order to enable real-time scheduling, the addon minimally needs the SYS_RESOURCE capability. SYS_NICE is only sufficient for high-priority. Unfortunately, I'm experiencing lots of underruns, and strongly suspect the lack of real-time scheduling in the addon as the cause.
> Add SYS_RESOURCE to list of valid privileges

- hassio/bootstrap.py
- hassio/config.py
- hassio/coresys.py
- hassio/docker/addon.py
- hassio/docker/homeassistant.py
- hassio/homeassistant.py
- hassio/utils/dt.py
Fix:  #638
We used before a free geo ip service to evulate the timezone before home-assistant was able to tell us the correct timezone. Now this service is not anymore free and we had need remove it.
With this change, it should work a bit like with this service and should fix some misshandling with timezone
> Change timezone handling

- .dockerignore
Add virtual environments to the `.dockerignore` file.
This prevents the virtual env from being transferred into the Docker image/build.
> Adds venv to .dockerignore

- hassio/addons/addon.py
- hassio/tasks.py
Fixes a small typo in a method name.
`test_udpate_schema` -> `test_update_schema`
> Fixes a typo in method name

- hassio/addons/validate.py
Odroid-cu2 does not exist AFAIK, it needs to be c2.
Fixes related add-on install issue: https://github.com/hassio-addons/addon-motioneye/issues/1
> Fix machine 'odroid-c2'

- hassio/addons/validate.py
Since I can't install a new add-on since hassio release 134 because of error 'addon not supported on armhf'. I think that support for tinker board is missing
> Add missing tinker board

- hassio/addons/validate.py
- tests/addons/test_config.py
At the moment you can not install an add-on with an image value like `registry.gitlab.com/company/add-ons/demo-service/demo-service`
See [Regex101](https://regex101.com/r/8DQgL4/1/) for further details.
> Bugfix Add-on validate correct image url

- hassio/addons/validate.py
This PR sorts the machine list alphabetically, and adds support for the Orange Pi Prime
> Add support for the Orange Pi Prime

- .github/move.yml
This reverts commit 07c4058a8c74d3eb852de5e5095ad186585d60aa.
Re-enabling the probot movebot again to allow for non-admins to move issues between repos.
> Revert "Delete move.yml"

- hassio/tasks.py
Very minor spelling correction.
> Correct typo: 'ignore' -> 'ignored'

- hassio/api/proxy.py
Access to the API from add-ons is logged with every request, which spams the supervisor logs for add-ons that access it frequently, eg if they update sensors or poll state.  This downgrades the logging for such requests from 'info' to 'debug'
resolves home-assistant/hassio#865
> Downgrade add-on API access logging to debug

- hassio/docker/interface.py
Fixes #1018 by removing tag if it exist in the image name.
> Remove potential tag when pulling new image

- hassio/addons/model.py
- hassio/docker/addon.py
Fix bug after restoring or unplug devices like: 
```
[hassio.docker] Can't start xxx: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyACM0": no such file or directory")
```
> Fix device bug

- hassio/addons/model.py
```
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/hassio/hassio/api/security.py", line 144, in token_validation
return await handler(request)
File "/usr/src/hassio/hassio/api/utils.py", line 32, in wrap_api
answer = await method(api, *args, **kwargs)
File "/usr/src/hassio/hassio/api/discovery.py", line 44, in list
self._check_permission_ha(request)
File "/usr/src/hassio/hassio/api/discovery.py", line 38, in _check_permission_ha
if request[REQUEST_FROM] != self.sys_homeassistant:
File "/usr/src/hassio/hassio/addons/model.py", line 452, in __eq__
if self.slug == other.slug:
AttributeError: 'HomeAssistant' object has no attribute 'slug'
```
> Fix error on add-on comparing

- hassio/discovery/services/adguard.py
Adds support for discovery of the `adguard` integration of Home Assistant.
Parent PR: home-assistant/home-assistant#24219
> Support for AdGuard Home discovery

- hassio/api/security.py
With this, the CLI will not work (of course).
> Allow manager role to access DNS API

- hassio/data/coredns.tmpl
When using CoreDNS with the forward plugin; Multiple upstreams are randomized on first use.
This causes one of the configured or provided upstream server to be selected, which can be a bit unexpected. A user-provided server should be used first, the standard provided servers as a fallback.
From the documentation:
---
* `policy` specifies the policy to use for selecting upstream servers. The default is `random`.
* `random` is a policy that implements random upstream selection.
* `round_robin` is a policy that selects hosts based on round robin ordering.
* `sequential` is a policy that selects hosts based on sequential ordering.
---
I've adjusted this policy to be `sequential` in this PR.
> Adjust coredns to use upstream fowarding server in order

- hassio/dns.py
The `localhost` entry is missing from the `hosts` file, which causes all kinds of weird behavior.
This PR adds back in that entry on init.
> Add localhost to hosts file

- hassio/data/coredns.tmpl
Right now, `local.hassio.io` forwards to upstream DNS servers, however, it should not.
The `hass.io` domain has a wildcard on AWS, which now results in looking up `sdjhfkjdshfjkdsks` (random) on a Hass.io box, resolves to AWS.
This PR prevents that by excluding `local.hass.io` from forwarding.
> Adjust coredns do not forward local.hass.io

- hassio/const.py
Currently, the Hass.io DNS falls back to Google DNS & CloudFlare's one dot one dot one dot one.
Just hours after releasing Hassio DNS, people started commenting on the privacy concerns with Google DNS. 
This PR is addressing this privacy concern, by changing the defaults to the 2 biggest privacy-aware DNS providers out there: CloudFlare & Quad9. Both have an excellent track record. 
Cloudflare is considered the fastest DNS server in the world (based on dozens of different benchmarks), hence I've moved it to be the first one. Quad9 has about the same response speed as Google DNS, hence I've added Quad9 as a second.
TL;DR: Replace Google DNS by Quad9 in order to address possible privacy concerns.
> Replace Google DNS by Quad9, prefer CloudFlare

- hassio/discovery/services/home_panel.py
Adds support for `home_panel` discovery in Home Assistant.
Related PR: home-assistant/home-assistant#27540
> Add support for Home Panel Discovery

- hassio/secrets.py
Gracefully allow for duplicate keys in secrets to prevent issues when a user has mistakenly added a duplicate secret.
Closes #1333
> Gracefully allow loading duplicate keys in secrets

- hassio/addons/__init__.py
rebuilded (valid, but archaic) --> rebuilt
> Fix grammatical issue in log message

- hassio/dns.py
Small change to prefer admin defined DNS servers, that is those defined using ```hassio dns options --servers dns://1.2.3.4``` 
See #1316 for discussion.
> Prefer admin defined DNS

- .github/lock.yml
As discussed, this will add configuration to automatically lock PR's that are closed (a day after locking).
This prevents discussion/questions raised on older PR's (while instead, one should just open a new issue).
> Add configuration for Lock Threads on closed pull requests

- hassio/misc/hardware.py
Allow to pass video* devices to containers. Should allow to use usb webcams / uvc tuners.
> Add video devices to video mapping

- hassio/const.py
- hassio/core.py
- hassio/coresys.py
The update of the supervisor can end up in write the last boot time while he restarts itself. Because we never process a full boot, we end up in a bad state. It only happens, for instance, they were a bit down.
> Fix wrong last boot

- supervisor/hwmon.py
Old generic installation can run SU without privileged and this break udev. Let show an error instead break the startup. Fix partial: #1556
> Fix udev error without privileged

- supervisor/addons/validate.py
use case tmpfs based mariadb for recorder taking over 2 mins for dump to stable storage on Pi4.
I can't see why this can't be raised it seems an arbitrary limit? Discuss.
Phill.
> Rasie limit on container shutdown for addons 

- README.md
Noticed this points to the old pipeline.
Not sure what badge you want to show so chose `Release`
> Remove Azure CI badge

- supervisor/api/__init__.py
- supervisor/bootstrap.py
- supervisor/core.py
- supervisor/homeassistant.py
- supervisor/hwmon.py
- supervisor/misc/scheduler.py
- supervisor/supervisor.py
Python actually does not have a fatal. Fatal is an alias to critical (see PEP-282).
This PR removes the use of the alias.
> Replace Logger.fatal by Logger.critical

- supervisor/docker/interface.py
- supervisor/homeassistant.py
- supervisor/snapshots/__init__.py
- supervisor/store/git.py
Removes the passing along of the loop, as it is deprecated in Python 3.8
```
/home/frenck/code/supervisor/supervisor/docker/interface.py:26: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
self.lock: asyncio.Lock = asyncio.Lock(loop=coresys.loop)
```
> Remove passing in deprecated loop arguments

- pylintrc
Cleans up the Pylint configuration, more in line with the core repository.
This PR does not change any code.
- Sets jobs to 2, make Pylint around 40% quicker.
- Remove duplicate disabled rules.
- Disables formatting rules in Pylint (handled by Black).
- Removed disabled rules that currently had no offenders in the codebase.
> Cleanup and speedup pylint

- .devcontainer/devcontainer.json
- .github/lock.yml
2 small changes:
- Removed a comment from the devcontainer.json, making the `json` valid for validating, as the JSON format natively doesn't support comments.
- Indenting was off in .github/lock.yaml
> Fix YAML & JSON styling

- rootfs/etc/services.d/supervisor/finish
Noticed during shutdown of the supervisor in my dev environment:
```
20-05-21 10:02:19 INFO (MainThread) [__main__] Close Supervisor
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
This PR addressed that, by adjusting the S6 Overlay service finish script for the Supervisor.
> Fix S6 supervisor not listening in finish script

- supervisor/ingress.py
Addresses issue, when supervisor crashes on start, if ingress.json contains incorrect timestamp for some reason.
To address https://community.home-assistant.io/t/hassio-supervisor-not-starting/183869/7 issue.
Please review. I'm not a real developer :)
```
20-04-23 03:32:57 INFO (MainThread) [supervisor.discovery] Load 1 messages
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/src/supervisor/supervisor/__main__.py", line 47, in <module>
loop.run_until_complete(coresys.core.setup())
File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
File "/usr/src/supervisor/supervisor/core.py", line 77, …
```
> Ingress skip incorrect session

- supervisor/addons/addon.py
- supervisor/api/addons.py
- supervisor/hassos.py
Some improvements to docstrings and error messages. Added the add-on slug to some exceptions thrown, so it becomes more clear which add-on causes it.
> Docs string and exception message improvements

- supervisor/api/proxy.py
- supervisor/homeassistant.py
Avoid also log flooding because we restart Core.
90% of the code is for P2 and the other 10% for P1. Since we need anyway touch the code and change the logic. The P1 adds the 503 for API which makes this PR a lot simpler.
> Handle new API / Frontend early boot

- supervisor/utils/tar.py
With #1795 I've failed passing the `Path` object to recursive function calls.
Fixes #1800
> Recursive function call fix

- supervisor/addons/model.py
- supervisor/addons/validate.py
- tests/addons/test_config.py
If hardware support not an add-on i.e. node-red on Rpi1/zero, you can simply exclude it with:
```
"machine": ["!raspberrypi"]
```
> Support to exclude machine

- .github/workflows/ci.yaml
The cache restore of the venvs allowed for restoring cache from different Python versions. This is not good as the Python version itself is part of the venv.
This PR removes the cache key that allowed restoring a venv cache that doesn't match the Python version.
> Don't reuse venv cache when Python version changes

- supervisor/homeassistant.py
Creates `home-assistant-rollback.log` from `home-assistant.log` before rollback, so the reason for rollback is not lost
> Make a copy of the logfile before rollback

- requirements.txt
- supervisor/bootstrap.py
> Replace debuger with debugpy

- supervisor/api/security.py
> Allow all addons to access /host/info endpoint

- .github/workflows/sentry.yaml
Adds a GitHub Actions workflow for handling Sentry releases automatically.
> Add Sentry release GitHub Action workflow

- supervisor/addons/addon.py
- supervisor/api/utils.py
- supervisor/docker/__init__.py
- supervisor/utils/log_format.py
- tests/utils/test_log_format.py
With this change we can get something like this example shown in the UI:
Instead of "Unknown Error, see logs", which makes you check the SU logs (maybe, if you find them) that will show:
```
Can't start addon_core_ssh: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_ssh (e98012852d7261d79918b8fb64b21778a1c30b1374138616bf60eec0ee624d4c): Bind for 0.0.0.0:80 failed: port is already allocated")
```
> Format API error messages

- codecov.yaml
https://docs.codecov.io/docs/github-checks-beta#disabling-github-checks-patch-annotations
> Remove annotations

- supervisor/validate.py
- tests/test_validate.py
If no one provide an proof picture that IPv6 server address work inside hassio_dns container, we remove this feature because it would only lead in issues.
> Only support IPv4 for DNS

- supervisor/dbus/network/interface.py
- supervisor/dbus/payloads/interface_update.tmpl
- tests/dbus/payloads/test_interface_update_payload.py
On older versions of NM, if the `uuid` is not present it just generates a new one, which is not allowed.
currently tested with success on 1.22.10 and 1.14.6
blocks https://github.com/home-assistant/architecture/pull/431
fixes https://github.com/home-assistant/supervisor/issues/2068
> Add uuid to update payload

- supervisor/utils/log_format.py
- tests/utils/test_log_format.py
We have  2 bind error messages depending on how you start it, this change makes sure we handle both.
> Handle both cases of bind failures

- supervisor/addons/addon.py
- supervisor/api/utils.py
- supervisor/utils/__init__.py
- tests/utils/test_exception_helper.py
While working on #2099 I noticed that many operations would result in a blank error message returned to the CLI/API, this change extracts the message from the exception chain
> Extract exception message from chain for API errors

- requirements.txt
- supervisor/__main__.py
aiohttp 1.7.1 with native file send did not work anymore with uvloop. We don't really need uvloop, so let's remove it. It's a nice eventloop if you need to process a lot of connections, but for us, we have no downside to use the new c asyncio extension.
> Remove uvloop

- supervisor/docker/addon.py
This adds more logs when docker builds fails giving add-on devs a chance to see what's wrong with out building locally on their machine with docker.
In addition to the cryptic:
```
20-11-02 10:11:11 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build local/amd64-addon-sync:0.4: The command '/bin/ash -o pipefail -c apk add --no-cache jq==223' returned a non-zero code: 1
```
With this PR it adds the build log as well:
```
20-11-02 10:11:11 ERROR (SyncWorker_2) [supervisor.docker.addon] Build log: 
Step 1/12 : ARG BUILD_FROM
Step 2/12 : FROM $BUILD_FROM
---> b70ac30ea587
Step 3/12 : ENV LANG C.UTF-8
---> Using cache
---> 21a3a2cca551
Step 4/12 : RUN apk add --no-cache jq==223
---> Running in 661ea6b65db9
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz …
```
> Add the log stream from docker if build fails

- supervisor/__main__.py
- tests/test_main.py
Instead of using container timings to detect corruption on init/python/supervisor - we use a lock file mechanic which allows the OS to recreate the container/image without a false positive quote.
> Supervisor container startup health function

- supervisor/hassos.py
> Add process lock for update + fix timeout

- supervisor/host/network.py
```
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
reraise(*_capture_exception(hub))
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
raise value
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
response = await old_handle(self, request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl …
```
> Wifi mode old NM

- supervisor/api/__init__.py
- supervisor/api/auth.py
nginx has a convenient feature named [Authentication Based on Subrequest Result](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/) which allows to grant/deny access using basic authentication based on the result of a subrequest. That nginx module however only works with GET requests.
This Pull Requests allows users to provide auth credentials using Basic Auth in a GET request. This is convenient because it is then possible to use nginx to authenticate a third party app. Within the nginx server directive an add-on developer could use something like:
```
location = /.ha-auth {
internal;
proxy_pass              http://supervisor/auth;
proxy_pass_request_body off;
proxy_set_header        Content-Length "";
proxy_set_header …
```
> Allow GET method on /auth with BasicAuth

- supervisor/addons/validate.py
Small suggested change to add-on configurations; make the `boot` parameter optional and give it the default of `auto`.
It seems that most add-ons use this value, as `manual` is rare. Making it optional and setting the default to `auto` allows to clean up the add-on configurations a bit more.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/769
> Set a default for add-on boot config

- supervisor/dbus/__init__.py
- supervisor/dbus/const.py
- supervisor/dbus/logind.py
- supervisor/host/control.py
The Reboot() and PowerOff() methods of the systemd D-Bus API are not
meant to be called directly when logind is in use. Make sure to use the
logind APIs if available.
Since OS release 5.1 systemd-logind is enabled.
> Shutdown using systemd-logind if available

- supervisor/docker/homeassistant.py
Align the core container timeout with what the core container
uses as grace period.
Relates to https://github.com/home-assistant/core/pull/45029.
> Increases core container timeout to match core shutdown time

- supervisor/addons/validate.py
Set a default for the add-on `startup` configuration, making the configuration parameter optional.
The default is set to `application`. Looking at the add-ons, most use `service`, however, I think `application` is a sane and safe default. Add-ons that have a more specific startup requirement can still use this option of course.
This PR allows cleaning up add-on configurations a bit more and is backward compatible.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/770 …
> Set a default for add-on startup config

- supervisor/addons/validate.py
It is always nice if an add-on doesn't need any options (and thus might not have a schema).
This PR adds a default empty dictionaries to the `schema` and `options` configuration parameters of an add-on configuration, mainly for cleaner add-on configurations.
For a future improvement, it would be nice if we could expose if the add-on has options (and thus a schema) and hide the config from the UI based on that.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/771 …
> Set a default for add-on options and schema config

- requirements.txt
- supervisor/docker/addon.py
- supervisor/docker/audio.py
- supervisor/docker/cli.py
- supervisor/docker/dns.py
- supervisor/docker/homeassistant.py
- supervisor/docker/multicast.py
- supervisor/docker/observer.py
- supervisor/docker/supervisor.py
- supervisor/hassos.py
Follow up of: https://github.com/ludeeus/awesomeversion/pull/28
- This PR fixes or closes issue: fixes #2442
> Fix issues with awesomeversion and representation

- supervisor/hardware/monitor.py
We used from old days the old depricated callback handler. This is now migrated. Also it fix the error:
```
OSError: Error while polling fd: 24
File "pyudev/monitor.py", line 531, in run
for device in iter(read_device, None):
File "pyudev/_util.py", line 159, in eintr_retry_call
return func(*args, **kwargs)
File "pyudev/monitor.py", line 354, in poll
if eintr_retry_call(poll.Poll.for_events((self, 'r')).poll, timeout):
File "pyudev/_util.py", line 159, in eintr_retry_call
return func(*args, **kwargs)
File "pyudev/_os/poll.py", line 94, in poll
return list(
File "pyudev/_os/poll.py", line 110, in _parse_events
raise IOError('Error while polling fd: {0!r}'.format(fd))
```
We increase the buffer. Just for the records, other systems like systemd use default 128mb
- This PR fixes or closes …
> Udev - move away form depricated callback / increase buffer

- supervisor/api/__init__.py
- supervisor/api/addons.py
- supervisor/api/security.py
It's more something for the future. I want that bashio get/cache the config from an endpoint instead to deal with a written file to a bind mount.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/794
> Add API endpoint for add-on for his own config

- supervisor/addons/addon.py
- supervisor/addons/validate.py
This PR add support for a static port configuration to the Watchdog URL add-on configuration.
Currently, it requires a defined port (while this should not be needed in most cases).
Fixes: <https://github.com/hassio-addons/addon-zwavejs2mqtt/pull/49>
```
21-02-19 14:01:41 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/40817795/zwavejs2mqtt/config.json: does not match regular expression for dictionary value @ data['watchdog']. Got 'http://[HOST]:8099/health/zwave'
``` …
> Allow for static port in Watchdog add-on configuration

- supervisor/homeassistant/api.py
> Fix landingpage on check_api_state

- supervisor/docker/__init__.py
- supervisor/docker/addon.py
- supervisor/docker/audio.py
* Fix path of cpu.rt_runtime_us sysfs file
Fix detection of CPU bandwidth allocation (CONFIG_RT_GROUP_SCHED) option
by checking the correct file location.
* Set priority limit and memory lock limit
Set a soft limit of real-time priority 90 and hard limit of 99. The
maximum is 99, to avoid add-ons using such a high priority without
second thought set the soft limit to 90. This allows a process to higher
the limit to 99, if really required.
Also set max locked memory to 128MB. Locking memory from getting paged
out is often used for the real-time process/thread to avoid delays due
to swapping/pageing in. Ideally a real-time process should only do the
real-time job, hence not need too much memory.
- Link to documentation …
> Real-time fixes

- supervisor/const.py
- supervisor/docker/addon.py
- supervisor/docker/audio.py
Adjust realtime CPU runtime allocation to support multiple
add-ons/plug-ins with the runtime flag set.
The cpu.rt_runtime_us allocation is somewhat special as it
allocates the guaranteed runtime. Hence we cannot simply allocate all
time to each add-on.
Unfortunately we cannot distribute the CPU time equally based on the
number of add-ons as we don't know the number of add-ons which will use
realtime ahead of time. Also adjusting at runtime is currenlty not
supported by the Docker Python SDK (the underlying http API does
however, so this would be a possible future improvement).
This solution distributes the total available time of 950ms to up to 5
add-ons/plug-ins in equal slices. On a quad-core system this allows up
to 760ms CPU time in the real-time scheduler per 1s (76% of one CPU) …
> Adjust CPU runtime allocation to support multiple add-ons

- supervisor/api/__init__.py
- tests/api/test_resolution.py
Reverts home-assistant/supervisor#2714
This API call makes no sense. It remembers me why we did that differently on others. Now we can also not run the check manually.
More details: https://github.com/home-assistant/cli/pull/280
> Revert "Tweak check API path"

- supervisor/const.py
- supervisor/docker/addon.py
- tests/docker/test_addon.py
Recently the `journald` option for add-ons was added, however, this doesn't work in all cases.
For Debian, the Storage is by default set to `auto`, which means, it will only write to the persistent storage location, if it exists (`/var/logs/journal`).
Right now, the Supervisor assumes the folder always exist, causing it not to work when the folder is missing. This PR adds a check that mimics the behavior of the journal service by checking if the persistent location exists, if not, it will fall back to the volatile location (`/run/log/journal`). The volatile location exists, as it is created if missing.
See: <https://www.freedesktop.org/software/systemd/man/journald.conf.html#Storage=>
This PR mounts either location consistently in the same location within the add-on, to ensure the use of …
> Fix journald add-on option to work with default Debian

- supervisor/addons/options.py
- tests/addons/test_options.py
During a [review of a change](https://github.com/home-assistant/addons/pull/1941#pullrequestreview-620834679) to the MariaDB addon, it was raised that it should be possible to make an array config option in an add-on truly optional. Currently if you define the schema of a config as `["str?"]` then the option itself must be present to pass validation, even if its just `[]`. This makes it so if the element inside is optional then the entire config option is optional.
Given an addon with this schema:
```json
{
"schema": {
"log_level": "str",
"privileges": ["list(x|y|z)?"]
}
}
```
This configuration was invalid prior to this PR. Now it is valid:
```yaml
log_level: info
``` …
> Allow optional array configs

- supervisor/docker/addon.py
- tests/docker/test_addon.py
The volume & bind location was swapped for the Add-on journald support.
Both persistent and volatile locations should be mapped consistently to the persistent location inside the add-on.
> Fix swapped volume/bind variables in Journald volume support

- supervisor/docker/addon.py
- tests/docker/test_addon.py
As Pascal pointed out, current journald mapping won't work, as the file exists checks are done inside the Supervisor container.
This PR changes the behavior by binding both the volatile and persistent journald storage.
> Map both persistent and volatile journald logs

- supervisor/host/network.py
Fixed bug in host network info collector (Issue #2779)
- This PR fixes or closes issue: fixes #2779 
- This PR is related to issue: #2779 
> Fix for bug in host network info collector

- supervisor/plugins/observer.py
Probably related to https://github.com/home-assistant/plugin-observer/issues/22
Sometimes i notice my supervisor logs shows a random : 
`WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Application found a problem with observer plugin!`
i believe the cause to be related to the timeout being too short on a "busy" system, thus my proposal to relax it to 10 seconds.
https://github.com/home-assistant/plugin-observer/issues/22
> Relax check_system_runtime timeout to 10 seconds

- .github/workflows/builder.yml
- scripts/supervisor.sh
- supervisor/docker/addon.py
Docker reports:
Sep 23 08:16:31 homeassistant dockerd[467]: time="2021-09-23T08:16:31.771717436Z" level=warning msg="Security options with `:` as a separator are deprecated and will be completely unsupported in 17.04, use `=` instead."
Since it seems that Docker supports `=` since quite a while, we should
use `=` only.
> Use `=` instead of deprecated `:` as security option separator

- supervisor/api/homeassistant.py
- supervisor/homeassistant/module.py
The documentation says that passing null to `image` allows to clear
the option. Currently `null` is not allowed leading to:
Error: expected string or buffer for dictionary value @ data['image']. Got None
While at it, also update type annotation to reflect what the API
currently allows.
- Link to documentation pull request: somewhat related: https://github.com/home-assistant/developers.home-assistant/pull/1146
> Allow to clear explicit image name

- supervisor/hardware/data.py
- supervisor/store/__init__.py
Create task before using `asyncio.wait()` to avoid deprecation warnings such as 
```
tests/store/test_custom_repository.py: 5 warnings
/workspaces/supervisor/supervisor/store/__init__.py:113: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
await asyncio.wait(tasks)
```
Change the if statement to avoid property access and the deprecation warning. The if statement currently causes access of a property of udevice.parent, leading to:
```
tests/hardware/test_module.py: 104 warnings
/workspaces/supervisor/supervisor/hardware/data.py:50: DeprecationWarning: Will be removed in 1.0. Access properties with Device.properties.
```
- This PR is related to …
> Address pytest warnings

- supervisor/homeassistant/websocket.py
Avoid sending backup start notification to Home Assistant Core 2021.12. The implementation in 2021.12 has a bug when non-SQLite databases are used. The bug is scheduled to be fixed in 2022.2 (see https://github.com/home-assistant/core/pull/63847/).
> Avoid sending backup start notification to HA Core 2021.12

- supervisor/bus.py
- supervisor/docker/addon.py
- tests/test_bus.py
- This PR fixes or closes issue: fixes #2690
> Support dynamic device access cgroup

- supervisor/resolution/evaluations/operating_system.py
> Remove Debian buster from supported OS

- supervisor/docker/cli.py
The CLI plug-in stays up even without command. This saves a few
kilobytes of RAM.
It also allows s6-overlay's stage2 to complete. The stage2 execlineb
process has an enormously long cmdline, with strings like "init-stage2
failed" in it. [This has previously led people to believe that there is a
problem](https://community.home-assistant.io/t/docker-init-stage2-failed/399975) (while there isn't). So as a side effect, getting stage2 to
complete side steps such confusion and makes the list of processes
cleaner. …
> Drop unnecessary command from CLI plug-in

- supervisor/dbus/network/setting/__init__.py
- supervisor/dbus/network/setting/generate.py
- tests/dbus/network/setting/test_init.py
#3570 had an unexpected side effect. It appears the response of get settings included the deprecated [addresses property](https://developer-old.gnome.org/NetworkManager/stable/settings-ipv4.html). This field was used before `address-data`, `gateway` and `dns` were split out. So when provided it wins over those.
The reason it went unnoticed is because if you have already set network settings then it fails silently, accepting the input but actually keeping the same value. Which is only noticeable if you try and change interface config (not a common task after initially setting it). It clearly breaks for users without existing network config.
- This PR fixes or closes issue: fixes #3610 
If API …
> Don't include addresses in network update

- supervisor/api/network.py
Don't assume network interface names are always lower case. It seems
that they can have an upper case letter, and capitalization matters.
- This PR fixes or closes issue: fixes #3645
> Respect capitialization of network interfaces

- supervisor/host/network.py
- tests/host/test_network.py
If the IPv4 and IPv6 methods are disabled for an enabled interface, do not push an update to the interface at startup. This can be caused a connectivity or DHCP issue at startup and then Supervisor will make this small issue a big one by permanently disabling the interface. After that the user can only fix it by connecting a monitor and keyboard after connectivity has been re-established.
Plus if an interface actually has both interfaces disabled then it really doesn't matter if its defaults are up to date.
It's not obvious how this breaks so here is what I was doing to reproduce this 100% of the time:
1) Have a fully functional, network connected HAOS system with ipv4 or ipv6 method set to `auto`
2) Shut it down
3) While shut down, turn off the DHCP server in the network it will connect …
> Never disable interfaces at startup

- supervisor/docker/__init__.py
We should update min requirements to 20.10.0 of docker. Anyway this make it more stable between versions.
> Docker info more robust

- supervisor/addons/__init__.py
- tests/addons/test_addon.py
Freshly installed addons did not start their event listener and so were always unknown.
> Fix addons always unknown after install

- supervisor/api/__init__.py
- supervisor/api/store.py
- tests/api/test_addons.py
ZWaveJS requires that `/addons/{addon}/info` response includes `state` and `options` or it will break on old versions. Adding those fields back in the legacy routing path only to support this.
> Add fields back for legacy addons info routing

- supervisor/addons/build.py
- supervisor/addons/validate.py
- tests/addons/test_build.py
- tests/addons/test_config.py
- tests/fixtures/build-config-manifest.json
Since we support manifests now for add-on images, this PR set in motion to use a single base image for all architectures using a manifest, by allowing `build_from` to be a string (instead of mapping for each architecture).
So instead of doing this:
```yaml
build_from:
aarch64: ghcr.io/hassio-addons/base:12.2.0
amd64: ghcr.io/hassio-addons/base:12.2.0
armhf: ghcr.io/hassio-addons/base:12.2.0
armv7: ghcr.io/hassio-addons/base:12.2.0
i386: ghcr.io/hassio-addons/base:12.2.0
```
This PR will also allow for this:
```yaml
build_from: ghcr.io/hassio-addons/base:12.2.0
```
Needs: …
> Support for Docker manifests base images add-on build

- supervisor/misc/tasks.py
- supervisor/store/__init__.py
- tests/store/test_custom_repository.py
- tests/store/test_store_manager.py
New versions of supervisor may add config options for addons and addon repositories and updated addons/repos may use them immediately. Therefore its not safe to even check for addon updates or add new repositories while supervisor is out of date.
> Supervisor updated before addon repositories

- supervisor/dbus/network/setting/generate.py
- tests/dbus/network/setting/test_init.py
There was an issue reported [in discord](https://discord.com/channels/330944238910963714/361377176379195393/1007374190518734948) as well as #3730 where `autoconnect` was being set to `false` in the config for the interface. 
As I responded in that now closed issue I am really not sure how this could occur. Supervisor does not touch this field when updating an interface currently. HAOS [does not set it](https://github.com/home-assistant/operating-system/blob/dev/buildroot-external/rootfs-overlay/etc/NetworkManager/NetworkManager.conf) and neither does the [supervised installer](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/etc/NetworkManager/NetworkManager.conf). I also can say this field does not have a value on any of my HAOS systems. Yet it …
> Set autoreconnect to true for interfaces

- supervisor/addons/addon.py
- supervisor/hardware/helper.py
- tests/addons/test_addon.py
Our S6 V3 migration guide missed a step. Legacy services now also must set the exit code of the container as described here: https://github.com/just-containers/s6-overlay/commit/2fbf5ce27264c7e355729794fa2404c8bc4a6f30 . Otherwise the exit code of the container is always set to success.
Watchdog now looks at the exit code of the container and assumes addons were supposed to stop if the exit code was 0. It appears this is incorrect a lot currently. We should fix our addons and change the example finish script but in my opinion supervisor now needs to handle this. As it was our miss, its been a while since we announced the S6 V3 change and its backwards incompatible with how watchdog used to work (it had special treatment for user calling "stop").
In addition I am treating reboot as a …
> Watchdog restarts addons on successful but unexpected exits

- supervisor/dbus/network/setting/__init__.py
- tests/dbus/network/setting/test_init.py
When trying to reproduce issues caused by DHCP being unavailable I noticed that when some settings were being unintentionally kept when switching from `method: static` to `method: auto`. My network configuration still seemed to have `addresses`, `dns` and `gateway` filled in even though those don't make sense with `method: auto`. Usually it was silently incorrect but with ipv6 sometimes I got an error from Network Manager.
This is caused by the settings merge. Adjusted to ensure we don't merge fields that Supervisor controls, only the ones it doesn't understand. …
> Remove static-only fields when method is auto

- supervisor/store/__init__.py
- tests/store/test_custom_repository.py
`add_repository` is also called to load existing repository information back into memory on startup. Therefore it cannot be wrapped in a job condition else we get nonsense failures on startup if supervisor is out of date or has no internet. We only need to require those things to actually add a new repository.
Note that this change does leave two small edge cases where the user could get validation errors:
1) On startup if supervisor finds the folder for a repo is gone it will clone it. If supervisor is out of date this new clone may be invalid for current supervisor. Since we have no clone to fall back on there's not really a better option.
2) Restore of a backup may include a repo we don't have a clone for. Can cause same problems as above if supervisor is out of date. We may want to …
> Store load ignores supervisor updated condition

- supervisor/backups/backup.py
As per commit 80e67b3 we're supporting a compressed flag on backups to
define whether a tar archive should be fully compressed or not, but
while we respect this for all the addons and folders we don't do it for
the actual homeassistant archive, that is always compressed despite the
passed flag.
Fix this by applying the same logic to the homeassistant archive too.
- This PR fixes or closes issue: fixes #3838
> supervisor/backup: Ensure compressed flag is respected by homeassistant

- supervisor/const.py
- supervisor/homeassistant/const.py
- supervisor/homeassistant/websocket.py
- supervisor/resolution/const.py
- supervisor/resolution/module.py
- tests/resolution/test_resolution_manager.py
Follow up to #3818 - the events need to be on HA's bus, not supervisor's. HA isn't listening to supervisor's event bus, supervisor fires events of type `supervisor/event` when HA needs to know about it.
> Fire issue events on HA's bus

- tests/api/test_network.py
- tests/host/test_network.py
I recently realized the dbus fixture returns a list of dbus commands. Checking this list to see what dbus commands have been run is a much better approach then monkeypatching `call_dbus` and checking its args. I fixed most in #3854 , here's a couple I missed.
> Reduce patching call dbus in tests

- supervisor/dbus/interface.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/network/connection.py
- supervisor/dbus/network/interface.py
- supervisor/dbus/network/setting/__init__.py
- supervisor/dbus/network/wireless.py
- tests/dbus/network/test_connection.py
- tests/dbus/network/test_interface.py
- tests/dbus/network/test_network_manager.py
- tests/dbus/network/test_wireless.py
Supercedes #3890 
Network Manager has many sub-objects that go in and out of existence as things change. After #3872 this poses a problem because we create signal listeners for almost every proxy interface we connect to a dbus object. The `__del__` code was an attempt to keep that under control without putting explicit disconnects everywhere.
This doesn't really work though. Since dbus-next keeps a list of callbacks and those callbacks point to our dbus objects. So removing this and instead whenever we replace a connected object in an NM object we do an explicit disconnect on the old one. These disconnects of old objects are being done in the executor because the result shouldn't impact connecting to and updating the current NM objects.
Also wrapped …
> Replace __del__ with explicit disconnect

- .github/workflows/builder.yml
- supervisor/addons/__init__.py
- supervisor/addons/addon.py
- tests/addons/test_addon.py
When restore installed an addon we weren't calling `load` on the new `Addon` object. This meant the docker events monitor was never attached. Corrected that. Also it looks like listeners weren't being unattached on addon uninstall, corrected that as well.
To test, modified the `Run the Supervisor` workflow to check that supervisor says the addon is running. This serves as a test for this and also should help us identify some of the recent issues around the state in the API being off in advance. …
> Attach event monitor after addon restore

- supervisor/dbus/interface.py
- supervisor/utils/dbus.py
- tests/fixtures/test_no_properties_interface.xml
- tests/utils/test_dbus.py
It seems we get back some bad introspections that don't include `org.freedesktop.DBus.Properties` from devices within NetworkManager. After the latest DBus changes this causes a `KeyError` rather then a `DBusInterfaceMethod` error.
Based on this it appears this is expected, we just need to return to raising the correct type of exception:
https://github.com/home-assistant/supervisor/blob/ff462ae9765157c8d74db724b26baa6b7f08744c/supervisor/dbus/network/__init__.py#L182-L187 …
> Bad introspection causes DBus error not KeyError

- supervisor/dbus/agent/__init__.py
- supervisor/dbus/interface.py
- supervisor/dbus/manager.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/network/connection.py
- supervisor/dbus/network/interface.py
- supervisor/dbus/network/setting/__init__.py
- supervisor/dbus/network/wireless.py
- supervisor/dbus/utils.py
- supervisor/utils/dbus.py
- tests/dbus/test_interface.py
Not threadsafe to disconnect in executor. Latest version of dbus-fast exposed the race condition this can cause since it makes a call to dbus to remove the match rule.
After reviewing Dbus-fast code around unattaching signal listeners I am pretty sure it doesn't raise any errors. To be safe though, ensuring we don't raise any exceptions while unattaching signal listeners during disconnect. As all the spots we call disconnect from don't want to see errors from it, we just want them logged if they occur.
After further review with @bdraco , the other issue occurring is callbacks for signals can be pending at the time we disconnect dbus objects. This raises `DBusNotConnectedErrors` when the callbacks try to run. To fix this we're separating `shutdown` and `disconnect`.
Shutdown is an …
> Don't disconnect in executor

- supervisor/addons/addon.py
- tests/addons/test_addon.py
Initialize of manual stop needs to be inverted. It should be the opposite of the logic from here:
https://github.com/home-assistant/supervisor/blob/48e666e1fc53ae13b325b7575abec67e901fb5eb/supervisor/core.py#L206-L208
Because supervisor restart is not considered a manual stop of an addon, host reboot is.
> Manual stop true after a reboot

- supervisor/dbus/interface.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/network/setting/generate.py
- supervisor/utils/dbus.py
- tests/conftest.py
- tests/dbus/network/test_network_manager.py
- tests/dbus/test_interface.py
- tests/utils/test_dbus.py
Veth interfaces are recreated a lot, particular when docker is having problems. This can create big problems now that we listen for property change signals. Since we must make a dbus call to find out an interface is a veth (which can flood the network) and they often just fail since the veth already vanished (which floods the log with noise). That results in issues like #3919
Changing a few things to address this:
1. If the introspection is missing the `org.freedesktop.DBus.Properties` interface for a dbus object we're expecting to be able to get properties for, raise `DBusInterfaceError` and disconnect. We found something unusable, the dbus object is probably gone.
2. If network manager finds an unusable device log that at debug level rather then warning. It could be useful info for …
> Ignore veth changes

- supervisor/addons/addon.py
- supervisor/docker/addon.py
- tests/addons/test_manager.py
- tests/fixtures/addon-config-add-image.json
- tests/fixtures/addon-config-remove-image.json
When an addon is updated `need_build` is determined by looking at the current config of the addon. Which means if the `image` was added or removed as part of the update it doesn't work.
If the image was added in the update you get #3414 (we build an image and then fail on run). If the image was removed in the update then the image pull most likely fails since the author probably didn't publish it with the new version (no issue for this currently but it is a bug).
Fixes it by looking at the store config during update to determine if we need to build an image or not.
- This PR fixes or closes issue: fixes #3414 …
> Fix addon image changed on update

- supervisor/dbus/rauc.py
After dbus-fast update to 1.73.0:
```
Nov 14 18:54:13 homeassistant hassio_supervisor[470]: 22-11-14 12:54:13 INFO (MainThread) [__main__] Running Supervisor
Nov 14 18:54:13 homeassistant hassio_supervisor[470]: TypeError: Expected unicode, got RaucState
Nov 14 18:54:13 homeassistant hassio_supervisor[470]: Exception ignored in: 'dbus_fast._private.marshaller.Marshaller._write_single'
Nov 14 18:54:13 homeassistant hassio_supervisor[470]: Traceback (most recent call last):
Nov 14 18:54:13 homeassistant hassio_supervisor[470]:   File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 103, in buffer_message
Nov 14 18:54:13 homeassistant hassio_supervisor[470]:     msg._marshall(self.negotiate_unix_fd),
Nov 14 18:54:13 homeassistant hassio_supervisor[470]: TypeError: …
```
> Call dbus with string value not enum

- supervisor/api/ingress.py
aiohttp adds a Content-Type header by default, as well as other headers.
This may usually be convenient, but it breaks APIs that explicitly ask for no content type header, for instance on post requests with an empty body.
Since ingress is proxying the requests from the browser to the add-on, it should avoid modifying them.
I only skip this header auto generation because it actually breaks the Adguard add-on.
- This PR fixes or closes issue:
- https://github.com/hassio-addons/addon-adguard-home/issues/359
- (possibly) https://github.com/home-assistant/core/issues/80639 …
> Do not let aiohttp add a Content-Type header

- supervisor/addons/__init__.py
- supervisor/addons/model.py
- tests/common.py
- tests/store/test_store_manager.py
When an addon is unavailable for the current system, the message is always the same:
> Add-on {slug} not supported on this platform
This is ok if the reason is the addon doesn't support the architecture or machine type the user is running. It would be nice if it said which was the issue but there's nothing they can do about that.
However its not ok if the reason is it requires a newer version of Home Assistant. The message doesn't say that at all and the user can fix that by updating.
Changed the message to say why it is unavailable. Also test ensures a partial backup is not taken when the user cannot update to the next version of the addon because it is unavailable, per https://github.com/home-assistant/core/pull/84943
- This PR is related to …
> Clarify message when addon unavailable

- supervisor/utils/apparmor.py
- 'Too many' is misleading if there are no profiles. (Which can happen if a person actively developing an add-on has forgotten to explicitly disable AppArmor using `apparmor: false`.)
- profiles just returns set() -- using profile_file should be more correct.
Sorry if this change comes across as "rushed" -- I've been trying to develop my own add-on and this issue resulted in an exhausting time sink.
- This PR fixes or closes issue: N/A
- This PR is related to issue: https://github.com/home-assistant/addons/issues/1850 (unrelated, but only place where the error was brought up)
- Link to documentation pull request: N/A
- Link to cli pull request: N/A
[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist …
> Fix AppArmor name-related exceptions

- supervisor/store/git.py
- supervisor/utils/codenotary.py
- tests/store/test_repository_git.py
- tests/utils/test_codenotary.py
Catch and handle UnicodeDecodeError from git and code notary modules. So we don't bubble that up and break setup. Fixes the following from sentry:
- https://sentry.io/organizations/home-assistant-io/issues/2471308411/?project=5370612
- https://sentry.io/organizations/home-assistant-io/issues/3673140086/?project=5370612
- https://sentry.io/organizations/home-assistant-io/issues/3673142729/?project=5370612
Additionally noticed that sometimes a decode error when pumping stderr causes the git library to throw `CommandError` instead of `GitCommandError` (which we weren't catching). Since `GitCommandError` inherits from `CommandError` I made that except broader to handle this. Fixes this from sentry:
- https://sentry.io/organizations/home-assistant-io/issues/3723051227/?project=5370612
- This …
> Handle UnicodeDecodeError

- .github/workflows/ci.yaml
- setup.cfg
- supervisor/resolution/validate.py
- tests/common.py
- tests/conftest.py
- tests/dbus/test_hostname.py
- tests/dbus/test_login.py
- tests/dbus/test_rauc.py
- tests/dbus/test_resolved.py
- tests/dbus/test_systemd.py
- tests/dbus/test_timedate.py
- tests/dbus_service_mocks/__init__.py
- tests/dbus_service_mocks/base.py
- tests/dbus_service_mocks/hostname.py
- tests/dbus_service_mocks/logind.py
- tests/dbus_service_mocks/rauc.py
- tests/dbus_service_mocks/resolved.py
- tests/dbus_service_mocks/systemd.py
- tests/dbus_service_mocks/timedate.py
Recently we've had several events where a supervisor update had catastrophic failures despite CI passing. The reason in each case was because we don't actually use dbus in our unit tests. Instead we mock all calls to dbus and return fixtures based on naming patterns.
This setup has a few problems:
1. DBus responses aren't actually JSON-compliant. Specifically dbus has a `byte` type and can return tuples in addition to arrays, neither of which can be represented in JSON. This forces us to do things like [this](https://github.com/home-assistant/supervisor/blob/165af46f54b6f592bbd144417012bf72370c9a60/tests/conftest.py#L123-L142) or [this](https://github.com/home-assistant/supervisor/blob/165af46f54b6f592bbd144417012bf72370c9a60/tests/dbus/test_resolved.py#L30-L49) to post-process fixtures …
> Mock services on session dbus in tests

- supervisor/addons/const.py
- supervisor/addons/validate.py
- supervisor/api/middleware/security.py
- tests/addons/test_config.py
Addon slugs currently have no validation on what can and cannot be in the string. This is a problem because
1. it shouldn't be that open-ended
1. the slug is in URLs so it needs to be URL safe
I went to our [addons analytics](https://analytics.home-assistant.io/addons.json) and came up with a regex that restricts slugs to what will work where we need it to without breaking backwards compatibility for any of the known addons.
It's mostly what you would expect (`-_a-z0-9`). Although turns out some addons used upper case letters and periods. Those probably wouldn't be included if this regex had existed from the beginning. Since it didn't and they are url safe better to include them and keep backwards compatibility.
- …
> Improve addon slug validation

- supervisor/dbus/agent/datadisk.py
- supervisor/dbus/interface.py
- supervisor/dbus/udisks2/__init__.py
- supervisor/dbus/udisks2/block.py
- supervisor/dbus/udisks2/data.py
- supervisor/dbus/udisks2/partition_table.py
- supervisor/os/data_disk.py
- supervisor/utils/dbus.py
- tests/conftest.py
- tests/dbus/agent/test_datadisk.py
- tests/dbus/network/test_network_manager.py
- tests/dbus/test_interface.py
- tests/dbus/udisks2/test_block.py
- tests/dbus/udisks2/test_manager.py
- tests/dbus/udisks2/test_partition_table.py
- tests/dbus_service_mocks/agent_datadisk.py
- tests/dbus_service_mocks/udisks2_partition_table.py
- tests/os/test_data_disk.py
- tests/utils/test_dbus.py
On a migrate data disk request, supervisor formats the new drive using UDisks2 instead of OS Agent. It then uses the new MarkDataMove DBus API to tell OS Agent to do a migration to the already prepped drive next reboot. This significantly improves error handling since supervisor can see what went wrong and tell the user, instead of asking them to look in the host log.
> Format data disk in Supervisor instead of OS Agent

- supervisor/dbus/udisks2/__init__.py
- supervisor/dbus/udisks2/filesystem.py
- supervisor/os/const.py
- supervisor/os/data_disk.py
- supervisor/resolution/checks/multiple_data_disks.py
- supervisor/resolution/const.py
- supervisor/resolution/fixups/system_rename_data_disk.py
- tests/dbus/udisks2/test_block.py
- tests/dbus/udisks2/test_filesystem.py
- tests/dbus/udisks2/test_manager.py
- tests/dbus_service_mocks/udisks2_block.py
- tests/dbus_service_mocks/udisks2_manager.py
- tests/resolution/check/test_check_multiple_data_disks.py
- tests/resolution/fixup/test_system_rename_data_disk.py
Create an issue when supervisor detects that a filesystem has the name `hassos-data` which is not the current device according to OS Agent. That also comes with a suggestion which when executed renames that filesystem to `hassos-data-old` to prevent a race condition at startup.
This should be all that is required to make a repair for this situation from supervisor's side. Since all issues and associated suggestions are pushed to core already via dispatcher. The follow-up is to modify the hassio component so it doesn't ignore this type of issue and instead makes a repair out of it, like was done for unsupported and unhealthy.
If API endpoints of add-on …
> Create issue for multiple data disks detected

- supervisor/addons/utils.py
- supervisor/docker/const.py
Add support for setting the `NET_RAW` capability.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/1749
> Add support for NET_RAW privileges

- supervisor/exceptions.py
- supervisor/mounts/manager.py
- supervisor/mounts/mount.py
- tests/api/test_mounts.py
- tests/backups/test_manager.py
- tests/mounts/test_manager.py
- tests/mounts/test_mount.py
Follow up to #4269, `bind` is not a type for mount. There is no type and you say `bind` as an option, this does bind mounts correctly.
In addition when we fail to mount on create, keep the new mount out of the list of mounts. Rather then adding it as a failure. Also try to remove the systemd unit first if it was created so the user doesn't get a confusing error when they retry.
> Fix bind mounting and remove on create failure

- supervisor/api/__init__.py
- supervisor/api/backups.py
- supervisor/api/mounts.py
- supervisor/backups/manager.py
- supervisor/misc/tasks.py
- supervisor/mounts/const.py
- supervisor/mounts/manager.py
- supervisor/mounts/mount.py
- supervisor/resolution/module.py
- supervisor/utils/sentinel.py
- tests/api/test_backups.py
- tests/api/test_mounts.py
- tests/backups/test_manager.py
- tests/conftest.py
- tests/mounts/test_manager.py
- tests/mounts/test_mount.py
Add support for backup mounts. Users can make backups to them and backups are listed from them. One backup mount can also be marked as default and all backups will be made there unless a location is otherwise specified. If a backup mount is added and there is no default it will automatically be set as the default.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/1777
- Link to cli pull request: https://github.com/home-assistant/cli/pull/399
> Use backup mounts

- supervisor/addons/utils.py
- supervisor/docker/const.py
Add support for setting the CAP_BPF and CAP_PERFMON capabilities.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/1759
> Add support for CAP_BPF and CAP_PERFMON privileges

- supervisor/backups/manager.py
- supervisor/mounts/mount.py
- tests/backups/test_manager.py
- tests/mounts/test_manager.py
- tests/mounts/test_mount.py
NFS mounts behave differently then CIFS mounts. Operations never timeout by default. Which means right now when supervisor is asked to do operations on a backup NFS mount and its down it simply hangs. Changing to use `soft` and a reasonable timeout for NFS mounts to prevent this.
Additionally during this I noticed that the following sequence causes a setup failure:
1. Make a working backup mount
2. Take it offline
3. Restart supervisor
Supervisor then adopts the existing systemd unit which things the mount is active. Backup manager tries to list files from it and gets a timeout error, failing setup. Fixing this so if backup manager cannot list files in a particular backup location it simply logs and ignores it.
- Link …
> Improve handling of NFS mounts and backup manager errors

- supervisor/backups/manager.py
- tests/backups/test_manager.py
https://github.com/home-assistant/supervisor/pull/4323 did not fix the setup failures from backup manager. The `OSError` is only thrown once you ask the generator from `glob` for a value, not on creation of the generator. Added an `is_dir` call to do a `stat` which raises on mount down.
> Protect backup manager from setup failures for mount down

- supervisor/docker/addon.py
- supervisor/docker/homeassistant.py
- supervisor/resolution/checks/docker_config.py
- tests/docker/test_addon.py
Change the mount propagation mode from SLAVE to RSLAVE in case of /media and /share
This should address the current  mounting blocker error at: https://github.com/home-assistant/supervisor/issues/4366
- This PR fixes or closes issue: fixes https://github.com/home-assistant/supervisor/issues/4366
> Fix propagation mode of mounts to allow Ha-Core to start

- supervisor/mounts/mount.py
- tests/mounts/test_manager.py
- tests/mounts/test_mount.py
The default for cifs mounts is to use inodes from the server when possible (not always possible, in which case it falls back to generating inodes on the client). This is a problematic default because sometimes it creates issues like https://github.com/home-assistant/operating-system/issues/2585 . The benefit (being able to easily distinguish hardlinks) doesn't seem worth the risk.
Changing to always use client generated inodes as that should fix the stale file handle issue without really any downside to other users.
- This PR fixes or closes issue: fixes https://github.com/home-assistant/operating-system/issues/2585 …
> Use noserverino option in cifs mounts

- supervisor/addons/addon.py
- tests/addons/test_addon.py
Addon.start was returning `None` if the addon was already running and callers expected it to always return a awaitable they could use to wait on it being started. Addon.start should always return coroutine callers can use to wait on it being ready and available, even if the addon has previously been started (might not be healthy yet).
- This PR is related to issue: https://home-assistant-io.sentry.io/issues/4270085037/events/5ae137c2b30c432292b5e7441800ef2f/
> Ensure addon.start always returns coroutine

- supervisor/const.py
- supervisor/core.py
- supervisor/homeassistant/module.py
- supervisor/homeassistant/websocket.py
- tests/homeassistant/test_module.py
- tests/homeassistant/test_websocket.py
Currently users see this a lot in core:
```
Logger: homeassistant.components.hassio.issues
Source: components/hassio/issues.py:312
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 17:31:34 (1 occurrences)
Last logged: 17:31:34
Failed to update supervisor issues: HassioAPIError('System is not ready with state: setup')
```
This is because when the hassio integration sees a message with type `supervisor_update` and key `supervisor` it assumes supervisor has just finished startup and asks for issues. The problem is we actually fire this message twice:
https://github.com/home-assistant/supervisor/blob/48e9e1c4f94cf89d3f2dbbebe93de7d5744fb6ae/supervisor/core.py#L269
https://github.com/home-assistant/supervisor/blob/48e9e1c4f94cf89d3f2dbbebe93de7d5744fb6ae/supervisor …
> Separate startup event from update check event

- supervisor/api/network.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/network/configuration.py
- supervisor/dbus/network/interface.py
- supervisor/dbus/network/setting/__init__.py
- supervisor/dbus/network/setting/generate.py
- supervisor/exceptions.py
- supervisor/host/configuration.py
- supervisor/host/network.py
- supervisor/resolution/checks/network_interface_ipv4.py
- tests/api/test_network.py
- tests/dbus/network/setting/test_generate.py
- tests/dbus/network/setting/test_init.py
- tests/dbus/network/test_connection.py
- tests/dbus/network/test_interface.py
- tests/dbus/network/test_network_manager.py
- tests/dbus/network/test_wireless.py
- tests/host/test_network.py
Currently we rely on network interface name to identify devices and tie them to config. This is problematic because they can change. And regularly do on some supported systems.
This PR ties the config to the mac address of the device instead of the name as that is far less likely to change. We believe it is unchanging for the boards we support currently although an operating system fix is possible if we do add support for a board where it can change.
This PR is backwards compatible API-wise. It adds support for updating a network interface identified by mac address but still allows clients to identify the one to update by name as well.
- This PR fixes or closes issue: fixes https://github.com/home-assistant/operating-system/issues/2174
- Link to …
> Identify network interfaces by mac over name

- supervisor/homeassistant/api.py
Should wait until after nightly core has been published to merge
related https://github.com/home-assistant/core/pull/96860
This call is made OFTEN and its likely the most common api call supervisor makes.
```
Jul 19 17:04:24 homeassistant hassio_supervisor[546]: 23-07-19 12:04:24 INFO (MainThread) [supervisor.host.services] Updating service information
Jul 19 17:04:24 homeassistant hassio_supervisor[546]: 23-07-19 12:04:24 WARNING (MainThread) [supervisor.homeassistant.api] Home Assistant API response: {'latitude': 29.7738, 'longitude': -95.406, 'elevation': 0, 'unit_system': {'length': 'mi', 'accumulated_precipitation': 'in', 'mass': 'lb', 'pressure': 'psi', 'temperature': '°F', 'volume': 'gal', 'wind_speed': 'mph'}, 'location_name': 'N2alex', 'time_zone': 'America/Chicago', …
```
> Switch to using the get core state api call to check if the API is up

- supervisor/addons/validate.py
- supervisor/api/discovery.py
- supervisor/discovery/validate.py
- supervisor/utils/sentry.py
- tests/addons/test_config.py
- tests/api/test_discovery.py
- tests/conftest.py
Supervisor is too protective when it comes to discovery messages. It won't even let the user see an addon if it lists an unknown type of service in discovery. Also removing a service from the list of known types of discovery can cause the discovery json file to fail validation on startup.
This PR makes the following changes:
1. Supervisor will not check the name of the service in discovery messages stored on disk at startup. Any string will pass
2. ~~If an addon lists an unknown type of service in discovery it will still appear in the store. A message will be logged about this at debug level and an event sent to sentry with basic addon details. This event will only be sent once per system per restart of supervisor to limit noise (as we fetch and process addon config regularly)~~
3. If an …
> Allow discovery messages for unknown services with a warning

- supervisor/backups/backup.py
- tests/backups/test_backup.py
Currently the process of making/extracting a backup (collecting everything into a temporary folder) always takes place on the data partition, even if the backup is destined for a mount. This causes unnecessary churn on the data partition. This changes it so temporary operations take place in the same folder that the backup will live in.
> Temporary operations for backups take place in destination folder

- supervisor/addons/__init__.py
Missing an await in a call to `plugin_dns.write_hosts`
```
23-07-31 16:40:27 DEBUG (MainThread) [supervisor.homeassistant.websocket] Queuing message until startup has completed: {'type': <WSType.SUPERVISOR_EVENT: 'supervisor/event'>, 'data': {'event': <WSEve
/usr/src/supervisor/supervisor/addons/__init__.py:462: RuntimeWarning: coroutine 'PluginDns.write_hosts' was never awaited
self.sys_plugins.dns.write_hosts()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
``` …
> Missing an await on dns.write_hosts call

- supervisor/addons/addon.py
- tests/addons/test_addon.py
- tests/addons/test_manager.py
- tests/api/test_addons.py
- tests/api/test_store.py
If addon installation occurs while we're waiting on the addon to tell us it has properly started, ensure that task is cancelled and allowed to complete first. Otherwise it may get stuck and timeout with errors.
> Cancel startup wait task on addon uninstallation

- supervisor/addons/addon.py
- supervisor/docker/addon.py
- supervisor/docker/audio.py
- supervisor/docker/cli.py
- supervisor/docker/dns.py
- supervisor/docker/homeassistant.py
- supervisor/docker/interface.py
- supervisor/docker/multicast.py
- supervisor/docker/observer.py
- supervisor/docker/supervisor.py
- supervisor/exceptions.py
- supervisor/homeassistant/core.py
- supervisor/jobs/__init__.py
- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- supervisor/jobs/job_group.py
- tests/addons/test_manager.py
- tests/api/test_store.py
- tests/conftest.py
- tests/docker/test_addon.py
- tests/homeassistant/test_core.py
- tests/jobs/test_job_decorator.py
- tests/jobs/test_job_manager.py
- tests/plugins/test_audio.py
- tests/plugins/test_dns.py
Replace `process_lock` decorator job decorator by adding a new `JOB_GROUP` execution limitation option. This option allows a thread to grab the lock for the group and then freely make calls to methods which share this common lock while still locking other callers out. Instead of having public methods using a lock and private methods that route around the lock to allow one method to call another after obtaining the singular lock on the class.
Lock ownership is tracked via a contextvar which is cloned per asyncio task. This way we can easily determine what task has grabbed hold of a job group lock and which haven't.
In terms of one job calling another, each job defines what it has access to irrespective of its parent. So if a job in a job group calls another job in that job group, that …
> Add job group execution limit option

- supervisor/validate.py
- tests/addons/test_config.py
- tests/test_validate.py
The current validator allows certain invalid names (e.g. upper case), but disallows valid cases (such as ttl.sh/myimage). Improve the container image validator to support more valid options and at the same time disallow some of the invalid options.
Note that this is not a complete/perfect validation still. A much much more sophisticated regex would be necessary to be 100% accurate. Also we format the string and replace {machine}/{arch} using Python format strings. In that regard the image format in Supervisor deviates from the Docker/OCI container image name format. …
> Extend container image name validator

- supervisor/store/data.py
- tests/addons/test_manager.py
- tests/store/test_reading_addons.py
- tests/store/test_translation_load.py
When processing addon data into the store we understandably do file I/O in the executor. But we also update the store data global in the executor which can cause race conditions. I believe this to be the source of errors like this:
```
23-06-27 23:38:56 INFO (MainThread) [supervisor.addons] Add-on 'core_whisper' successfully updated
23-06-27 23:38:56 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'core_whisper'
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
return await self._method(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/supervisor/supervisor/addons/__init__.py", line 293, in update
self.data.update(store)
File "/usr/src/supervisor/supervisor/addons/data.py", line 58, in update …
```
> Address addon storage race condition

- supervisor/addons/addon.py
- tests/addons/test_addon.py
The organization of the conditional during addon restore meant that if restore attempted to change the version of the addon (like a rollback) the addon was never stopped. This caused two serious issues:
1. The addon version actually did not change after a restore. It would be corrected the next time the addon restarted but immediately after restore the user was still running same version of the addon that they were before the restore
2. Supervisor never properly collected meta information for the container. It cleared out its meta information at the beginning of restore and never got new info because start was skipped (since the addon never stopped running). This caused supervisor to forget its IP address and be unable to direct users to it for ingress after a restore. It showed this …
> Always stop the addon before restoring it

- supervisor/core.py
Don't attempt to notify others about a transition to `CoreState.CLOSE`. Supervisor is about to close the event loop so this just causes a stream of errors as the tasks created from this transition get cancelled like this:
```
23-08-24 16:19:37 ERROR (MainThread) [asyncio] Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/supervisor/supervisor/__main__.py", line 60, in <module>
loop.run_forever()
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
self._run_once()
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
handle._run()
File …
```
> Don't notify listeners on CoreState.CLOSE

- supervisor/core.py
- supervisor/plugins/manager.py
- tests/plugins/test_plugin_manager.py
Plugin manager load should not try to update plugins if supervisor is out of date. They will all fail to update and just make log noise. Supervisor is just going to auto-update and restart again in a moment anyway.
Additionally I noticed that loading the plugin manager was calling `reload` on updater. But core was actually loading updater after plugin manager. I reversed these and removed the call to `reload` in plugin manager as it just caused us to fetch data twice in a row. …
> Skip plugin update on startup if supervisor out of date

- supervisor/addons/addon.py
- supervisor/api/__init__.py
- supervisor/api/backups.py
- supervisor/backups/const.py
- supervisor/backups/manager.py
- supervisor/coresys.py
- supervisor/exceptions.py
- supervisor/homeassistant/module.py
- supervisor/jobs/__init__.py
- supervisor/jobs/const.py
- supervisor/jobs/decorator.py
- tests/api/test_backups.py
- tests/backups/test_manager.py
- tests/jobs/test_job_decorator.py
Users often run HAOS as a VM in software like KVM and Proxmox. These applications all contain snapshot features which quickly take a snapshot of the entire VM. For users of these applications this is significantly easier and faster alternative to backup then supervisor's native backup and restore features. Which makes sense, supervisor can't really compete with disk snapshot features given how and where we are running.
The problem is these features currently create data consistency issues. Home Assistant continues to run and write data to disk at an extremely rapid pace, it is definitely possible to end up with a corrupted database. Just like what used to happen to Supervisor's backups before we put in hooks to pause recorder during backups.
This adds a freeze API. When called it does the …
> Add freeze/thaw apis for external snapshots

- supervisor/addons/__init__.py
- tests/addons/test_addon.py
- tests/backups/test_manager.py
On restore of an addon, supervisor always tells HA to add or delete an ingress panel if the addon has ingress after the restore. This creates two problems:
1. If a version of the addon was restored which does not have ingress, supervisor does not tell HA to remove the panel
2. If the panel is already visible and supervisor says to add it or not visible and supervisor says to delete it the user sees an error like this:
```
2023-09-04 15:19:11.191 ERROR (MainThread) [aiohttp.server] Error handling request
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in …
```
> Only tell HA to refresh ingress on restore on change

- supervisor/api/store.py
- tests/api/test_store.py
The response from `/store/addons` is not consistent with all other supervisor APIs as `data` is a list instead of a dictionary. This causes the issue shown here: https://github.com/home-assistant/cli/pull/360
This is a breaking change as it changes the structure of the response of this existing API. However Core does not rely on this API to our knowledge, it only uses `/store`. The CLI relies on it but cannot use it currently, this will fix it. So it should be safe to make and better to make the API consistent. 
[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist. …
> Correct /store/addons api output

- supervisor/docker/interface.py
- supervisor/homeassistant/core.py
Descendents of Job Groups do not use a a lock member on the class to track whether a task is in progress, they ask the job group if there's an active job. This currently creates issues like `JobGroupExecutionLimitExceeded: Another job is running for job group container_hassio_observer` from plugin watchdog as it does not know another job is already happening.
> JobGroups check active job to determine if in progress

- supervisor/exceptions.py
- supervisor/homeassistant/core.py
- tests/homeassistant/test_core.py
When Supervisor starts core after an update it waits for the API to come up successfully. If it does not then it rolls back the update to prevent users getting stuck with a broken update and no way to fix it (since HA and its UI is down).
Core version `2023.9.0.dev20230816` highlighted a flaw in this logic since it ended up in deadlock. Supervisor assumes that either the API will come up or the container will crash. It's check did not have a timeout to handle the case where neither occurred (container did not crash but API never came up).
This adds a 5 minute timeout to that check. After 5 minutes the check assumes core has had a fatal error and returns a crash exception so the caller knows to proceed as if core has crashed.
- This PR is related to …
> Core API check during startup can timeout

- supervisor/jobs/__init__.py
- supervisor/jobs/decorator.py
- tests/jobs/test_job_decorator.py
Currently jobs which are never started because they fail the limit or condition checks are left around indefinitely. These should always be cleaned up and removed.
- This PR fixes or closes issue: fixes #4564
> Unstarted jobs should always be cleaned up

- supervisor/addons/__init__.py
- supervisor/docker/interface.py
- supervisor/store/addon.py
- tests/addons/test_manager.py
Currently addon update has a possible race condition with the global addon data. This can be triggered as follows:
1. An addon update is initiated
2. While waiting for the new image to download, store data is updated (possibly due to scheduled task)
3. The config of the addon being updated has changed. Specifically if a new version came out or the image was changed
In this situation Supervisor ends up pulling one image but telling the addon a completely different image is in use. And then promptly removing the image it just pulled as it believes it is stale.
The unit test reproduces this race condition by simulating with asyncio events prior to the code change. It is not reproducible afterwards. I believe this change to be the solution to #4610 . Although we can't be certain as we have no …
> Eliminate possible addon data race condition during update

- supervisor/api/proxy.py
- tests/api/test_proxy.py
- tests/fixtures/addons/local/ssh/config.yaml
Currently supervisor can only proxy messages of type text from addons to HA. Some addons need to be able to send binary messages as well.
> Support proxy of binary messages from addons to HA

- supervisor/docker/addon.py
- supervisor/docker/audio.py
- supervisor/docker/cli.py
- supervisor/docker/dns.py
- supervisor/docker/homeassistant.py
- supervisor/docker/interface.py
- supervisor/docker/multicast.py
- supervisor/docker/observer.py
- supervisor/resolution/fixups/addon_execute_repair.py
- tests/docker/test_addon.py
- tests/docker/test_interface.py
- tests/resolution/fixup/test_addon_execute_repair.py
Follow-up to #4619 . Although we believe #4610 should be fixed now, we don't have explicit confirmation that the race condition is the source. In addition there are edge cases where the image can go missing unexpectedly (failure/outtage in the middle of an `ha supervisor repair`, docker update clearing out images, user pruning images with docker cli, etc.)
~~"{x} cannot be started because the image doesn't exist" is not an error we should ever really be showing users. There is nothing they can do about this except submit an issue here and be told to run `ha supervisor repair`. There is however, more supervisor can do to prevent them from ever seeing this error. Namely we can do exactly what `docker run` does - if the image with the specified tag cannot be found locally, pull it.~~
~~This …
> Capture exception if image is missing on run

- supervisor/addons/__init__.py
- supervisor/addons/addon.py
- supervisor/docker/addon.py
- supervisor/plugins/base.py
- tests/addons/test_addon.py
- tests/addons/test_manager.py
- tests/plugins/test_plugin_base.py
Currently backup, restore and update has a race condition with watchdog. Watchdog will see that the addon has stopped and it will not be marked as a manual stop so it believes it is unexpected. This will cause it to try and reanimate it which can cause issues with the process being run. Block this from happening by treating it as a manual stop as it was initiated by the user.
This situation can also occur with plugin updates currently. The PR stops that as well by having watchdog ignore successful stops of the container as that will only occur during plugin updates or system shutdowns, watchdog should not try to reanimate during either of these events. …
> Remove race with watchdog during backup, restore and update

- supervisor/homeassistant/api.py
- supervisor/homeassistant/core.py
- tests/conftest.py
- tests/homeassistant/test_core.py
Currently we check for Core API access and that the state is running. If this is not fulfilled within 5 minutes, we rollback to the previous version.
It can take quite a while until Home Assistant Core is in state running. In fact, after going through bootstrap, it can theoretically take indefinitely (as in there is no timeout from Core side).
~~So to trigger rollback, rather than check the state to be running, just check if the API is accessible in this case. This prevents spurious rollbacks.~~
However, we can almost guarantee that with all timeouts added up, and some margin, the Core should be up in all but the most obscure setups.
Use a two step method, where we check the API responding first before checking the state. This allows to better understand why the Supervisor chose to …
> Use longer timeouts for API checks before trigger a rollback

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- supervisor/addons/addon.py
- supervisor/api/proxy.py
- supervisor/backups/manager.py
- supervisor/core.py
- supervisor/dbus/udisks2/data.py
- supervisor/homeassistant/api.py
- supervisor/misc/scheduler.py
- supervisor/mounts/validate.py
- supervisor/os/manager.py
- supervisor/plugins/observer.py
- supervisor/supervisor.py
- supervisor/updater.py
- supervisor/utils/codenotary.py
- supervisor/utils/dbus.py
- supervisor/utils/pwned.py
- supervisor/utils/whoami.py
- tox.ini
It seems that previous bumps missed bumping in various places. Bump tooling to consistently target Python version 3.11.
> Bump tooling to target Python version 3.11

- supervisor/const.py
- supervisor/ingress.py
- supervisor/validate.py
- tests/test_ingress.py
#4152 broke supervisor's ability to save ingress session data on shutdown because it puts dataclasses directly into `_data` and validation expects dictionaries. Fix this by ensuring `_data` is always a serializable dictionary representation of ingress data and converting to the dataclasses as necessary in methods.
- This PR fixes or closes issue: fixes #4671
> Fix saving ingress data on supervisor shutdown

- supervisor/addons/validate.py
The intention is to warn if the old "config" is used while also one of the new "homeassistant_config" or "addons_config" is used.
> Warn users only when old config is actually used

- supervisor/addons/addon.py
- tests/addons/test_addon.py
An add-on update could start to make use of the add-on config. However, at this point the add-on config directory doesn't exist, which leads to an error. Instead of creating the folder on add-on installation, create the folder on add-on startup to make sure it exists in any case.
- This PR fixes or closes issue: fixes #4689
> Create add-on config folder on add-on start

- supervisor/arch.py
- tests/addons/test_addon.py
- tests/conftest.py
- tests/test_arch.py
Small speed up to arch is_supported by avoiding building two sets every time its called
> Small speed up to arch is_supported

- supervisor/addons/addon.py
- tests/backups/test_manager.py
Do not remove the add-on config when the add-on gets uninstalled. The add-on config directory contains user configuration which the user might like to retain even when uninstalling the add-on. The user can easily delete the directory on his own since it is user can access the directory.
In the future we should consider adding an option at uninstall time to offer removing this directory. But meanwhile not removing it is the better default. …
> Don't remove add-on conifg on add-on removal

- supervisor/docker/addon.py
- tests/docker/test_addon.py
With the new add-on config feature the intention is to provide a good location for add-on specific configurations. Currently, add-ons such as Node RED or ESPHome use the Home Assistant config directory because this location is accessible to the user (via Samba VSCode add-on etc.).
To make it clear to add-on developer that the new intention is to use add-on specific config, the implementation now bind mounts the add-on configuration directory to `/config`. And since some add-ons still need access to the Home Assistant configuration, its config folder is mounted to `/homeassistant` under the new scheme.
However, users do *know* and use the path `/config`, and edit things e.g. through the SSH or VS Code add-on. Also `/config` is still the directory from inside the Core container. The path is …
> Revert Home Assistant configuration to `/config`

- supervisor/docker/addon.py
- tests/docker/test_addon.py
Reverts home-assistant/supervisor#4697
As discussed, reverting this change.
Reasoning:
- `/config` will always point to the active config in the matching container. The Home Assistant container will have its config in `/config`, all plugins have their config in `/config` and add-ons will now have their config in `/config` too.
- `/homeassistant` is where other containers can access the Home Assistant configuration (if needed, but in general, their should not need it).
The above will add consistency to the developer experience (as part of the original intention was for this specific case).
For user-facing add-ons (like ssh, samba, vscode, file editor, e.d.), they will be adopted that they map `config` to `/homeassistant`, so that the change is transparent/non-breaking from the user …
> Revert "Revert Home Assistant configuration to `/config`"

- rootfs/etc/services.d/watchdog/run
It seems that the bashio ping command leads to empty newlines in the Supervisor logs. Redirecting its stdout to /dev/null avoids these empty newlines.
> Avoid empty newlines in Supervisor logs

- supervisor/api/ingress.py
aiohttp < 3.9.0 (fixed in https://github.com/aio-libs/aiohttp/pull/7756) will generate an invalid chunked response aka `"0\r\n\r\n"` instead of an actual empty body if we reached the streaming handler for 204, 304, and a few other cases. Additionally its inefficient to send a `StreamResponse` when a normal `Response` will do in these cases.
I tested this changed with core running aiohttp 3.9.0rc0 and 3.8.5, and supervisor running aiohttp 3.8.6 and 3.9.0rc0
When we upgrade to 3.9.0 we should replace this check with the aiohttp `must_be_empty_body` helper:
https://github.com/aio-libs/aiohttp/blob/8ae650bee4add9f131d49b96a0a150311ea58cd1/aiohttp/helpers.py#L1061
- Link to cli pull …
> Ensure empty body responses never generate an invalid chunked response

- requirements.txt
- supervisor/api/__init__.py
This is a non-fork version of https://github.com/home-assistant/supervisor/pull/4683
---
The default `UrlDispatcher` implementation does a linear search every which can have a significant [TimeComplexity](https://wiki.python.org/moin/TimeComplexity) when dispatching urls when there are a lot of routes. `FastUrlDispatcher` keeps an index of the urls which allows for fast dispatch.
This solution was original implemented in core as
https://github.com/home-assistant/core/blob/241e8560e99da4cbd3c9f763d77cfbd8badb1c66/homeassistant/components/http/__init__.py#L592
It is now in a PyPI package so it can be reused in other projects until aiohttp 3.10 which will solve the problem via https://github.com/aio-libs/aiohttp/pull/7829
- This PR is related to …
> Use aiohttp-fast-url-dispatcher to avoid linear searching to route urls

- supervisor/__main__.py
- supervisor/utils/logging.py
- tests/utils/test_logging.py
Move logging I/O to another thread to avoid blocking the event loop by porting the same solution we have in [core](https://github.com/home-assistant/core/blob/bee457ed6f6dd623fd785169a0815f04deb3f192/homeassistant/util/logging.py#L63)
fixes #4715
> Move logging I/O to another thread to avoid blocking the event loop

- supervisor/ingress.py
- tests/test_ingress.py
Ingress session cleanup was adding `None` into data when we had a session with no session data (which is common). This created a lot of issues when we attempted to save ingress data since `None` is invalid at that spot.
> Fix ingress session cleanup

- requirements.txt
- supervisor/api/__init__.py
Reverts home-assistant/supervisor#4714 due to https://github.com/aio-libs/aiohttp/issues/7864
> Revert "Bump aiohttp to 3.9.0"

- supervisor/dbus/agent/__init__.py
- supervisor/dbus/hostname.py
- supervisor/dbus/logind.py
- supervisor/dbus/network/__init__.py
- supervisor/dbus/network/dns.py
- supervisor/dbus/network/settings.py
- supervisor/dbus/rauc.py
- supervisor/dbus/resolved.py
- supervisor/dbus/systemd.py
- supervisor/dbus/timedate.py
- supervisor/dbus/udisks2/__init__.py
- supervisor/exceptions.py
- supervisor/utils/dbus.py
- tests/dbus/agent/test_agent.py
- tests/dbus/network/test_dns.py
- tests/dbus/network/test_network_manager.py
- tests/dbus/network/test_settings.py
- tests/dbus/test_hostname.py
- tests/dbus/test_login.py
- tests/dbus/test_rauc.py
- tests/dbus/test_resolved.py
- tests/dbus/test_timedate.py
- tests/utils/test_dbus.py
There are quite some errors captured which are related by seemingly a suddenly missing NetworkManager. Errors appear as: 
```
23-11-21 17:42:50 ERROR (MainThread) [supervisor.dbus.network] Error while processing /org/freedesktop/NetworkManager/Devices/10: Remote peer disconnected
...
23-11-21 17:42:50 ERROR (MainThread) [supervisor.dbus.network] Error while processing /org/freedesktop/NetworkManager/Devices/35: The name is not activatable
```
Both errors seem to already happen at introspection time, however the current code doesn't converts these errors to Supervisor issues. This PR uses the already existing `DBus.from_dbus_error()`.
Furthermore this adds a new Exception `DBusNoReplyError` for the `ErrorType.NO_REPLY` (or `org.freedesktop.DBus.Error.NoReply` in D-Bus terms, which is the …
> Improve D-Bus error handling for NetworkManager

- supervisor/mounts/mount.py
- tests/api/test_mounts.py
- tests/backups/test_manager.py
- tests/dbus_service_mocks/systemd.py
- tests/mounts/test_manager.py
- tests/mounts/test_mount.py
- tests/resolution/fixup/test_mount_execute_remove.py
The current code does not wait until the (bind) mount unit has been actually deactivated (state "inactive"). This is especially problematic when restoring a backup, where we deactivate all bind mounts before restoring the target folder. Before the tarball is actually restored, we delete all contents of the target folder. This lead to the situation where the "rm -rf" command got executed before the bind mount actually got unmounted.
The current code polls the state using an exponentially increasing delay. Wait up to 30s for the bind mount to actually deactivate.
Fixes: #4711, #4726 …
> Wait until mount unit is deactivated on unmount

- supervisor/addons/addon.py
- tests/addons/test_addon.py
- tests/fixtures/addons/local/example/config.yaml
Instead of setting the ingress port on install, make sure to set the port when the add-on gets loaded (on Supervisor startup and before installation). This is necessary since a dynamic ingress port is not stored as part of the add-on data storage themself but in the ingress data store. So on every Supervisor start the port needs to be transferred to the add-on model.
Note that we still need to check the port on add-on update since the add-on potentially added (dynamic) ingress on update. Same applies to add-on restore (the restored version might use a dynamic ingress port).
This addresses the following issue seen on the dev channel:
```
23-12-06 10:11:36 ERROR (MainThread) [aiohttp.server] Error handling request
File …
```
> Check/get ingress port on add-on load

- .github/workflows/ci.yaml
Currently pre-commit caching seems not to work properly: There is no cache stored according to GitHub Action tab, and the Prepare Python dependencies job shows the following warning: Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
This seems to be similar to what have been observed and solved in Home Assistant Core with https://github.com/home-assistant/core/pull/46696. Use PRE_COMMIT_CACHE instead of PRE_COMMIT_HOME as well. …
> Fix pre-commit GitHub Action cache

- supervisor/core.py
- tests/test_core.py
In case of an exception "data" is not set leading to an error: cannot access local variable 'data' where it is not associated with a value
Make sure to fallback to the non-SSL whoami call properly.
- This PR fixes or closes issue: fixes #4753
> Fix fallback to non-SSL whoami call

- supervisor/dbus/network/setting/generate.py
It seems that the values for auth-alg and key-mgmt got mixed up. Trying to safe a WEP configuration currently leads to the error:
```
23-12-19 10:56:37 ERROR (MainThread) [supervisor.host.network] Can't create config and activate wlan0: 802-11-wireless-security.key-mgmt: 'open' is not a valid value for the property
```
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/105879
> Fix WiFi WEP configuration

- supervisor/homeassistant/core.py
- supervisor/plugins/cli.py
- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
- supervisor/plugins/observer.py
- tests/homeassistant/test_core.py
As shown in home-assistant/operating-system#3007, error messages printed to logs when container installation fails can cause some confusion, because they are sometimes printed to the log on the landing page. Adjust all wordings of "retry in" to "retrying in" to make it obvious this happens automatically.
- This PR fixes or closes issue: fixes home-assistant/operating-system#3007
> Adjust "retry in ..." log messages to avoid confusion

- supervisor/misc/tasks.py
- tests/misc/test_tasks.py
In sentry we're seeing cases where supervisor tries to reanimate Home Assistant every 8 minutes indefinitely, failing every time. There is clearly something very wrong with these systems but without more info we're not sure what it is. However whatever is wrong, Supervisor cannot fix it by attempting to restart the container. So it should stop trying after 5 failed attempts in a row to avoid filling up the log with noise.
> Set max reanimation attempts on HA watchdog

- supervisor/addons/addon.py
- supervisor/docker/addon.py
- tests/addons/test_manager.py
When using multi-architecture container images, the architecture of the add-on is not passed to Docker in all cases. This causes the architecture of the Supervisor container to be used, which potentially is not supported by the add-on in question.
This commit passes the architecture of the add-on to Docker, so that the correct image is pulled.
- This PR fixes or closes issue: fixes #4402
> Always pass explicit architecture of installed add-ons

- supervisor/backups/backup.py
- supervisor/backups/manager.py
- supervisor/exceptions.py
- supervisor/homeassistant/module.py
- tests/backups/conftest.py
- tests/backups/test_manager.py
When something goes wrong in restore users often have no idea since all we do is log a warning or error. When we do return an error all the UI says is "something went wrong, check the logs". This is particularly egregious during onboarding since the users can't even check supervisor logs.
This PR changes it so we raise an exception with what went wrong if the restore process did not begin due to invalid input or if restore was halted with an exception. If restore proceeded to the end but something went wrong along the way we always return `False` to tell users to check the logs to see what worked and what didn't.
The last part is not ideal but currently we have no other option. Restore can be partially successful, we don't have a good way to inform and display the details of what happened …
> Improve error handling in backup restore

- requirements.txt
- supervisor/api/auth.py
- supervisor/api/utils.py
- supervisor/utils/json.py
- tests/utils/test_json.py
Improve json performance by porting core orjson utils
core has to wait for supervisor to build and reply to its api requests before startup can proceed which slows down core startup a bit since everything is core depends on hassio when its in use
Additionally there is a noticeable by humans improvement in the load times of applications running through ingress.
> Improve json performance by porting core orjson utils

- supervisor/addons/addon.py
Add-ons which use ingress fail to start after rebuild because the ingress port doesn't get set properly. Make sure to set the ingress port after rebuild.
- This PR fixes or closes issue: fixes #4807
> Fix add-on rebuild with ingress

- supervisor/addons/addon.py
- supervisor/addons/const.py
- supervisor/addons/model.py
- supervisor/addons/validate.py
- supervisor/misc/tasks.py
- tests/addons/test_addon.py
- tests/fixtures/addons/local/example/config.yaml
Provide addon developers with a way to list breaking versions of their addons. This way we can block auto-updates which would cross one of these breaking versions and prevent bad situations like what happened recently with Nginx Proxy Manager.
- Link to documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/2056
> Addon devs can block auto update for breaking versions

- supervisor/jobs/__init__.py
- tests/jobs/test_job_manager.py
Changes to jobs are immediately reported to Home Assistant via websockets. When the change is to the `errors` field we are attempting to pass the instance of `SupervisorJobError` which is not serializable, causing this:
```
24-01-29 21:58:44 ERROR (MainThread) [asyncio] Task exception was never retrieved                                                                                                                                                                                                                                             
future: <Task finished name='Task-5951' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:318> exception=TypeError('Object of type SupervisorJobError is not JSON serializable')> …
```
> Fix serialization issue adding error to job

- supervisor/api/proxy.py
- supervisor/homeassistant/websocket.py
I missed that these need to have `dumps` passed. Noticed in https://github.com/home-assistant/supervisor/pull/4853#issue-2106939371
> Use json_dumps helper for websocket messages

- supervisor/misc/tasks.py
- tests/misc/test_tasks.py
Make sure to reset the failed API call counter after a successful API call. While at it also update the log messages a bit to make it clearer what the problem is exactly.
> Reset failed API call counter on successful API call

- supervisor/backups/manager.py
- supervisor/exceptions.py
- supervisor/mounts/const.py
- supervisor/mounts/manager.py
- supervisor/mounts/mount.py
- supervisor/mounts/validate.py
- tests/api/test_backups.py
- tests/api/test_mounts.py
- tests/backups/test_manager.py
- tests/mounts/test_manager.py
- tests/mounts/test_mount.py
When we fail to mount a media or share type mount it is supposed to mount a read-only file in that spot. This ensures that attempts to write to that folder will fail and report rather then essentially silently fail by writing locally (and then creating other issues later). This logic did not work because it relied on user permissions and all docker containers in the Home Assistant ecosystem run as `root`. This changes the bind mount itself to use the read-only option which causes write failures even for `root`.
Since there was a feature request to create mounts of type media and share as read-only this was extended into a feature. Users can now make read-only mounts of type media and share.
As for backup type mounts, we expected that if the user tried to make a backup on a downed mount …
> Improve error handling when mounts fail

- supervisor/dbus/const.py
- supervisor/dbus/systemd.py
- supervisor/mounts/manager.py
- supervisor/mounts/mount.py
- tests/api/test_backups.py
- tests/api/test_mounts.py
- tests/backups/test_manager.py
- tests/conftest.py
- tests/mounts/test_manager.py
- tests/mounts/test_mount.py
- tests/resolution/fixup/test_mount_execute_reload.py
- tests/resolution/fixup/test_mount_execute_remove.py
All mount status checks only looked at the state reported by the systemd unit. If that was `active` they assumed the connection was live. This state does not actually reflect this though, it just tells us whether the mount process is live. To check if the the connection is actually working, you need to use something like `mountpoint` or `pathlib.Path.is_mount`.
This check now happens in all major mount processes (mount, load, reload, and update). If it does not succeed then an error is reported to the user. And if the user was attempting to fix the "mount not working" repair, it should only dismiss if the connection is intact.
Additionally improved the state checking process to use signals instead of polling dbus.
- …
> Mount status checks look at connection

- supervisor/api/utils.py
- supervisor/exceptions.py
- tests/api/test_discovery.py
> APIForbidden should result in 403 status

- supervisor/homeassistant/core.py
- tests/homeassistant/test_home_assistant_watchdog.py
If core had failed immediately prior to an OS shutdown or while supervisor is restarting then its watchdog will cause it to start immediately during the `SETUP` phase of supervisor. Instead of waiting until Supervisor normally starts it in the `STARTUP` phase.
We need to skip processing this initial on attach event like we do for plugins and let supervisor always start Home Assistant as normal during `STARTUP`
> Avoid Watchdog starting Core before Supervisor is in startup

- supervisor/dbus/network/setting/generate.py
Make sure NetworkManager connections are named correctly for VLANs as well (<interface-name>.<vlan-id>).
- This PR is related to issue: #4383
> Format NetworkManager connection name correctly for VLANs

- supervisor/docker/const.py
- tests/docker/__init__.py
- tests/docker/test_addon.py
- tests/docker/test_audio.py
- tests/docker/test_homeassistant.py
As described in #4996, Docker 25+ changes made sub-mounts of the /dev filesystem to be mounted read-only. Revert to the previous behavior by adjusting the ReadOnlyNonRecursive option. Cleaner way would be to upstream support for setting this option via Mount class arguments, so this change is meant to be rather a hotfix for the issue. Even better approach would be mounting /dev non-recursively, and taking care of creating all necessary filesystems when creating containers in Supervisor.
This change was also tested on HAOS 12.0 with Docker 24.0.7 - it just ignores the extra option without any fuss in logs.
- This PR fixes or closes issue: fixes #4996
- This PR is related to issue: #4827
If API endpoints of add-on …
> Fix submounts of /dev being read-only with Docker 25+

- supervisor/api/__init__.py
- supervisor/api/addons.py
- supervisor/api/audio.py
- supervisor/api/dns.py
- supervisor/api/homeassistant.py
- supervisor/api/host.py
- supervisor/api/multicast.py
- supervisor/api/supervisor.py
- supervisor/api/utils.py
- tests/api/__init__.py
- tests/api/test_addons.py
- tests/api/test_audio.py
- tests/api/test_dns.py
- tests/api/test_homeassistant.py
- tests/api/test_host.py
- tests/api/test_multicast.py
- tests/api/test_supervisor.py
Replace all logs endpoints using container logs with wrapped advanced_logs function, adding possibility to get logs from previous boots and following the logs. Supervisor logs are an excetion where Docker logs are still used - in case an exception is raised while accessing the Systemd logs, they're used as fallback - otherwise we wouldn't have an easy way to see what went wrong.
- This PR fixes or closes issue: fixes #3309
- Link to cli pull request: https://github.com/home-assistant/cli/pull/471
> Use Systemd Journal API for all logs endpoints in API

- supervisor/docker/manager.py
CoreDNS forward plug-in fails in ~6s, then fallback triggers. However, the default timeout of glibc and musl is 5s. Increase default timeout to make sure CoreDNS fallback is working on first query.
Background: Default timeout of libc (getaddrinfo`):
* [musl in src/network/resolvconf.c](https://git.musl-libc.org/cgit/musl/tree/src/network/resolvconf.c#n17) 
* [glibc resolv/resolv.h](https://elixir.bootlin.com/glibc/glibc-2.39/source/resolv/resolv.h#L68)
The option `timeout` allows to configure this timeout.
Note that there is also an option `attempts`, which is 2 by default. From observation, these attempts are done within the 5s window. This means that even the second attempt of the C library will fail. When the local (forwarded) DNS server did not respond, and CoreDNS used the fallback, …
> Increase DNS timeout for CoreDNS users

- supervisor/addons/addon.py
- supervisor/addons/build.py
- supervisor/api/homeassistant.py
- supervisor/docker/addon.py
- supervisor/docker/interface.py
- supervisor/homeassistant/const.py
- supervisor/homeassistant/core.py
- supervisor/homeassistant/module.py
- supervisor/homeassistant/validate.py
- supervisor/os/data_disk.py
- supervisor/plugins/audio.py
- supervisor/plugins/base.py
- supervisor/plugins/cli.py
- supervisor/plugins/dns.py
- supervisor/plugins/multicast.py
- supervisor/plugins/observer.py
- supervisor/resolution/checks/multiple_data_disks.py
- supervisor/resolution/const.py
- supervisor/resolution/fixups/system_adopt_data_disk.py
- tests/addons/test_addon.py
- tests/addons/test_manager.py
- tests/api/test_homeassistant.py
- tests/conftest.py
- tests/homeassistant/test_core.py
- tests/homeassistant/test_module.py
- tests/plugins/test_plugin_base.py
- tests/resolution/check/test_check_multiple_data_disks.py
- tests/resolution/fixup/test_system_adopt_data_disk.py
When a user plugs in an existing data disk from another system we encourage them to rename it otherwise it causes a race condition at startup. However users often expect another option - to use it as their data disk. For example if they just purchased a new system they might expect to move the external data disk from one to the other and have it keep working.
This adds that option. It largely works as is. However at startup we now check all the images to see if we have the right ones for the current machine/architecture. Because if you move a data disk from one system to another we may need to get all new images depending on what changed.
PR in core to add translation strings and support for this new repair: https://github.com/home-assistant/core/pull/114891
- This PR fixes or closes …
> Allow adoption of existing data disk

- supervisor/addons/addon.py
- tests/addons/test_addon.py
An error while pulling or building the image for an addon during load should not cause setup to fail, these should not raise out of `load`.
- This PR fixes or closes issue: fixes #5009
> Addon load should not fail due to docker error

- supervisor/mounts/manager.py
- supervisor/mounts/mount.py
- tests/mounts/test_manager.py
Mount manager reload is currently called every 15 minutes to get an update on the state of all mounts. Currently it only attempts to reload or mount a failed mount on first failure, after that it pops a repair and leaves it up to the user to fix.
Now it will attempt reload of all failures anytime it is reloaded. This will help users that don't run a NAS 24/7 and turn it off on certain times and days. Currently if those users happen to reboot or update supervisor at that time they have to manually fix it after turning on their NAS, now Supervisor will fix it for them eventually (15 minutes max).
The downside here is there will be a lot more logging. If a NAS is actually down long-term and the mount is still configured in Supervisor it will keep trying and logging the failure every 15 …
> Mount manager reload mounts all failed mounts

- supervisor/api/__init__.py
- supervisor/api/store.py
- tests/api/test_store.py
The status code of the changelog API when an addon had no changelog was accidently chnaged in #4972 . This PR changes it back to a 200 in this case and adds a unit test. It also fixes the `/store/addons/{slug}/changelog` API as it appears that hasn't worked for a long time (frontend is still using the supposedly deprecated `/addons/{slug}/changelog` and that did work).
As an aside this feels very hacky. We should simply return a 404 and the frontend should have the text to display in that case with localization. Supervisor should not be returning the message presented directly to users in this case.
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/116470
If …
> Fix no changelog API response

- supervisor/homeassistant/module.py
The landing page doesn't need access to hardware anyways, so avoid processing hardware events while landing page is running.
Reported by a user on the community: https://community.home-assistant.io/t/upgrading-haos-12-1-to-12-3-fails-on-rpi-3
> Don't process hardware events when landing page is running

- supervisor/api/store.py
- tests/api/test_store.py
Follow-up to #5064 . It appears orphaned addons return 400 responses to `/changelog` that the frontend cannot interpret. While digging I noticed that the `/documentation` API has the same problem, it just hasn't come up yet (probably because `update` entities do not hit it in the background like they do with the changelog).
Changed both these APIs so they go back to returning 200 responses with the error as text. As noted in the other PR, we should really handle this differently. Although in this case I'm not sure a 404 makes sense since this is a bit odd. Still it would be nice to have the API correctly report an error and the frontend show the appropriate text rather then having supervisor return error text to display to users.
- This PR fixes or closes issue: fixes #5076
- This PR is …
> Fix doc and changelog API response for orphaned addons

- .devcontainer/devcontainer.json
Migrate supervisor's devcontainer to use uv instead of pip for faster installs. Depends on https://github.com/home-assistant/devcontainer/pull/86
> Migrate supervisor devcontainer from pip to uv

- supervisor/utils/__init__.py
With PR #5634 (which had the goal to remove I/O in event loop for backup operations) the semantics of `remove_folder` changed slightly: Non-zero exits of subprocesses were no longer handled, but lead to a CalledProcessError.
Now to restore the semantics of `remove_folder` we should simply log an error. However, this semantic change actually uncovered a potential problem in deployed systems: There are 34 users on beta channel which regularly seem to run `FixupStoreExecuteReset`, and with the semantic change we see those errors in Sentry.
An obvious problem could be no space. But in a quick test that would not execute the repair in first place since the fixup has the job condition `FREE_SPACE` set. So the problem is likely elsewhere.
With this change, we log the stderr of find, while still …
> Handle non-zero subprocess exits

- supervisor/os/manager.py
- tests/os/test_manager.py
In #6024 we mark a system as unhealthy when multiple OS installations were found. The idea was to block OS updates in this case. However, it turns out that the OS update job was not checking the system health and thus allowed updates even when the system was marked as unhealthy.
This commit adds the `JobCondition.HEALTHY` condition to the OS update job, ensuring that OS updates are only performed when the system is healthy.
Users can force an OS update still by using `ha jobs options --ignore-conditions healthy`. …
> Block OS updates when the system is unhealthy

- supervisor/resolution/const.py
- supervisor/resolution/evaluations/os_version.py
- tests/resolution/evaluation/test_evaluate_os_version.py
Only the last 4 versions of OS are supported. Add an evaluation that marks system as unsupported if running a version of OS older then that.
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/40132
- Link to client library pull request: https://github.com/home-assistant-libs/python-supervisor-client/pull/140
- Link to Core PR for repair support: https://github.com/home-assistant/core/pull/149837
[cli-repository]: …
> Add unsupported reason os_version and evaluation

- supervisor/resolution/checks/disk_lifetime.py
- supervisor/resolution/const.py
- tests/resolution/check/test_check_disk_lifetime.py
Create an issue (which will become a repair) when disk lifetime has exceeded 90%.
- This PR is related to issue: #6064
[client-library-repository]: https://github.com/home-assistant-libs/python-supervisor-client/
> Add an issue for disk lifetime >=90%

- supervisor/jobs/decorator.py
- supervisor/jobs/job_group.py
- tests/jobs/test_job_decorator.py
Refactors JobGroup concurrency system to enable external lock management. This allows to release Job group locks outside of a running Job context, which allows the use of context manager in the decorator and execution limits combined with group concurrency parameters.
**JobGroup** (supervisor/jobs/job_group.py):
- Add `release(job)` parameter to enable external lock release with ownership verification
- Add `is_locked_by(job)` helper methods
**Job Decorator** (supervisor/jobs/decorator.py):
- Add helper methods `_is_group_concurrency()` and `_is_group_throttle()` for cleaner logic separation
- Remove all `cast(JobGroup, job_group)` calls by using proper type checking
- Change from `asyncio.Semaphore()` to `asyncio.Lock()` for consistency with `JobGroup`
- Enable throttling with group …
> Improve JobGroup locking with external ownership tracking

- supervisor/api/supervisor.py
- supervisor/core.py
- supervisor/dbus/timedate.py
- supervisor/host/control.py
- tests/dbus/test_timedate.py
- tests/host/test_control.py
- tests/test_core.py
With home-assistant/operating-system#4224, timezone setting in OS can be peristently set in HAOS as well. Propagate the timezone configured in Supervisor config (which can be changed through general system settings in HA Core) through the DBus API for setting the timezone.
[client-library-repository]: …
> Propagate timezone setting to host in OS 16.2 and newer

- supervisor/addons/validate.py
- tests/addons/test_config.py
Fix crash when addon configurations contain malformed map entries missing the required `type` field. This issue was introduced by commit 1fb15772d which added `addon.map_volumes` access in docker config checks, exposing a validation bug in the addon config migration code.
The problem occurred when addon configurations contained YAML entries like:
```yaml
map:
- addon_config: rw
```
This creates `{"addon_config": "rw"}` which lacks the required `"type"` field, causing a `KeyError: 'type'` during migration before schema validation could run.
The fix:
1. **Validates dict entries** during migration and skips invalid ones with helpful warnings
2. **Always updates config** with filtered results to replace malformed entries 
3. **Provides clear diagnostics** to help addon developers fix their …
> Handle malformed addon map entries gracefully

- supervisor/core.py
- supervisor/resolution/module.py
This PR optimizes the resolution manager initialization to avoid duplicate `evaluate_system()` calls during supervisor setup. 
Currently, when the resolution manager loads, it calls `healthcheck()` which internally calls `evaluate_system()`. However, during the setup stage, the supervisor's main setup process also calls `evaluate_system()`, creating redundant system evaluation work.
Remove the `evaluate_system()` in the setup stage. Also move the OS Agent diagnostics initialization into the start phase. This allows to leverage the broad exception handling. Finally check if OS Agent is connected at all, which prevents the common case of D-Bus not being available without causing exceptions. Supervisor already raises an error earlier if OS Agent is missing.
- This PR fixes or closes issue: …
> Avoid duplicate evaluate_system() calls during resolution manager setup

- supervisor/host/control.py
When timedatectl is not available (e.g. in minimal devcontainers), the code currently fails to setup due to missing timedate service on D-Bus. This change makes the code more robust by checking only checking for the presence of the service if we actually going to use it.
- This PR fixes or closes issue: fixes #6146
[client-library-repository]: …
> Avoid setup failure on missing timedatectl

- supervisor/addons/options.py
- supervisor/addons/validate.py
- tests/addons/test_config.py
- tests/addons/test_options.py
Remove the arbitrary (and undocumented) restrictions on how lists and dicts can be nested within themselves and each other in addon config schemas, so e.g. the following is now allowed:
```yaml
schema:
filters:
- conditions:
- property: str
condition: list(equal|not_equal)
value: str
actions:
accept: bool?
latency: int?
```
The only remaining restriction is that list-of-lists (`field: [[str]]`) are disallowed, because there's no way to represent them in the current encoding for `UiOptions` (and they can already be represented in a more self-documenting way: `field: [{subfield: [str]}]`).
The current documentation at https://developers.home-assistant.io/docs/add-ons/configuration#options--schema does not mention the restrictions, and as such does not require an update per-se.
A …
> Allow deeply nested dicts and lists in addon config schemas

- supervisor/addons/addon.py
- supervisor/addons/manager.py
- supervisor/api/proxy.py
- supervisor/auth.py
- supervisor/discovery/__init__.py
- supervisor/homeassistant/api.py
- supervisor/homeassistant/websocket.py
- supervisor/ingress.py
- supervisor/resolution/notify.py
This PR optimizes Home Assistant API connection handling by removing redundant port checks that were creating unnecessary socket connections. The main improvement eliminates duplicate socket creation during API connectivity checks.
**Key Performance Optimization:**
- **Remove redundant port checks**: Previously, each API connectivity check performed both a port check and then an actual API request, creating two socket connections per check
- **Significant socket reduction**: During a typical Supervisor startup when Home Assistant Core is running (e.g., after a Supervisor update), approximately 10 successful API checks are made. This change eliminates 10 unnecessary socket creations per startup since aiohttp connections are reused for the actual API calls
- **Simplified token management**: …
> Optimize API connection handling by removing redundant port checks
